// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newKbCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "kb",
		Short:       "Knowledge Base categories and answers",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newKbAnswerCreateCmd(flags))
	cmd.AddCommand(newKbAnswerDeleteCmd(flags))
	cmd.AddCommand(newKbAnswerInternalCmd(flags))
	cmd.AddCommand(newKbAnswerPublishCmd(flags))
	cmd.AddCommand(newKbCategoryCreateCmd(flags))
	cmd.AddCommand(newKbInitCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelKbBrowseCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelKbGetCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelKbSearchCmd(flags))
	return cmd
}
