// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newTicketsCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyTitle string
	var bodyGroup string
	var bodyCustomerId string
	var bodyStateId int
	var bodyPriorityId int
	var bodyOwnerId int
	var bodyOrganizationId int
	var bodyArticleSubject string
	var bodyArticleBody string
	var bodyArticleType string
	var bodyArticleInternal bool
	var bodyArticleContentType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create",
		Short:       "Create a ticket. Provide title, group, a customer, and an initial article.",
		Annotations: map[string]string{"pp:endpoint": "tickets.create", "pp:method": "POST", "pp:path": "/tickets", "pp:requires-input": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("title") && bodyTitle == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "title")
				}
			}
			path := "/tickets"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				if cmd.Flags().Changed("title") || bodyTitle != "" {
					bodyMap["title"] = bodyTitle
				}
				if cmd.Flags().Changed("group") || bodyGroup != "" {
					bodyMap["group"] = bodyGroup
				}
				if cmd.Flags().Changed("customer-id") || bodyCustomerId != "" {
					bodyMap["customer_id"] = bodyCustomerId
				}
				if cmd.Flags().Changed("state-id") || bodyStateId != 0 {
					bodyMap["state_id"] = bodyStateId
				}
				if cmd.Flags().Changed("priority-id") || bodyPriorityId != 0 {
					bodyMap["priority_id"] = bodyPriorityId
				}
				if cmd.Flags().Changed("owner-id") || bodyOwnerId != 0 {
					bodyMap["owner_id"] = bodyOwnerId
				}
				if cmd.Flags().Changed("organization-id") || bodyOrganizationId != 0 {
					bodyMap["organization_id"] = bodyOrganizationId
				}
				{
					nestedArticle := map[string]any{}
					if cmd.Flags().Changed("article-subject") || bodyArticleSubject != "" {
						nestedArticle["subject"] = bodyArticleSubject
					}
					if cmd.Flags().Changed("article-body") || bodyArticleBody != "" {
						nestedArticle["body"] = bodyArticleBody
					}
					if cmd.Flags().Changed("article-type") || bodyArticleType != "" {
						nestedArticle["type"] = bodyArticleType
					}
					if cmd.Flags().Changed("article-internal") {
						nestedArticle["internal"] = bodyArticleInternal
					}
					if cmd.Flags().Changed("article-content-type") || bodyArticleContentType != "" {
						nestedArticle["content_type"] = bodyArticleContentType
					}
					if len(nestedArticle) > 0 {
						bodyMap["article"] = nestedArticle
					}
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "tickets", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "tickets", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "tickets", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "tickets", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "tickets", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "tickets",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Mutation-riding reads (POST search, RPC-over-POST lists) return
				// the same single-key collection envelopes as GET reads. Unwrap
				// before filtering so rows nest once under the result key and
				// --select filters rows, not envelope keys; plain created-object
				// responses pass through unwrapSingleKeyArray untouched.
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				var selectErr error
				filtered := unwrapSingleKeyArray(data)
				if flags.selectFields != "" {
					filtered, selectErr = filterFieldsChecked(filtered, flags.selectFields)
					selectErr = selectErrorForDryRun(selectErr, flags, data)
				} else if flags.compact {
					filtered = compactFields(filtered, map[string]bool{"id": true, "title": true, "group_id": true, "state_id": true, "priority_id": true, "owner_id": true, "customer_id": true, "organization_id": true, "created_at": true, "updated_at": true})
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				resultKey := "data"
				if flags.agent {
					resultKey = "results"
				}
				structured, err := wrapPlatformStructuredOutput(json.RawMessage(envelopeJSON), flags, resultKey, true)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), structured, true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "tickets", partialFailure.Message))
				}
				return selectErr
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlagsMeta renders the body with live
			// provenance, then the typed partial-failure exit fires unless
			// --allow-partial-failure downgrades it. Without this guard a
			// partial failure would exit 0 for these output modes — the exact
			// silent-swallow regression the surrounding patch is preventing
			// for asJSON / piped output.
			printErr := printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"}, map[string]bool{"id": true, "title": true, "group_id": true, "state_id": true, "priority_id": true, "owner_id": true, "customer_id": true, "organization_id": true, "created_at": true, "updated_at": true})
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "tickets", partialFailure.Message))
			}
			return printErr
		},
	}
	cmd.Flags().StringVar(&bodyTitle, "title", "", "Ticket title / subject")
	cmd.Flags().StringVar(&bodyGroup, "group", "", "Group name (e.g. Users, Support)")
	cmd.Flags().StringVar(&bodyCustomerId, "customer-id", "", "Customer user id or email address")
	cmd.Flags().IntVar(&bodyStateId, "state-id", 0, "State id (1=new, 2=open, 3=pending, 4=closed, 6=resolved)")
	cmd.Flags().IntVar(&bodyPriorityId, "priority-id", 0, "Priority id (1=low, 2=normal, 3=high)")
	cmd.Flags().IntVar(&bodyOwnerId, "owner-id", 0, "Assigned agent user id")
	cmd.Flags().IntVar(&bodyOrganizationId, "organization-id", 0, "Organization id")
	cmd.Flags().StringVar(&bodyArticleSubject, "article-subject", "", "Article subject")
	cmd.Flags().StringVar(&bodyArticleBody, "article-body", "", "Article body")
	cmd.Flags().StringVar(&bodyArticleType, "article-type", "", "Article type: note or email")
	cmd.Flags().BoolVar(&bodyArticleInternal, "article-internal", false, "true = internal note, false = customer-visible")
	cmd.Flags().StringVar(&bodyArticleContentType, "article-content-type", "", "text/html or text/plain")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
