// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCloudDetectionCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "cloud-detection",
		Short:       "Get, disable, create, update, and delete cloud detection",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCloudDetectionActivateRulesCmd(flags))
	cmd.AddCommand(newCloudDetectionCreateRuleCmd(flags))
	cmd.AddCommand(newCloudDetectionDeleteRulesCmd(flags))
	cmd.AddCommand(newCloudDetectionDisableRulesCmd(flags))
	cmd.AddCommand(newCloudDetectionGetAlertsCmd(flags))
	cmd.AddCommand(newCloudDetectionGetRulesCmd(flags))
	cmd.AddCommand(newCloudDetectionUpdateAlertAnalystVerdictCmd(flags))
	cmd.AddCommand(newCloudDetectionUpdateRuleCmd(flags))
	cmd.AddCommand(newCloudDetectionUpdatedThreatIncidentCmd(flags))
	return cmd
}
