// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newConfigOverrideCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "config-override",
		Short:       "Get, create, update, and delete config override",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newConfigOverrideCreateCmd(flags))
	cmd.AddCommand(newConfigOverrideDeleteCmd(flags))
	cmd.AddCommand(newConfigOverrideDeleteConfigoverrideCmd(flags))
	cmd.AddCommand(newConfigOverrideGetCmd(flags))
	cmd.AddCommand(newConfigOverrideUpdateCmd(flags))
	return cmd
}
