// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDvCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "dv",
		Short:       "Get, create, and download dv",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDvCancelRunningQueryCmd(flags))
	cmd.AddCommand(newDvCreateQueryAndGetQueryIdCmd(flags))
	cmd.AddCommand(newDvDownloadSourceProcessFileCmd(flags))
	cmd.AddCommand(newDvGetEventsCmd(flags))
	cmd.AddCommand(newDvGetEventsByTypeCmd(flags))
	cmd.AddCommand(newDvGetProcessStateCmd(flags))
	cmd.AddCommand(newDvGetQueryStatusCmd(flags))
	return cmd
}
