// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newExclusionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "exclusions",
		Short:       "Get, create, update, and delete exclusions",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newExclusionsCreateCmd(flags))
	cmd.AddCommand(newExclusionsDeleteCmd(flags))
	cmd.AddCommand(newExclusionsGetCmd(flags))
	cmd.AddCommand(newExclusionsUpdateCmd(flags))
	cmd.AddCommand(newExclusionsValidateItemCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelExclusionsAuditCmd(flags))
	return cmd
}
