// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFiltersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "filters",
		Short:       "Get, create, update, and delete filters",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newFiltersDeleteCmd(flags))
	cmd.AddCommand(newFiltersDeleteDeepVisibilityCmd(flags))
	cmd.AddCommand(newFiltersGetCmd(flags))
	cmd.AddCommand(newFiltersGetDeepVisibilityCmd(flags))
	cmd.AddCommand(newFiltersSaveCmd(flags))
	cmd.AddCommand(newFiltersSaveDeepVisibilityCmd(flags))
	cmd.AddCommand(newFiltersUpdateCmd(flags))
	cmd.AddCommand(newFiltersUpdateDeepVisibilityCmd(flags))
	return cmd
}
