// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// learn_init.go is the spec-driven init shim for the self-learning loop.
// newLearnConfig builds the per-CLI *entities.Config the cobra teach /
// recall / learnings commands thread through every call site;
// initLearn seeds the entity_lookups table from the canonical-+-aliases
// table declared in spec.Learn.EntityLookupSeeds. Both run once at
// startup; subsequent calls are idempotent (INSERT OR IGNORE on the
// store side, fresh Config build on the registration side).
//
// Soft validation: a runtime regex compile failure (which spec parse
// already rejects at load time) logs to stderr and continues without
// the pattern instead of aborting the CLI. Empty Learn config produces
// a Config with built-in stopwords and a no-op initLearn.

package cli

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"sync"

	"sentinelone-pp-cli/internal/learn/entities"
	"sentinelone-pp-cli/internal/store"
)

// newLearnConfig returns the per-CLI entity extractor Config the
// teach / recall / normalize call sites pass into the learn package.
// Reads the printed-CLI's spec.Learn.TickerPatterns, Stopwords, and
// Synonyms; patterns that fail to compile at runtime (defense in
// depth — spec parse already validated them) log a warning and are
// skipped. Declared synonyms register on both the returned Config and
// the store package's write-side normalizer.
func newLearnConfig() *entities.Config {
	cfg := entities.NewConfig()
	return cfg
}

// initLearn seeds the entity_lookups table from the spec.Learn.
// EntityLookupSeeds declaration. INSERT OR IGNORE on the store side
// makes this idempotent — calling it twice produces the same DB state
// as calling it once. An empty seed map is a no-op (returns nil).
func initLearn(ctx context.Context, db *sql.DB) error {
	_ = ctx
	_ = db
	return nil
}

// learnInitOnce gates runLearnInitOnce so the seed pass happens at
// most once per CLI process. The sync.Once keeps the cost off the
// hot path for repeat command invocations within an MCP session.
var learnInitOnce sync.Once

// runLearnInitOnce opens the canonical store path, fires initLearn
// once per process, and downgrades any failure to a stderr warning.
// Per the self-learning loop's soft-validation contract, a seed
// failure must never abort the CLI — the recall path returns the
// empty envelope if entity_lookups is missing rows, which is the
// same behavior an opt-out CLI sees.
func runLearnInitOnce(ctx context.Context) {
	learnInitOnce.Do(func() {
		dbPath := defaultDBPath("sentinelone-cli")
		s, err := store.OpenWithContext(ctx, dbPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "warning: sentinelone-cli: learn init: open store: %v\n", err)
			return
		}
		defer s.Close()
		if err := initLearn(ctx, s.DB()); err != nil {
			fmt.Fprintf(os.Stderr, "warning: sentinelone-cli: learn init: %v\n", err)
		}
	})
}

// learnCommonIdentityFields is the ordered, domain-neutral list
// ResourceEntitiesFromJSON walks when a resource has no more specific
// identity key. Missing JSON keys are skipped, so one list can serve
// every collection.
var learnCommonIdentityFields = []string{
	"name", "title", "display_name", "full_name", "short_name", "label",
	"slug", "key", "code", "id", "address",
}

// learnResourceTypeFields returns the per-resource identity-field map
// passed to Recall so entity_match can be exact when the stored JSON
// actually carries the identity.
func learnResourceTypeFields() map[string][]string {
	return map[string][]string{
		"accounts":                     {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"actions":                      {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"activities":                   {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"add-tags":                     {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"agents":                       {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"agents-passphrases":           {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"api-token-details":            {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"application-inventory":        {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"application-inventory-counts": {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"applications":                 {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"classification":               {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"cloud-detection":              {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"cloud-detection-rules":        {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"config-override":              {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"configuration":                {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"copy-rules":                   {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"device-control":               {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"download-from-cloud":          {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"dv":                           {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"enable":                       {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"exclusions":                   {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"expire-now":                   {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"explore":                      {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"export":                       {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"filters":                      {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"filters-dv":                   {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"firewall-control":             {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"firewall-control-protocols":   {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"forensics":                    {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"groups":                       {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"hashes":                       {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"import":                       {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"installed-applications":       {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"installed-applications-cves":  {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"json":                         {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"last-activity-as-syslog":      {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"locations":                    {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"move-agents":                  {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"move-rules":                   {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"notes":                        {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"policy":                       {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"protocols":                    {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"ranger":                       {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"ranger-cred-groups":           {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"ranger-gateways":              {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"ranger-table-view":            {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"rbac":                         {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"reactivate":                   {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"regenerate-key":               {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"remote-scripts":               {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"remove-tags":                  {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"reorder":                      {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"report-tasks":                 {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"reports":                      {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"reputation":                   {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"restrictions":                 {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"revert-policy":                {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"rogues":                       {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"sentinelone-export":           {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"sentinelonerss":               {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"set-location":                 {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"settings":                     {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"singularity-marketplace":      {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"site-with-admin":              {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"sites":                        {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"system":                       {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"tags":                         {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"tasks-configuration":          {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"tasks-configuration-has-explicit-subscope": {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"tenant":              {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"tests":               {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"threat-intelligence": {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"threats":             {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"timeline":            {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"uninstall-password":  {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"update":              {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"upload":              {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"uploads":             {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"user":                {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"users":               {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"whitening-options":   {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
	}
}

// learnIdentityFieldsFor returns the identity fields for one resource
// type, falling back to the common list when the type is unknown.
func learnIdentityFieldsFor(resourceType string) []string {
	if fields, ok := learnResourceTypeFields()[resourceType]; ok && len(fields) > 0 {
		return fields
	}
	return append([]string(nil), learnCommonIdentityFields...)
}
