// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newRangerCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "ranger",
		Short:       "Get, create, add, update, and delete ranger",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newRangerAddCredDetailsCmd(flags))
	cmd.AddCommand(newRangerAddNewDeployCommandForDeviceFromAgentFromTaskInfraCmd(flags))
	cmd.AddCommand(newRangerChangeDeviceReviewCmd(flags))
	cmd.AddCommand(newRangerChangeDeviceReviewInBulkCmd(flags))
	cmd.AddCommand(newRangerChangeDeviceTagsCmd(flags))
	cmd.AddCommand(newRangerCreateCredGroupCmd(flags))
	cmd.AddCommand(newRangerDeleteCredGroupCmd(flags))
	cmd.AddCommand(newRangerDeleteCredGroupDetailCmd(flags))
	cmd.AddCommand(newRangerExportDataCmd(flags))
	cmd.AddCommand(newRangerGetCredGroupDetailsCmd(flags))
	cmd.AddCommand(newRangerGetCredGroupsCmd(flags))
	cmd.AddCommand(newRangerGetGatewaysCmd(flags))
	cmd.AddCommand(newRangerGetSettingsCmd(flags))
	cmd.AddCommand(newRangerGetTableCmd(flags))
	cmd.AddCommand(newRangerUpdateCredGroupCmd(flags))
	cmd.AddCommand(newRangerUpdateCredGroupDetailsCmd(flags))
	cmd.AddCommand(newRangerUpdateGatewayCmd(flags))
	cmd.AddCommand(newRangerUpdateGatewaysCmd(flags))
	cmd.AddCommand(newRangerUpdateSettingsCmd(flags))
	cmd.AddCommand(newRangerJsonCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelRangerExposureCmd(flags))
	return cmd
}
