// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newRemoteScriptsGetScriptsCmd(flags *rootFlags) *cobra.Command {
	var flagCursor string
	var flagScriptType string
	var flagAccountIds string
	var flagSortOrder string
	var flagQuery string
	var flagSortBy string
	var flagSiteIds string
	var flagOsTypes string
	var flagLimit string
	var flagSkipCount string
	var flagSkip string
	var flagCountOnly string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-scripts",
		Aliases:     []string{"list"},
		Short:       "Get the SentinelOne scripts from the Script Library.",
		Example:     "  sentinelone-cli remote-scripts get-scripts",
		Annotations: map[string]string{"pp:endpoint": "remote-scripts.get-scripts", "pp:method": "GET", "pp:path": "/remote-scripts", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/remote-scripts"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "auto", "remote-scripts", path, retainCLIQueryParams(cmd, map[string]string{
				"cursor":     formatCLIParamValue(flagCursor),
				"scriptType": formatCLIParamValue(flagScriptType),
				"accountIds": formatCLIParamValue(flagAccountIds),
				"sortOrder":  formatCLIParamValue(flagSortOrder),
				"query":      formatCLIParamValue(flagQuery),
				"sortBy":     formatCLIParamValue(flagSortBy),
				"siteIds":    formatCLIParamValue(flagSiteIds),
				"osTypes":    formatCLIParamValue(flagOsTypes),
				"limit":      formatCLIParamValue(flagLimit),
				"skipCount":  formatCLIParamValue(flagSkipCount),
				"skip":       formatCLIParamValue(flagSkip),
				"countOnly":  formatCLIParamValue(flagCountOnly),
			}, map[string][]string{"cursor": {"cursor"}, "scriptType": {"script-type"}, "accountIds": {"account-ids"}, "sortOrder": {"sort-order"}, "query": {"query"}, "sortBy": {"sort-by"}, "siteIds": {"site-ids"}, "osTypes": {"os-types"}, "limit": {"limit"}, "skipCount": {"skip-count"}, "skip": {"skip"}, "countOnly": {"count-only"}}, "cursor", "cursor"), nil, flagAll, "cursor", "cursor", "limit", 0, "", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			outputData := collectionItemsForOutput(data, path)
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(outputData, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				var selectErr error
				filtered := data
				if flags.selectFields != "" {
					filtered, selectErr = filterFieldsChecked(filtered, flags.selectFields)
					selectErr = selectErrorForDryRun(selectErr, flags, data)
				} else if flags.compact {
					filtered = compactFields(filtered, nil)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				wrapped, wrapErr = wrapPlatformStructuredOutput(wrapped, flags, "results", true)
				if wrapErr != nil {
					return wrapErr
				}
				if err := printOutput(cmd.OutOrStdout(), wrapped, true); err != nil {
					return err
				}
				return selectErr
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, nil)
		},
	}
	cmd.Flags().StringVar(&flagCursor, "cursor", "", "Cursor position returned by the last request. Use to iterate over more than 1000 items.")
	cmd.Flags().StringVar(&flagScriptType, "script-type", "", "Script type. Example: 'artifactCollection'.")
	cmd.Flags().StringVar(&flagAccountIds, "account-ids", "", "List of Account IDs to filter by. Example: '225494730938493804,225494730938493915'.")
	cmd.Flags().StringVar(&flagSortOrder, "sort-order", "", "Sort direction. Example: 'asc'.")
	cmd.Flags().StringVar(&flagQuery, "query", "", "Query")
	cmd.Flags().StringVar(&flagSortBy, "sort-by", "", "The column to sort the results by. Example: 'id'.")
	cmd.Flags().StringVar(&flagSiteIds, "site-ids", "", "List of Site IDs to filter by. Example: '225494730938493804,225494730938493915'.")
	cmd.Flags().StringVar(&flagOsTypes, "os-types", "", "Os types. Example: 'linux'.")
	cmd.Flags().StringVar(&flagLimit, "limit", "", "Limit number of returned items (1-1000). Example: '10'.")
	cmd.Flags().StringVar(&flagSkipCount, "skip-count", "", "If true, total number of items will not be calculated, which speeds up execution time.")
	cmd.Flags().StringVar(&flagSkip, "skip", "", "Skip first number of items (0-1000). To iterate over more than 1000 items, use 'cursor'. Example: '150'.")
	cmd.Flags().StringVar(&flagCountOnly, "count-only", "", "If true, only total number of items will be returned, without any of the actual objects.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
