// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSentineloneExportCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "sentinelone-export",
		Short:       "List and get sentinelone export",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSentineloneExportActivitiesCmd(flags))
	cmd.AddCommand(newSentineloneExportAgentsCmd(flags))
	cmd.AddCommand(newSentineloneExportEventsCmd(flags))
	cmd.AddCommand(newSentineloneExportListInstalledApplicationsCmd(flags))
	cmd.AddCommand(newSentineloneExportThreatTimelineCmd(flags))
	return cmd
}
