// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSettingsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "settings",
		Short:       "Get, create, update, and delete settings",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSettingsClearPendingEmailsCmd(flags))
	cmd.AddCommand(newSettingsDeleteNotificationRecipientCmd(flags))
	cmd.AddCommand(newSettingsGetAdCmd(flags))
	cmd.AddCommand(newSettingsGetAdFqdnsCmd(flags))
	cmd.AddCommand(newSettingsGetMicrosoftCmd(flags))
	cmd.AddCommand(newSettingsGetNotificationCmd(flags))
	cmd.AddCommand(newSettingsGetNotificationRecipientsCmd(flags))
	cmd.AddCommand(newSettingsGetSmsCmd(flags))
	cmd.AddCommand(newSettingsGetSmtpCmd(flags))
	cmd.AddCommand(newSettingsGetSsoCmd(flags))
	cmd.AddCommand(newSettingsGetSyslogCmd(flags))
	cmd.AddCommand(newSettingsSetAdCmd(flags))
	cmd.AddCommand(newSettingsSetAdFqdnsCmd(flags))
	cmd.AddCommand(newSettingsSetMicrosoftCmd(flags))
	cmd.AddCommand(newSettingsSetNotificationCmd(flags))
	cmd.AddCommand(newSettingsSetNotificationRecipientsCmd(flags))
	cmd.AddCommand(newSettingsSetSmsCmd(flags))
	cmd.AddCommand(newSettingsSetSmtpCmd(flags))
	cmd.AddCommand(newSettingsSetSsoCmd(flags))
	cmd.AddCommand(newSettingsSetSyslogCmd(flags))
	cmd.AddCommand(newSettingsTestAdCmd(flags))
	cmd.AddCommand(newSettingsTestMicrosoftCmd(flags))
	cmd.AddCommand(newSettingsTestSmtpCmd(flags))
	cmd.AddCommand(newSettingsTestSsoCmd(flags))
	cmd.AddCommand(newSettingsTestSyslogCmd(flags))
	return cmd
}
