// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSitesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "sites",
		Short:       "Get, create, update, and delete sites",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSitesCreateCmd(flags))
	cmd.AddCommand(newSitesCreateDuplicateCmd(flags))
	cmd.AddCommand(newSitesDeleteCmd(flags))
	cmd.AddCommand(newSitesGetCmd(flags))
	cmd.AddCommand(newSitesGetByIdCmd(flags))
	cmd.AddCommand(newSitesUpdateCmd(flags))
	cmd.AddCommand(newSitesExpireNowCmd(flags))
	cmd.AddCommand(newSitesPolicyCmd(flags))
	cmd.AddCommand(newSitesReactivateCmd(flags))
	cmd.AddCommand(newSitesRegenerateKeyCmd(flags))
	cmd.AddCommand(newSitesRevertPolicyCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelSitesRiskCmd(flags))
	return cmd
}
