// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newThreatsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "threats",
		Short:       "Get, fetch, disable, create, add, and update threats",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newThreatsAddNoteToMultipleCmd(flags))
	cmd.AddCommand(newThreatsAddToBlacklistCmd(flags))
	cmd.AddCommand(newThreatsAddToExclusionsCmd(flags))
	cmd.AddCommand(newThreatsDisableEnginesCmd(flags))
	cmd.AddCommand(newThreatsExportCmd(flags))
	cmd.AddCommand(newThreatsExportMitigationReportCmd(flags))
	cmd.AddCommand(newThreatsFetchFileCmd(flags))
	cmd.AddCommand(newThreatsGetCmd(flags))
	cmd.AddCommand(newThreatsMitigateCmd(flags))
	cmd.AddCommand(newThreatsUpdateAnalystVerdictCmd(flags))
	cmd.AddCommand(newThreatsUpdateExternalTicketIdCmd(flags))
	cmd.AddCommand(newThreatsUpdatedIncidentCmd(flags))
	cmd.AddCommand(newThreatsDownloadFromCloudCmd(flags))
	cmd.AddCommand(newThreatsExploreCmd(flags))
	cmd.AddCommand(newThreatsNotesCmd(flags))
	cmd.AddCommand(newThreatsTimelineCmd(flags))
	cmd.AddCommand(newThreatsWhiteningOptionsCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelThreatsBlastRadiusCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelThreatsMttrCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelThreatsRecurrenceCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelThreatsTriageCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelThreatsVerdictsCmd(flags))
	return cmd
}
