// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"net/url"
	"os"
	"strconv"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"huntress-pp-cli/internal/cli"
	"huntress-pp-cli/internal/client"
	"huntress-pp-cli/internal/cliutil"
	"huntress-pp-cli/internal/config"
	"huntress-pp-cli/internal/learn"
	"huntress-pp-cli/internal/mcp/bound"
	"huntress-pp-cli/internal/mcp/cobratree"
	"huntress-pp-cli/internal/platform"
	"huntress-pp-cli/internal/store"
	"modernc.org/sqlite"
	sqlite3 "modernc.org/sqlite/lib"
)

const (
	// MCP hosts can fan out tool calls faster than a human CLI session.
	// Keep them on the same polite-client limiter path instead of disabling
	// pacing with rate=0; users can still tune human CLI calls with --rate-limit.
	defaultMCPRateLimit = 2
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	installFreshTenantGate(s)
	// Code-orchestration mode — the full surface is covered by registry tools
	// (<api>_search, <api>_get, and <api>_execute). Endpoint-mirror tools are suppressed.
	RegisterCodeOrchestrationTools(s)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Synced records live in resources(resource_type, id, data); filter by resource_type and use json_extract on data, e.g. SELECT json_extract(data,'$.name') FROM resources WHERE resource_type='account'.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext(s),
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName   string
	WireName     string
	Location     string
	BodyPath     []string
	Format       string
	QueryArray   bool
	QueryStyle   string
	QueryExplode bool
	Default      string
}

type mcpPageConfig struct {
	CursorParam    string
	NextCursorPath string
}

func formatMCPParamValue(v any) string {
	switch tv := v.(type) {
	case string:
		return tv
	case bool:
		return strconv.FormatBool(tv)
	case float64:
		if math.IsNaN(tv) || math.IsInf(tv, 0) {
			return strconv.FormatFloat(tv, 'f', -1, 64)
		}
		if math.Trunc(tv) == tv && math.Abs(tv) < 1e15 {
			return strconv.FormatInt(int64(tv), 10)
		}
		return strconv.FormatFloat(tv, 'f', -1, 64)
	case float32:
		f := float64(tv)
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return strconv.FormatFloat(f, 'f', -1, 32)
		}
		if math.Trunc(f) == f && math.Abs(f) < 1e15 {
			return strconv.FormatInt(int64(f), 10)
		}
		return strconv.FormatFloat(f, 'f', -1, 32)
	default:
		// Composite values (a native []any / map[string]any from an array or
		// object param) reach this path when bound to a query or path slot;
		// JSON-encode them so the wire value is valid JSON rather than Go's
		// "[a b c]" / "map[...]" rendering. Body params never come through
		// here — they are stored natively in bodyArgs and marshalled there.
		if b, err := json.Marshal(v); err == nil {
			return string(b)
		}
		return fmt.Sprintf("%v", v)
	}
}

func mcpPathValue(v any) string {
	return cliutil.EscapePathParam(formatMCPParamValue(v))
}
func appendMCPArrayQueryParam(path, name string, value any, style string, explode bool) string {
	var values []string
	switch typed := value.(type) {
	case []any:
		values = make([]string, 0, len(typed))
		for _, item := range typed {
			values = append(values, formatMCPParamValue(item))
		}
	case []string:
		values = typed
	default:
		raw := formatMCPParamValue(value)
		var decoded []any
		if json.Unmarshal([]byte(raw), &decoded) == nil {
			for _, item := range decoded {
				values = append(values, formatMCPParamValue(item))
			}
		} else {
			for _, item := range strings.Split(raw, ",") {
				if item = strings.TrimSpace(item); item != "" {
					values = append(values, item)
				}
			}
		}
	}
	if len(values) == 0 {
		return path
	}

	query := url.Values{}
	switch style {
	case "spaceDelimited":
		query.Set(name, strings.Join(values, " "))
	case "pipeDelimited":
		query.Set(name, strings.Join(values, "|"))
	case "form":
		if explode {
			for _, item := range values {
				query.Add(name, item)
			}
		} else {
			query.Set(name, strings.Join(values, ","))
		}
	default:
		query.Set(name, formatMCPParamValue(value))
	}

	separator := "?"
	if strings.Contains(path, "?") {
		separator = "&"
	}
	return path + separator + query.Encode()
}
func setNestedBodyArg(body map[string]any, path []string, value any) {
	if len(path) == 0 {
		return
	}
	if len(path) == 1 {
		body[path[0]] = value
		return
	}
	current := body
	for _, key := range path[:len(path)-1] {
		next, ok := current[key].(map[string]any)
		if !ok {
			next = map[string]any{}
			current[key] = next
		}
		current = next
	}
	current[path[len(path)-1]] = value
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, pageConfig mcpPageConfig, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, platformSession, err := newMCPClient(ctx)
		if err != nil {
			return mcpToolError(err.Error()), nil
		}
		if platformSession != nil {
			defer platformSession.ZeroCredentials()
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()
		if err := cli.AdoptMCPOutputSemantics(platformSession, args); err != nil {
			return mcpToolError(err.Error()), nil
		}

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		mcpCursor := ""
		if pageConfig.CursorParam != "" {
			knownArgs["cursor"] = true
			if v, ok := args["cursor"]; ok {
				s, ok := v.(string)
				if !ok {
					return mcpToolError("cursor must be an opaque string returned by a previous MCP response"), nil
				}
				mcpCursor = s
				upstreamCursor, err := bound.UpstreamCursor(s)
				if err != nil {
					return mcpToolError(err.Error()), nil
				}
				if upstreamCursor != "" {
					params[pageConfig.CursorParam] = upstreamCursor
				}
			}
		}
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				if binding.Default != "" {
					v = binding.Default
				} else {
					continue
				}
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, mcpPathValue(v), 1)
			case "header":
				if headers == nil {
					headers = map[string]string{}
				}
				headers[binding.WireName] = formatMCPParamValue(v)
			case "body":
				if len(binding.BodyPath) > 0 {
					setNestedBodyArg(bodyArgs, binding.BodyPath, v)
				} else {
					bodyArgs[binding.WireName] = v
				}
			default:
				if binding.QueryArray {
					path = appendMCPArrayQueryParam(path, binding.WireName, v, binding.QueryStyle, binding.QueryExplode)
				} else {
					params[binding.WireName] = formatMCPParamValue(v)
				}
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, mcpPathValue(v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = formatMCPParamValue(v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				if readOnly {
					data, err = c.GetWithHeaders(ctx, path, params, headers)
				} else {
					data, err = c.GetMutatingWithHeaders(ctx, path, params, headers)
				}
				break
			}
			if readOnly {
				data, err = c.Get(ctx, path, params)
			} else {
				data, err = c.GetMutating(ctx, path, params)
			}
		case "POST":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PutQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PutQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
			}
		case "PATCH":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PatchQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PatchQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
			}
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcpToolError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcpToolTextWithPlatform("already exists (no-op)", platformSession), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcpToolError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set Basic credentials with: export HUNTRESS_API_KEY=\"your-token-here\" HUNTRESS_API_SECRET=\"your-token-here\"" +
					"\n      Get a key at: https://www.huntress.com/terms-of-service" +
					"\n      Run 'huntress-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcpToolError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your Basic credentials." +
					"\n      Set Basic credentials with: export HUNTRESS_API_KEY=\"your-token-here\" HUNTRESS_API_SECRET=\"your-token-here\"" +
					"\n      Get a key at: https://www.huntress.com/terms-of-service" +
					"\n      Run 'huntress-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcpToolError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource. Check that they have the required permissions and match the API's expected auth scheme." +
					"\n      Set Basic credentials with: export HUNTRESS_API_KEY=\"your-token-here\" HUNTRESS_API_SECRET=\"your-token-here\"" +
					"\n      Get a key at: https://www.huntress.com/terms-of-service" +
					"\n      Run 'huntress-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcpToolTextWithPlatform("already deleted (no-op)", platformSession), nil
				}
				return mcpToolError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcpToolError("rate limited: " + msg), nil
			default:
				return mcpToolError(msg), nil
			}
		}

		if binaryResponse {
			encoded := base64.StdEncoding.EncodeToString(data)
			out, err := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      encoded,
				"byte_count":       len(data),
			})
			if err != nil {
				return mcpToolError(fmt.Sprintf("encoding binary result: %v", err)), nil
			}
			if len(out) > bound.MaxBytes {
				return mcpToolError(fmt.Sprintf("binary response is too large for MCP text output: %d response bytes encode to %d base64 bytes and %d MCP result bytes, exceeding the %d byte budget. Use the companion CLI command with --output <file> to save the payload locally.", len(data), len(encoded), len(out), bound.MaxBytes)), nil
			}
			result := string(out)
			if platformSession != nil {
				result = bound.WithMetadata(result, platformSession.OutputMetadata())
			}
			return mcplib.NewToolResultText(result), nil
		}
		if pageConfig.CursorParam != "" {
			return mcpToolPageResultTextWithPlatform(method, data, pageConfig, mcpCursor, platformSession), nil
		}
		return mcpToolResultTextWithPlatform(method, data, platformSession), nil
	}
}

func mcpToolResultText(method string, data json.RawMessage) *mcplib.CallToolResult {
	return mcpToolResultTextWithPlatform(method, data, nil)
}

func mcpToolTextWithPlatform(result string, platformSession *platform.Session) *mcplib.CallToolResult {
	if platformSession != nil {
		result = bound.WithMetadata(result, platformSession.OutputMetadata())
	}
	return mcplib.NewToolResultText(result)
}

func mcpToolResultTextWithPlatform(method string, data json.RawMessage, platformSession *platform.Session) *mcplib.CallToolResult {
	result := bound.EndpointResponse(method, data)
	return mcpToolTextWithPlatform(result, platformSession)
}

// mcpToolError keeps provider-controlled typed endpoint errors within the MCP
// text-result budget just like successful endpoint results.
func mcpToolError(message string) *mcplib.CallToolResult {
	return mcplib.NewToolResultError(bound.Text(message))
}

func mcpToolPageResultText(method string, data json.RawMessage, pageConfig mcpPageConfig, cursor string) *mcplib.CallToolResult {
	return mcpToolPageResultTextWithPlatform(method, data, pageConfig, cursor, nil)
}

func mcpToolPageResultTextWithPlatform(method string, data json.RawMessage, pageConfig mcpPageConfig, cursor string, platformSession *platform.Session) *mcplib.CallToolResult {
	result := bound.EndpointPageResponse(method, data, bound.PageOptions{
		Cursor:         cursor,
		CursorParam:    pageConfig.CursorParam,
		NextCursorPath: pageConfig.NextCursorPath,
	})
	if platformSession != nil {
		result = bound.WithMetadata(result, platformSession.OutputMetadata())
	}
	return mcplib.NewToolResultText(result)
}

func newMCPClient(ctx context.Context) (*client.Client, *platform.Session, error) {
	cfg, err := newMCPConfig()
	if err != nil {
		return nil, nil, err
	}
	return newMCPClientFromConfig(ctx, cfg)
}

func newMCPConfig() (*config.Config, error) {
	cfg, err := config.Load("")
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	return cfg, nil
}

func newMCPClientFromConfig(ctx context.Context, cfg *config.Config) (*client.Client, *platform.Session, error) {
	c := client.New(cfg, 60*time.Second, defaultMCPRateLimit)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	session, err := cli.BindMCPClient(ctx, c)
	if err != nil {
		return nil, nil, err
	}
	if err := cli.ApplyClientHooks(c); err != nil {
		if session != nil {
			session.ZeroCredentials()
		}
		return nil, nil, fmt.Errorf("initializing MCP client: %w", err)
	}
	return c, session, nil
}

func mcpDBPath() (string, error) {
	// Resolve through the CLI so search/sql read the store `sync` wrote
	// (credential-scoped data-<hash>.db on a fresh install). See
	// handfixes.json "mcp-store-path-matches-cli".
	return cli.MCPStorePath()
}

type mcpStoreStatusKind string

const (
	mcpStoreStatusEmpty   mcpStoreStatusKind = "empty"
	mcpStoreStatusPartial mcpStoreStatusKind = "partial"
	mcpStoreStatusReady   mcpStoreStatusKind = "ready"
)

func openMCPReadOnlyStore(path string) (*store.Store, *mcplib.CallToolResult) {
	if _, err := os.Stat(path); err != nil {
		if os.IsNotExist(err) {
			return nil, mcplib.NewToolResultError(mcpMissingStoreMessage(path))
		}
		return nil, mcplib.NewToolResultError(fmt.Sprintf("checking local data store %s: %v", path, err))
	}
	db, err := store.OpenReadOnly(path)
	if err != nil {
		return nil, mcplib.NewToolResultError(fmt.Sprintf("opening local data store %s: %v. Run huntress-cli sync to refresh the store, or use live endpoint MCP tools for unsynced data.", path, err))
	}
	return db, nil
}

func mcpMissingStoreMessage(path string) string {
	return fmt.Sprintf("No local data store found at %s. Run huntress-cli sync before using MCP search/sql, or use live endpoint MCP tools for unsynced data.", path)
}

func mcpStoreStatus(db *store.Store) (mcpStoreStatusKind, error) {
	status, err := db.Status()
	if err != nil {
		return "", err
	}
	var checkpoints, completed int
	err = db.DB().QueryRow(`SELECT COUNT(*), COALESCE(SUM(CASE WHEN last_attempt_complete = 1 THEN 1 ELSE 0 END), 0) FROM sync_state`).Scan(&checkpoints, &completed)
	if err != nil && strings.Contains(strings.ToLower(err.Error()), "no such column: last_attempt_complete") {
		// Read-only stores have not run the conservative completion migration.
		// Legacy timestamps were also written by partial walks, so prove nothing.
		err = db.DB().QueryRow(`SELECT COUNT(*), 0 FROM sync_state`).Scan(&checkpoints, &completed)
	}
	if err != nil {
		msg := strings.ToLower(err.Error())
		if strings.Contains(msg, "no such table") || strings.Contains(msg, "no such column") {
			if len(status) > 0 {
				return mcpStoreStatusReady, nil
			}
			return mcpStoreStatusEmpty, nil
		}
		return "", err
	}
	if checkpoints > 0 {
		if completed == checkpoints {
			return mcpStoreStatusReady, nil
		}
		return mcpStoreStatusPartial, nil
	}
	if len(status) > 0 {
		return mcpStoreStatusReady, nil
	}
	return mcpStoreStatusEmpty, nil
}

func mcpEmptyStoreNextStep() string {
	return "Run huntress-cli sync to populate the local SQLite store before using MCP search/sql."
}

func mcpPartialStoreNextStep() string {
	return "The latest sync attempt is incomplete. Resume or rerun huntress-cli sync before treating local search/sql results as a complete snapshot."
}

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	path, err := mcpDBPath()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("resolving database: %v", err)), nil
	}
	db, toolErr := openMCPReadOnlyStore(path)
	if toolErr != nil {
		return toolErr, nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}
	storeStatus, err := mcpStoreStatus(db)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading store status: %v", err)), nil
	}

	return toolResultJSON(mcpSearchEnvelope(results, storeStatus))
}

func mcpSearchEnvelope(results []json.RawMessage, storeStatus mcpStoreStatusKind) map[string]any {
	if results == nil {
		results = []json.RawMessage{}
	}
	out := map[string]any{
		"count":        len(results),
		"results":      results,
		"store_status": storeStatus,
		"resumable":    false,
	}
	if storeStatus == mcpStoreStatusPartial {
		out["warning"] = "Local data may be incomplete because the latest sync attempt did not finish."
		out["next_step"] = mcpPartialStoreNextStep()
	} else if len(results) == 0 {
		if storeStatus == mcpStoreStatusEmpty {
			out["next_step"] = mcpEmptyStoreNextStep()
		} else {
			out["next_step"] = "No local search matches. Try a broader query, a lower-specificity FTS expression, or sync again if data may be stale."
		}
	}
	return out
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate rejects multi-statement input, then applies an allowlist (SELECT or
// WITH only) AFTER stripping the leading whitespace, line comments, block
// comments, and semicolons that SQLite itself ignores before parsing. A naive
// HasPrefix check on a keyword blocklist is bypassable by prefixing the
// dangerous statement with "/* x */" or "-- x\n"; a naive leading-keyword
// allowlist is bypassable by appending "; ATTACH DATABASE ...". Combined with
// the empirical fact that modernc.org/sqlite's mode=ro does NOT block VACUUM
// INTO (writes a snapshot to a new file) or ATTACH DATABASE (opens a separate
// writable handle), either bypass produces silent exfiltration to an
// attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	stripped := stripLeadingSQLNoise(query)
	if hasTrailingSQLStatement(stripped) {
		return fmt.Errorf("only a single SELECT or WITH statement is allowed")
	}
	upper := strings.ToUpper(stripped)
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

// hasTrailingSQLStatement reports whether query contains a statement
// terminator followed by more executable SQL. A trailing semicolon is allowed;
// a second statement is not. Semicolons inside string literals, quoted
// identifiers, bracket identifiers, and comments are ignored to match SQLite's
// parser shape closely enough for this security gate.
func hasTrailingSQLStatement(query string) bool {
	inSingle := false
	inDouble := false
	inBacktick := false
	inBracket := false
	inLineComment := false
	inBlockComment := false

	for i := 0; i < len(query); i++ {
		ch := query[i]
		next := byte(0)
		if i+1 < len(query) {
			next = query[i+1]
		}

		switch {
		case inLineComment:
			if ch == '\n' {
				inLineComment = false
			}
			continue
		case inBlockComment:
			if ch == '*' && next == '/' {
				inBlockComment = false
				i++
			}
			continue
		case inSingle:
			if ch == '\'' {
				if next == '\'' {
					i++
					continue
				}
				inSingle = false
			}
			continue
		case inDouble:
			if ch == '"' {
				if next == '"' {
					i++
					continue
				}
				inDouble = false
			}
			continue
		case inBacktick:
			if ch == '`' {
				if next == '`' {
					i++
					continue
				}
				inBacktick = false
			}
			continue
		case inBracket:
			if ch == ']' {
				inBracket = false
			}
			continue
		}

		switch {
		case ch == '-' && next == '-':
			inLineComment = true
			i++
		case ch == '/' && next == '*':
			inBlockComment = true
			i++
		case ch == '\'':
			inSingle = true
		case ch == '"':
			inDouble = true
		case ch == '`':
			inBacktick = true
		case ch == '[':
			inBracket = true
		case ch == ';':
			if stripLeadingSQLNoise(query[i+1:]) != "" {
				return true
			}
			return false
		}
	}
	return false
}

const mcpSQLMaxValueBytes = 4 << 20

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	path, err := mcpDBPath()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("resolving database: %v", err)), nil
	}
	db, toolErr := openMCPReadOnlyStore(path)
	if toolErr != nil {
		return toolErr, nil
	}
	defer db.Close()

	queryCtx, cancel := bound.WithSQLQueryDeadline(ctx)
	defer cancel()

	conn, err := db.DB().Conn(queryCtx)
	if err != nil {
		return mcplib.NewToolResultError(mcpSQLQueryError(queryCtx, err)), nil
	}
	defer conn.Close()

	if _, err := sqlite.Limit(conn, sqlite3.SQLITE_LIMIT_LENGTH, mcpSQLMaxValueBytes); err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("setting SQL value length cap: %v", err)), nil
	}

	rows, err := conn.QueryContext(queryCtx, query)
	if err != nil {
		return mcplib.NewToolResultError(mcpSQLQueryError(queryCtx, err)), nil
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading columns: %v", err)), nil
	}
	scan := bound.NewSQLScanState(cols)
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			if mcpSQLValueTooBig(err) {
				return mcplib.NewToolResultError(mcpSQLQueryError(queryCtx, err)), nil
			}
			return mcplib.NewToolResultError(fmt.Sprintf("scanning row: %v", err)), nil
		}
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		if !scan.Add(row) {
			break
		}
	}
	// rows.Next() stops on a mid-iteration error without failing the loop, so
	// skipping rows.Err() would return a truncated result set as success.
	if err := rows.Err(); err != nil {
		return mcplib.NewToolResultError(mcpSQLQueryError(queryCtx, err)), nil
	}
	storeStatus, err := mcpStoreStatus(db)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading store status: %v", err)), nil
	}

	return toolResultJSON(mcpSQLEnvelope(scan.Rows, cols, storeStatus, scan.Truncated))
}

func mcpSQLEnvelope(rows []map[string]any, columns []string, storeStatus mcpStoreStatusKind, truncated bool) map[string]any {
	if rows == nil {
		rows = []map[string]any{}
	}
	out := map[string]any{
		"count":        len(rows),
		"columns":      columns,
		"rows":         rows,
		"store_status": storeStatus,
		"resumable":    false,
		"truncated":    truncated,
	}
	if truncated {
		out["returned_count"] = len(rows)
		out["max_bytes"] = bound.MaxBytes
		out["note"] = bound.SQLResultBoundNote
	}
	if storeStatus == mcpStoreStatusPartial {
		out["warning"] = "Local data may be incomplete because the latest sync attempt did not finish."
		out["next_step"] = mcpPartialStoreNextStep()
	} else if len(rows) == 0 && !truncated {
		if storeStatus == mcpStoreStatusEmpty {
			out["next_step"] = mcpEmptyStoreNextStep()
		} else {
			out["next_step"] = "The read-only SQL query returned no rows. Check resource_type filters, json_extract paths, or run sync again if data may be stale."
		}
	}
	return out
}

func mcpSQLQueryError(queryCtx context.Context, err error) string {
	if queryCtx.Err() != nil {
		return fmt.Sprintf("query cancelled: %v. MCP SQL queries are bounded to %s; narrow the query with WHERE, GROUP BY, or an aggregate.", err, bound.SQLQueryTimeout)
	}
	if mcpSQLValueTooBig(err) {
		return fmt.Sprintf("query failed: a string or blob exceeds the MCP SQL value cap of %d bytes (4 MiB). Narrow the selected columns or use substr, json_extract, or length instead of returning oversized values.", mcpSQLMaxValueBytes)
	}
	msg := err.Error()
	if strings.Contains(strings.ToLower(msg), "no such table") {
		return fmt.Sprintf("query failed: %v. Synced records live in resources(resource_type, id, data), not one SQL table per resource. Filter by resource_type, for example resource_type='account', and read JSON fields with json_extract(data,'$.field').", err)
	}
	return fmt.Sprintf("query failed: %v", err)
}

func mcpSQLValueTooBig(err error) bool {
	var sqliteErr *sqlite.Error
	return errors.As(err, &sqliteErr) && sqliteErr.Code() == sqlite3.SQLITE_TOOBIG
}

// toolResultJSON renders v as the indented JSON body of an MCP text result,
// surfacing a marshal failure as a tool error instead of empty content.
func toolResultJSON(v any) (*mcplib.CallToolResult, error) {
	text, err := bound.JSON(v)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding result: %v", err)), nil
	}
	return mcplib.NewToolResultText(text), nil
}
func registeredCommandMirrorCapabilities(s *server.MCPServer, capabilities []map[string]string) []map[string]string {
	registered := make([]map[string]string, 0, len(capabilities))
	root := cli.RootCmd()
	for _, capability := range capabilities {
		toolName := cobratree.ToolNameForCommand(s, root, capability["cli_command"])
		if toolName == "" {
			continue
		}
		entry := s.GetTool(toolName)
		if entry == nil || entry.Tool.Meta == nil || entry.Tool.Meta.AdditionalFields["pp:tenant-gate"] != "child-cli" {
			continue
		}
		capability["mcp_tool"] = toolName
		registered = append(registered, capability)
	}
	return registered
}

func handleContext(s *server.MCPServer) func(context.Context, mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		return handleContextResult(s, ctx, req)
	}
}

func handleContextResult(s *server.MCPServer, _ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	paths := map[string]string{}
	if dir, err := cliutil.ConfigDir(); err == nil {
		paths["config_dir"] = dir
	}
	if dir, err := cliutil.DataDir(); err == nil {
		paths["data_dir"] = dir
	}
	if dir, err := cliutil.StateDir(); err == nil {
		paths["state_dir"] = dir
	}
	if dir, err := cliutil.CacheDir(); err == nil {
		paths["cache_dir"] = dir
	}
	ctx := map[string]any{
		"api":         "huntress",
		"description": "Every Huntress endpoint, plus fleet-wide incident, coverage, and billing rollups the API can't.",
		"archetype":   "crm",
		"tool_count":  len(s.ListTools()),
		"paths":       paths,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion huntress-cli binary.",
		// learn_protocol is generated from the single shared source of
		// truth (the exported constant internal/learn.RecallFirstProtocol)
		// also consumed by the CLI agent-context command, so the MCP and
		// CLI agent surfaces cannot drift.
		"learn_protocol": learn.RecallFirstProtocol,
		"auth": map[string]any{
			"type": "api_key",
			"env_vars": []map[string]any{
				{
					"name":      "HUNTRESS_API_KEY",
					"kind":      "per_call",
					"required":  true,
					"sensitive": false,
				},
				{
					"name":        "HUNTRESS_API_SECRET",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
			"key_url": "https://www.huntress.com/terms-of-service",
		},
		"resources": []map[string]any{
			{
				"name":        "account",
				"description": "Operations about Accounts",
				"endpoints":   []string{"get-v1"},
			},
			{
				"name":        "accounts",
				"description": "Operations about Accounts",
				"endpoints":   []string{"creation-parameters", "delete-v1-id", "get-v1", "get-v1-id", "update-parameters"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "accounts.agents",
				"description": "Operations about Agents",
				"endpoints":   []string{"get-v1-accounts-account-id", "get-v1-accounts-account-id-id"},
			},
			{
				"name":        "accounts.external-ports",
				"description": "Manage external ports",
				"endpoints":   []string{"get-v1-accounts-account-id", "get-v1-accounts-account-id-id"},
			},
			{
				"name":        "accounts.incident-reports",
				"description": "Operations about Incident Reports",
				"endpoints":   []string{"get-v1-accounts-account-id", "get-v1-accounts-account-id-id", "get-v1-accounts-account-id-id-remediations", "get-v1-accounts-account-id-id-remediations-remediation-id", "post-v1-accounts-account-id-id-remediations-bulk-approval", "post-v1-accounts-account-id-id-resolution", "remediation-bulk-rejection-parameters"},
				"writable":    true,
			},
			{
				"name":        "accounts.invoices",
				"description": "Operations about Invoices",
				"endpoints":   []string{"get-v1-accounts-account-id", "get-v1-accounts-account-id-id"},
			},
			{
				"name":        "accounts.memberships",
				"description": "Manage memberships",
				"endpoints":   []string{"creation-parameters", "delete-v1-accounts-account-id-id", "get-v1-accounts-account-id", "get-v1-accounts-account-id-id", "update-parameters"},
				"writable":    true,
			},
			{
				"name":        "accounts.organizations",
				"description": "Operations about Organizations",
				"endpoints":   []string{"creation-parameters", "delete-v1-accounts-account-id-id", "get-v1-accounts-account-id", "get-v1-accounts-account-id-id", "update-parameters"},
				"writable":    true,
			},
			{
				"name":        "accounts.reports",
				"description": "Manage reports",
				"endpoints":   []string{"get-v1-accounts-account-id", "get-v1-accounts-account-id-id"},
			},
			{
				"name":        "accounts.signals",
				"description": "Operations about Signals",
				"endpoints":   []string{"get-v1-accounts-account-id", "get-v1-accounts-account-id-id"},
			},
			{
				"name":        "actor",
				"description": "Operations about Actors",
				"endpoints":   []string{"get-v1"},
			},
			{
				"name":        "agents",
				"description": "Operations about Agents",
				"endpoints":   []string{"get-v1", "get-v1-id"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "escalations",
				"description": "Operations about Escalations",
				"endpoints":   []string{"get-v1", "get-v1-id"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "escalations.resolution",
				"description": "Manage resolution",
				"endpoints":   []string{"escalation-parameters"},
				"writable":    true,
			},
			{
				"name":        "external-ports",
				"description": "Manage external ports",
				"endpoints":   []string{"get-v1", "get-v1-id"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "identities",
				"description": "Operations about Identities",
				"endpoints":   []string{"get-v1", "get-v1-id"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "incident-reports",
				"description": "Operations about Incident Reports",
				"endpoints":   []string{"get-v1", "get-v1-id"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "incident-reports.remediations",
				"description": "Manage remediations",
				"endpoints":   []string{"bulk-rejection-parameters", "get-v1-incident-reports-incident-report-id", "get-v1-incident-reports-incident-report-id-id", "post-v1-incident-reports-incident-report-id-bulk-approval"},
				"writable":    true,
			},
			{
				"name":        "incident-reports.resolution",
				"description": "Manage resolution",
				"endpoints":   []string{"post-v1-incident-reports-id"},
				"writable":    true,
			},
			{
				"name":        "invoices",
				"description": "Operations about Invoices",
				"endpoints":   []string{"get-v1", "get-v1-id"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "known-vpns",
				"description": "Operations about Known VPNs",
				"endpoints":   []string{"get-v1"},
				"syncable":    true,
			},
			{
				"name":        "memberships",
				"description": "Manage memberships",
				"endpoints":   []string{"creation-parameters", "delete-v1-id", "get-v1", "get-v1-id", "update-parameters"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "organizations",
				"description": "Operations about Organizations",
				"endpoints":   []string{"creation-parameters", "delete-v1-id", "get-v1", "get-v1-id", "update-parameters"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "reports",
				"description": "Manage reports",
				"endpoints":   []string{"get-v1", "get-v1-id"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "reseller",
				"description": "Operations for Reseller-level API credentials. These are mostly the same endpoints available in the rest of the API.",
				"endpoints":   []string{"get-v1-invoices", "get-v1-invoices-id", "get-v1-invoices-id-account-usage-line-items", "get-v1-invoices-id-organization-usage-line-items", "get-v1-subscriptions", "get-v1-subscriptions-id", "subscription-creation-parameters", "subscription-update-parameters", "subscription-upgrade-parameters"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "siem",
				"description": "Query your SIEM logs programmatically using ES|QL (Elasticsearch Query Language) .",
				"endpoints":   []string{"post-v1-query"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "signals",
				"description": "Operations about Signals",
				"endpoints":   []string{"get-v1", "get-v1-id"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "unwanted-access-rules",
				"description": "Operations about Unwanted Access Rules",
				"endpoints":   []string{"creation-parameters", "delete-v1-id", "get-v1", "get-v1-id", "update-parameters"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass page_token parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": registeredCommandMirrorCapabilities(s, []map[string]string{
			{"name": "fleet-incidents", "command": "fleet-incidents", "cli_command": "fleet-incidents", "description": "One unified, age-sorted incident queue across every client organization", "rationale": "The API returns incidents per-org and paginated; we fan out across all orgs, join organization names", "via": "mcp-command-mirror"},
			{"name": "coverage-gaps", "command": "coverage-gaps", "cli_command": "coverage-gaps", "description": "Flags orgs and agents with stale callbacks, unhealthy Defender/firewall", "rationale": "Requires joining agent health fields across all orgs and computing per-org rollups and thresholds locally", "via": "mcp-command-mirror"},
			{"name": "blast-radius", "command": "blast-radius", "cli_command": "blast-radius", "description": "Given an indicator (external IP, file hash, or foothold signature), finds every agent, org", "rationale": "Cross-entity join across incident_reports, agents, and external_ports in the local store", "via": "mcp-command-mirror"},
			{"name": "triage-age", "command": "triage-age", "cli_command": "triage-age", "description": "SLA aging report: open incidents bucketed by hours-open, broken out by org and severity, with breaches flagged.", "rationale": "Time-buckets all open incidents across every org in one pass; the API has no SLA or aging concept.", "via": "mcp-command-mirror"},
			{"name": "billing-reconcile", "command": "billing-reconcile", "cli_command": "billing-reconcile", "description": "Compares invoiced and subscribed seat counts against actually deployed agent counts per org and surfaces the delta.", "rationale": "Joins invoices and subscriptions against a live per-org agent count — two endpoints the API never correlates.", "via": "mcp-command-mirror"},
			{"name": "drift", "command": "drift", "cli_command": "drift", "description": "Diffs the current sync against the prior snapshot: new and removed agents, status flips, new criticals", "rationale": "A pure historical-snapshot feature requiring two sync states; the live API is point-in-time only.", "via": "mcp-command-mirror"},
			{"name": "mttr", "command": "mttr", "cli_command": "mttr", "description": "Computes mean time-to-resolve for incidents from sent-to-resolved timestamps, grouped by org or severity.", "rationale": "Requires resolution-time history captured across syncs plus aggregation", "via": "mcp-command-mirror"},
			{"name": "canary-watch", "command": "canary-watch", "cli_command": "canary-watch", "description": "Surfaces only ransomware-canary and foothold incidents in a time window — the highest-signal early-ransomware indicators", "rationale": "Filtered cross-org fan-out plus a local time-window join; a curated high-signal view the API can't assemble in one call.", "via": "mcp-command-mirror"},
			{"name": "org-scorecard", "command": "org-scorecard", "cli_command": "org-scorecard", "description": "Per-client QBR scorecard: agent count, coverage percent, open and closed incidents, MTTR", "rationale": "Joins agents and incidents (plus history for MTTR and trend)", "via": "mcp-command-mirror"},
			{"name": "stale-agents", "command": "stale-agents", "cli_command": "stale-agents", "description": "Lists agents whose last callback exceeds a threshold — decommissioned-but-billed machines or broken installs.", "rationale": "Local threshold filter and cross-org sort on last_callback_at; the API has no 'last seen older than' query.", "via": "mcp-command-mirror"},
			{"name": "handoff", "command": "handoff", "cli_command": "handoff", "description": "Shift-change report of what changed (new criticals, resolutions, escalations) since a timestamp", "rationale": "Snapshot diff plus multi-entity time-window aggregation; only possible with stored history.", "via": "mcp-command-mirror"},
			{"name": "incident-detail", "command": "incident-detail", "cli_command": "incident-detail", "description": "See one incident fully enriched — its remediations, the affected agent, and the org name — in a single lookup.", "rationale": "Joins incident_reports, remediations, agents, and organizations locally; the API returns these across 3+ separate calls.", "via": "mcp-command-mirror"},
			{"name": "fleet-summary", "command": "fleet-summary", "cli_command": "fleet-summary", "description": "One-screen fleet top-line: total orgs, agents, open criticals, oldest unactioned critical, orgs below coverage threshold", "rationale": "Single SQLite aggregation across organizations + agents + incident_reports; the API has no fleet-wide rollup at all.", "via": "mcp-command-mirror"},
			{"name": "reseller-rollup", "command": "reseller-rollup", "cli_command": "reseller-rollup", "description": "Per-account roll-up for resellers: invoice total, subscribed seats, and deployed agent count side by side.", "rationale": "Joins account-scoped reseller invoices, subscriptions, and agent counts across the /v1/accounts/{id} axis", "via": "mcp-command-mirror"},
		}),
		"playbook": []map[string]string{
			{"topic": "fleet-incidents", "insight": "The API returns incidents per-org and paginated; we fan out across all orgs, join organization names, and sort globally by age in the local store."},
			{"topic": "coverage-gaps", "insight": "Requires joining agent health fields across all orgs and computing per-org rollups and thresholds locally; the API has no posture aggregation."},
			{"topic": "blast-radius", "insight": "Cross-entity join across incident_reports, agents, and external_ports in the local store; the API exposes no cross-incident search."},
			{"topic": "triage-age", "insight": "Time-buckets all open incidents across every org in one pass; the API has no SLA or aging concept."},
			{"topic": "billing-reconcile", "insight": "Joins invoices and subscriptions against a live per-org agent count — two endpoints the API never correlates."},
			{"topic": "drift", "insight": "A pure historical-snapshot feature requiring two sync states; the live API is point-in-time only."},
			{"topic": "mttr", "insight": "Requires resolution-time history captured across syncs plus aggregation; the API exposes timestamps but never the metric."},
			{"topic": "canary-watch", "insight": "Filtered cross-org fan-out plus a local time-window join; a curated high-signal view the API can't assemble in one call."},
			{"topic": "org-scorecard", "insight": "Joins agents and incidents (plus history for MTTR and trend) for one org into a single rollup the API returns nowhere pre-aggregated."},
			{"topic": "stale-agents", "insight": "Local threshold filter and cross-org sort on last_callback_at; the API has no 'last seen older than' query."},
			{"topic": "handoff", "insight": "Snapshot diff plus multi-entity time-window aggregation; only possible with stored history."},
			{"topic": "incident-detail", "insight": "Joins incident_reports, remediations, agents, and organizations locally; the API returns these across 3+ separate calls."},
			{"topic": "fleet-summary", "insight": "Single SQLite aggregation across organizations + agents + incident_reports; the API has no fleet-wide rollup at all."},
			{"topic": "reseller-rollup", "insight": "Joins account-scoped reseller invoices, subscriptions, and agent counts across the /v1/accounts/{id} axis; the API never correlates them."},
			{"topic": "Contact lookup", "insight": "Use search for finding contacts by name/email. List endpoints return unsorted results and require pagination for large datasets."},
			{"topic": "Activity tracking", "insight": "When checking deal activity, sync first and query locally. CRM APIs often throttle activity-log endpoints heavily."},
		},
	}
	return toolResultJSON(ctx)
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
