// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newAccountsUpdateParametersCmd(flags *rootFlags) *cobra.Command {
	var bodyBillingAddressCity string
	var bodyBillingAddressCountry string
	var bodyBillingAddressLine1 string
	var bodyBillingAddressLine2 string
	var bodyBillingAddressPostalCode string
	var bodyBillingAddressState string
	var bodyName string
	var bodyPhoneNumber string
	var bodyShippingAddressCity string
	var bodyShippingAddressCountry string
	var bodyShippingAddressLine1 string
	var bodyShippingAddressLine2 string
	var bodyShippingAddressPostalCode string
	var bodyShippingAddressState string
	var bodySubdomain string
	var bodySupportType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "update-parameters <account_id>",
		Aliases:     []string{"update"},
		Short:       "Updates the details of a specific account.",
		Annotations: map[string]string{"pp:endpoint": "accounts.update-parameters", "pp:method": "PATCH", "pp:path": "/v1/accounts/{account_id}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <account_id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <account_id>"))
			}
			if !stdinBody {
			}
			path := "/v1/accounts/{account_id}"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("account_id is required\nUsage: %s <%s>", cmd.CommandPath(), "account_id"))
			}
			path = replacePathParam(path, "account_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				{
					nestedBillingAddress := map[string]any{}
					if cmd.Flags().Changed("billing-address-city") || bodyBillingAddressCity != "" {
						nestedBillingAddress["city"] = bodyBillingAddressCity
					}
					if cmd.Flags().Changed("billing-address-country") || bodyBillingAddressCountry != "" {
						nestedBillingAddress["country"] = bodyBillingAddressCountry
					}
					if cmd.Flags().Changed("billing-address-line1") || bodyBillingAddressLine1 != "" {
						nestedBillingAddress["line1"] = bodyBillingAddressLine1
					}
					if cmd.Flags().Changed("billing-address-line2") || bodyBillingAddressLine2 != "" {
						nestedBillingAddress["line2"] = bodyBillingAddressLine2
					}
					if cmd.Flags().Changed("billing-address-postal-code") || bodyBillingAddressPostalCode != "" {
						nestedBillingAddress["postal_code"] = bodyBillingAddressPostalCode
					}
					if cmd.Flags().Changed("billing-address-state") || bodyBillingAddressState != "" {
						nestedBillingAddress["state"] = bodyBillingAddressState
					}
					if len(nestedBillingAddress) > 0 {
						bodyMap["billing_address"] = nestedBillingAddress
					}
				}
				if cmd.Flags().Changed("name") || bodyName != "" {
					bodyMap["name"] = bodyName
				}
				if cmd.Flags().Changed("phone-number") || bodyPhoneNumber != "" {
					bodyMap["phone_number"] = bodyPhoneNumber
				}
				{
					nestedShippingAddress := map[string]any{}
					if cmd.Flags().Changed("shipping-address-city") || bodyShippingAddressCity != "" {
						nestedShippingAddress["city"] = bodyShippingAddressCity
					}
					if cmd.Flags().Changed("shipping-address-country") || bodyShippingAddressCountry != "" {
						nestedShippingAddress["country"] = bodyShippingAddressCountry
					}
					if cmd.Flags().Changed("shipping-address-line1") || bodyShippingAddressLine1 != "" {
						nestedShippingAddress["line1"] = bodyShippingAddressLine1
					}
					if cmd.Flags().Changed("shipping-address-line2") || bodyShippingAddressLine2 != "" {
						nestedShippingAddress["line2"] = bodyShippingAddressLine2
					}
					if cmd.Flags().Changed("shipping-address-postal-code") || bodyShippingAddressPostalCode != "" {
						nestedShippingAddress["postal_code"] = bodyShippingAddressPostalCode
					}
					if cmd.Flags().Changed("shipping-address-state") || bodyShippingAddressState != "" {
						nestedShippingAddress["state"] = bodyShippingAddressState
					}
					if len(nestedShippingAddress) > 0 {
						bodyMap["shipping_address"] = nestedShippingAddress
					}
				}
				if cmd.Flags().Changed("subdomain") || bodySubdomain != "" {
					bodyMap["subdomain"] = bodySubdomain
				}
				if cmd.Flags().Changed("support-type") || bodySupportType != "" {
					bodyMap["support_type"] = bodySupportType
				}
			}
			data, statusCode, err := c.PatchWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "accounts", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "accounts", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "accounts", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "accounts", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "accounts", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "patch",
					"resource": "accounts",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Mutation-riding reads (POST search, RPC-over-POST lists) return
				// the same single-key collection envelopes as GET reads. Unwrap
				// before filtering so rows nest once under the result key and
				// --select filters rows, not envelope keys; plain created-object
				// responses pass through unwrapSingleKeyArray untouched.
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				var selectErr error
				filtered := unwrapSingleKeyArray(data)
				if flags.selectFields != "" {
					filtered, selectErr = filterFieldsChecked(filtered, flags.selectFields)
					selectErr = selectErrorForDryRun(selectErr, flags, data)
				} else if flags.compact {
					filtered = compactFields(filtered, map[string]bool{"id": true, "name": true, "status": true})
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				resultKey := "data"
				if flags.agent {
					resultKey = "results"
				}
				structured, err := wrapPlatformStructuredOutput(json.RawMessage(envelopeJSON), flags, resultKey, true)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), structured, true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "accounts", partialFailure.Message))
				}
				return selectErr
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlagsMeta renders the body with live
			// provenance, then the typed partial-failure exit fires unless
			// --allow-partial-failure downgrades it. Without this guard a
			// partial failure would exit 0 for these output modes — the exact
			// silent-swallow regression the surrounding patch is preventing
			// for asJSON / piped output.
			printErr := printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"}, map[string]bool{"id": true, "name": true, "status": true})
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "accounts", partialFailure.Message))
			}
			return printErr
		},
	}
	cmd.Flags().StringVar(&bodyBillingAddressCity, "billing-address-city", "", "City")
	cmd.Flags().StringVar(&bodyBillingAddressCountry, "billing-address-country", "", "Two-letter ISO 3166-1 alpha-2 country code")
	cmd.Flags().StringVar(&bodyBillingAddressLine1, "billing-address-line1", "", "Street address line 1")
	cmd.Flags().StringVar(&bodyBillingAddressLine2, "billing-address-line2", "", "Street address line 2")
	cmd.Flags().StringVar(&bodyBillingAddressPostalCode, "billing-address-postal-code", "", "Postal or ZIP code (required for US and GB)")
	cmd.Flags().StringVar(&bodyBillingAddressState, "billing-address-state", "", "State or province (required for US and CA)")
	cmd.Flags().StringVar(&bodyName, "name", "", "Name of the account")
	cmd.Flags().StringVar(&bodyPhoneNumber, "phone-number", "", "Primary phone number used to contact account owner")
	cmd.Flags().StringVar(&bodyShippingAddressCity, "shipping-address-city", "", "City")
	cmd.Flags().StringVar(&bodyShippingAddressCountry, "shipping-address-country", "", "Two-letter ISO 3166-1 alpha-2 country code")
	cmd.Flags().StringVar(&bodyShippingAddressLine1, "shipping-address-line1", "", "Street address line 1")
	cmd.Flags().StringVar(&bodyShippingAddressLine2, "shipping-address-line2", "", "Street address line 2")
	cmd.Flags().StringVar(&bodyShippingAddressPostalCode, "shipping-address-postal-code", "", "Postal or ZIP code (required for US and GB)")
	cmd.Flags().StringVar(&bodyShippingAddressState, "shipping-address-state", "", "State or province (required for US and CA)")
	cmd.Flags().StringVar(&bodySubdomain, "subdomain", "", "Subdomain this account will use to access the Huntress portal")
	cmd.Flags().StringVar(&bodySupportType, "support-type", "", "Specifies whether a reseller account is managed by the partner or by Huntress.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
