// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMembershipsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "memberships",
		Short:       "Get, create, update, and delete memberships",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newMembershipsCreationParametersCmd(flags))
	cmd.AddCommand(newMembershipsDeleteV1IdCmd(flags))
	cmd.AddCommand(newMembershipsGetV1Cmd(flags))
	cmd.AddCommand(newMembershipsGetV1IdCmd(flags))
	cmd.AddCommand(newMembershipsUpdateParametersCmd(flags))
	return cmd
}
