// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newMembershipsGetV1Cmd(flags *rootFlags) *cobra.Command {
	var flagLimit int
	var flagPageToken string
	var flagSortField string
	var flagSortDirection string
	var flagOrganizationId string
	var flagUserId string
	var flagPermissions string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-v1",
		Aliases:     []string{"list"},
		Short:       "Shows a list of memberships.",
		Example:     "  huntress-cli memberships get-v1",
		Annotations: map[string]string{"pp:endpoint": "memberships.get-v1", "pp:method": "GET", "pp:path": "/v1/memberships", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("sort-field") {
				allowedSortField := []string{"id", "user_id", "created_at", "updated_at"}
				validSortField := false
				for _, v := range allowedSortField {
					if flagSortField == v {
						validSortField = true
						break
					}
				}
				if !validSortField {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagSortField, "sort-field", allowedSortField)
				}
			}
			if cmd.Flags().Changed("sort-direction") {
				allowedSortDirection := []string{"asc", "desc"}
				validSortDirection := false
				for _, v := range allowedSortDirection {
					if flagSortDirection == v {
						validSortDirection = true
						break
					}
				}
				if !validSortDirection {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagSortDirection, "sort-direction", allowedSortDirection)
				}
			}
			if cmd.Flags().Changed("permissions") {
				allowedPermissions := []string{"Admin", "Security Engineer", "User", "Read-only", "Finance", "Marketing", "Provisioner"}
				validPermissions := false
				for _, v := range allowedPermissions {
					if flagPermissions == v {
						validPermissions = true
						break
					}
				}
				if !validPermissions {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagPermissions, "permissions", allowedPermissions)
				}
			}
			path := "/v1/memberships"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "auto", "memberships", path, retainCLIQueryParams(cmd, map[string]string{
				"limit":           formatCLIParamValue(flagLimit),
				"page_token":      formatCLIParamValue(flagPageToken),
				"sort_field":      formatCLIParamValue(flagSortField),
				"sort_direction":  formatCLIParamValue(flagSortDirection),
				"organization_id": formatCLIParamValue(flagOrganizationId),
				"user_id":         formatCLIParamValue(flagUserId),
				"permissions":     formatCLIParamValue(flagPermissions),
			}, map[string][]string{"limit": {"limit"}, "page_token": {"page-token"}, "sort_field": {"sort-field"}, "sort_direction": {"sort-direction"}, "organization_id": {"organization-id"}, "user_id": {"user-id"}, "permissions": {"permissions"}}, "page_token", "page_token"), nil, flagAll, "page_token", "page_token", "limit", 10, "pagination.next_page_token", "", "memberships", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			outputData := collectionItemsForOutput(data, path)
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(outputData, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				var selectErr error
				filtered := data
				if flags.selectFields != "" {
					filtered, selectErr = filterFieldsChecked(filtered, flags.selectFields)
					selectErr = selectErrorForDryRun(selectErr, flags, data)
				} else if flags.compact {
					filtered = compactFields(filtered, map[string]bool{"created_at": true, "id": true, "updated_at": true})
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				wrapped, wrapErr = wrapPlatformStructuredOutput(wrapped, flags, "results", true)
				if wrapErr != nil {
					return wrapErr
				}
				if err := printOutput(cmd.OutOrStdout(), wrapped, true); err != nil {
					return err
				}
				return selectErr
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, map[string]bool{"created_at": true, "id": true, "updated_at": true})
		},
	}
	cmd.Flags().IntVar(&flagLimit, "limit", 10, "Max number of resources returned in a paged collection. Defaults to 10, with a minimum of 1 and maximum 500.")
	cmd.Flags().StringVar(&flagPageToken, "page-token", "", "Token used to request the next page in paginated results. Defaults to 'null'")
	cmd.Flags().StringVar(&flagSortField, "sort-field", "id", "Field to sort by. Defaults to 'id'. (one of: id, user_id, created_at, updated_at)")
	cmd.Flags().StringVar(&flagSortDirection, "sort-direction", "desc", "Sort direction. Defaults to 'desc'. (one of: asc, desc)")
	cmd.Flags().StringVar(&flagOrganizationId, "organization-id", "", "Filter by organization ID to return only memberships for that organization.")
	cmd.Flags().StringVar(&flagUserId, "user-id", "", "Filter by user ID to return only memberships for that user.")
	cmd.Flags().StringVar(&flagPermissions, "permissions", "", "Filter by permission label. (one of: Admin, Security Engineer, User, Read-only, Finance, Marketing, Provisioner)")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
