// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newReportsGetV1Cmd(flags *rootFlags) *cobra.Command {
	var flagLimit int
	var flagPageToken string
	var flagPeriodMin string
	var flagPeriodMax string
	var flagOrganizationId string
	var flagType string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-v1",
		Aliases:     []string{"list"},
		Short:       "Shows Summary Reports associated with your account.",
		Example:     "  huntress-cli reports get-v1",
		Annotations: map[string]string{"pp:endpoint": "reports.get-v1", "pp:method": "GET", "pp:path": "/v1/reports", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("type") {
				allowedType := []string{"monthly_summary", "quarterly_summary", "yearly_summary"}
				validType := false
				for _, v := range allowedType {
					if flagType == v {
						validType = true
						break
					}
				}
				if !validType {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagType, "type", allowedType)
				}
			}
			path := "/v1/reports"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "auto", "reports", path, retainCLIQueryParams(cmd, map[string]string{
				"limit":           formatCLIParamValue(flagLimit),
				"page_token":      formatCLIParamValue(flagPageToken),
				"period_min":      formatCLIParamValue(flagPeriodMin),
				"period_max":      formatCLIParamValue(flagPeriodMax),
				"organization_id": formatCLIParamValue(flagOrganizationId),
				"type":            formatCLIParamValue(flagType),
			}, map[string][]string{"limit": {"limit"}, "page_token": {"page-token"}, "period_min": {"period-min"}, "period_max": {"period-max"}, "organization_id": {"organization-id"}, "type": {"type"}}, "page_token", "page_token"), nil, flagAll, "page_token", "page_token", "limit", 10, "pagination.next_page_token", "", "reports", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			outputData := collectionItemsForOutput(data, path)
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(outputData, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				var selectErr error
				filtered := data
				if flags.selectFields != "" {
					filtered, selectErr = filterFieldsChecked(filtered, flags.selectFields)
					selectErr = selectErrorForDryRun(selectErr, flags, data)
				} else if flags.compact {
					filtered = compactFields(filtered, map[string]bool{"agents_count": true, "allowed_exclusions_count": true, "analyst_name": true, "analyst_title": true, "antivirus_exclusions_count": true, "blocked_malware_count": true, "created_at": true, "deployed_canaries_count": true, "external_ips_count": true, "external_ports_count": true, "firewall_disabled_count": true, "firewall_disabled_with_conflict_count": true, "firewall_enabled_count": true, "firewall_enabled_with_conflict_count": true, "id": true, "investigated_mav_detection_count": true, "itdr_billable_identity_count": true, "itdr_non_billable_identity_count": true, "macos_agent_count": true, "mav_incident_report_count": true, "new_exclusions_count": true, "organization_id": true, "powerful_application_count": true, "protected_profiles_count": true, "risky_exclusions_removed_count": true, "risky_services_count": true, "servers_agent_count": true, "total_mav_detection_count": true, "type": true, "updated_at": true, "url": true, "weak_application_count": true, "windows_agent_count": true})
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				wrapped, wrapErr = wrapPlatformStructuredOutput(wrapped, flags, "results", true)
				if wrapErr != nil {
					return wrapErr
				}
				if err := printOutput(cmd.OutOrStdout(), wrapped, true); err != nil {
					return err
				}
				return selectErr
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, map[string]bool{"agents_count": true, "allowed_exclusions_count": true, "analyst_name": true, "analyst_title": true, "antivirus_exclusions_count": true, "blocked_malware_count": true, "created_at": true, "deployed_canaries_count": true, "external_ips_count": true, "external_ports_count": true, "firewall_disabled_count": true, "firewall_disabled_with_conflict_count": true, "firewall_enabled_count": true, "firewall_enabled_with_conflict_count": true, "id": true, "investigated_mav_detection_count": true, "itdr_billable_identity_count": true, "itdr_non_billable_identity_count": true, "macos_agent_count": true, "mav_incident_report_count": true, "new_exclusions_count": true, "organization_id": true, "powerful_application_count": true, "protected_profiles_count": true, "risky_exclusions_removed_count": true, "risky_services_count": true, "servers_agent_count": true, "total_mav_detection_count": true, "type": true, "updated_at": true, "url": true, "weak_application_count": true, "windows_agent_count": true})
		},
	}
	cmd.Flags().IntVar(&flagLimit, "limit", 10, "Max number of resources returned in a paged collection. Defaults to 10, with a minimum of 1 and maximum 500.")
	cmd.Flags().StringVar(&flagPageToken, "page-token", "", "Token used to request the next page in paginated results. Defaults to 'null'")
	cmd.Flags().StringVar(&flagPeriodMin, "period-min", "", "Filter by an ISO-8601 formatted date string that represents the lower bound of the search range for the period date.")
	cmd.Flags().StringVar(&flagPeriodMax, "period-max", "", "Filter by an ISO-8601 formatted date string that represents the upper bound of the search range for the period date.")
	cmd.Flags().StringVar(&flagOrganizationId, "organization-id", "", "Filter by organization ID within Huntress account")
	cmd.Flags().StringVar(&flagType, "type", "", "Filter by report type. One of monthly_summary, quarterly_summary, yearly_summary (one of: monthly_summary, quarterly_summary, yearly_summary)")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
