// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newUnwantedAccessRulesCreationParametersCmd(flags *rootFlags) *cobra.Command {
	var bodyCategory string
	var bodyCountryCode string
	var bodyExpiresAt string
	var bodyIdentityId int
	var bodyLogic string
	var bodyNotes string
	var bodyOrganizationId int
	var bodyStartsAt string
	var bodyType string
	var bodyVpn string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "creation-parameters",
		Aliases:     []string{"create"},
		Short:       "Creates a new Unwanted Access Rule associated with your account, an organization, or a specific identity. **Rule logic.",
		Example:     "  huntress-cli unwanted-access-rules creation-parameters --type expected",
		Annotations: map[string]string{"pp:endpoint": "unwanted-access-rules.creation-parameters", "pp:method": "POST", "pp:path": "/v1/unwanted_access_rules", "pp:requires-input": "true", "pp:happy-args": "--type=expected"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("type") && bodyType == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "type")
				}
			}
			path := "/v1/unwanted_access_rules"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				if cmd.Flags().Changed("category") || bodyCategory != "" {
					bodyMap["category"] = bodyCategory
				}
				if cmd.Flags().Changed("country-code") || bodyCountryCode != "" {
					bodyMap["country_code"] = bodyCountryCode
				}
				if cmd.Flags().Changed("expires-at") || bodyExpiresAt != "" {
					bodyMap["expires_at"] = bodyExpiresAt
				}
				if cmd.Flags().Changed("identity-id") || bodyIdentityId != 0 {
					bodyMap["identity_id"] = bodyIdentityId
				}
				if cmd.Flags().Changed("logic") || bodyLogic != "" {
					bodyMap["logic"] = bodyLogic
				}
				if cmd.Flags().Changed("notes") || bodyNotes != "" {
					bodyMap["notes"] = bodyNotes
				}
				if cmd.Flags().Changed("organization-id") || bodyOrganizationId != 0 {
					bodyMap["organization_id"] = bodyOrganizationId
				}
				if cmd.Flags().Changed("starts-at") || bodyStartsAt != "" {
					bodyMap["starts_at"] = bodyStartsAt
				}
				if cmd.Flags().Changed("type") || bodyType != "" {
					bodyMap["type"] = bodyType
				}
				if cmd.Flags().Changed("vpn") || bodyVpn != "" {
					bodyMap["vpn"] = bodyVpn
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "unwanted-access-rules", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "unwanted-access-rules", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "unwanted-access-rules", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "unwanted-access-rules", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "unwanted-access-rules", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "unwanted-access-rules",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Mutation-riding reads (POST search, RPC-over-POST lists) return
				// the same single-key collection envelopes as GET reads. Unwrap
				// before filtering so rows nest once under the result key and
				// --select filters rows, not envelope keys; plain created-object
				// responses pass through unwrapSingleKeyArray untouched.
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				var selectErr error
				filtered := unwrapSingleKeyArray(data)
				if flags.selectFields != "" {
					filtered, selectErr = filterFieldsChecked(filtered, flags.selectFields)
					selectErr = selectErrorForDryRun(selectErr, flags, data)
				} else if flags.compact {
					filtered = compactFields(filtered, map[string]bool{"country_code": true, "created_at": true, "expires_at": true, "id": true, "starts_at": true, "status": true, "type": true, "updated_at": true})
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				resultKey := "data"
				if flags.agent {
					resultKey = "results"
				}
				structured, err := wrapPlatformStructuredOutput(json.RawMessage(envelopeJSON), flags, resultKey, true)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), structured, true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "unwanted-access-rules", partialFailure.Message))
				}
				return selectErr
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlagsMeta renders the body with live
			// provenance, then the typed partial-failure exit fires unless
			// --allow-partial-failure downgrades it. Without this guard a
			// partial failure would exit 0 for these output modes — the exact
			// silent-swallow regression the surrounding patch is preventing
			// for asJSON / piped output.
			printErr := printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"}, map[string]bool{"country_code": true, "created_at": true, "expires_at": true, "id": true, "starts_at": true, "status": true, "type": true, "updated_at": true})
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "unwanted-access-rules", partialFailure.Message))
			}
			return printErr
		},
	}
	cmd.Flags().StringVar(&bodyCategory, "category", "", "Category that the catchall or exception applies to. Required when `logic` is provided.")
	cmd.Flags().StringVar(&bodyCountryCode, "country-code", "", "ISO 3166-1 alpha-2 country code this rule should match. Provide for `standard` rules.")
	cmd.Flags().StringVar(&bodyExpiresAt, "expires-at", "", "UTC date (YYYY-MM-DD) when the rule expires. Omit for `expected` rules that should never expire.")
	cmd.Flags().IntVar(&bodyIdentityId, "identity-id", 0, "Scope the rule to a specific identity. Mutually exclusive with `organization_id`.")
	cmd.Flags().StringVar(&bodyLogic, "logic", "", "Rule logic.")
	cmd.Flags().StringVar(&bodyNotes, "notes", "", "Optional free-text note to attach to the rule.")
	cmd.Flags().IntVar(&bodyOrganizationId, "organization-id", 0, "Scope the rule to an organization. Mutually exclusive with `identity_id`.")
	cmd.Flags().StringVar(&bodyStartsAt, "starts-at", "", "UTC date (YYYY-MM-DD) when the rule becomes active. Omit for `expected` rules that should start immediately.")
	cmd.Flags().StringVar(&bodyType, "type", "", "Whether matching access is `expected` or `unauthorized`.")
	cmd.Flags().StringVar(&bodyVpn, "vpn", "", "Tunnel operator name this rule should match. Provide for `standard` rules.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
