// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUnwantedAccessRulesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "unwanted-access-rules",
		Short:       "Operations about Unwanted Access Rules",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newUnwantedAccessRulesCreationParametersCmd(flags))
	cmd.AddCommand(newUnwantedAccessRulesDeleteV1IdCmd(flags))
	cmd.AddCommand(newUnwantedAccessRulesGetV1Cmd(flags))
	cmd.AddCommand(newUnwantedAccessRulesGetV1IdCmd(flags))
	cmd.AddCommand(newUnwantedAccessRulesUpdateParametersCmd(flags))
	return cmd
}
