// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"os"

	"datto-bcdr-pp-cli/internal/cliutil"
	"datto-bcdr-pp-cli/internal/config"
	"github.com/spf13/cobra"
)

func newAuthCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "auth",
		Short:       "Manage authentication for Datto Bcdr",
		Annotations: map[string]string{"pp:parent-group": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAuthSetupCmd(flags))
	cmd.AddCommand(newAuthStatusCmd(flags))
	cmd.AddCommand(newAuthSetCredentialsCmd(flags))
	cmd.AddCommand(newAuthLogoutCmd(flags))

	return cmd
}

// newAuthSetupCmd prints concrete steps for getting a credential. Side-effect
// rule: print by default, --launch opt-in to open the URL, short-circuit when
// the verifier is running this in a sandboxed subprocess.
func newAuthSetupCmd(_ *rootFlags) *cobra.Command {
	var launch bool
	cmd := &cobra.Command{
		Use:     "setup",
		Short:   "Print steps for obtaining a credential (use --launch to open the URL)",
		Example: "  datto-bcdr-cli auth setup\n  datto-bcdr-cli auth setup --launch",
		RunE: func(cmd *cobra.Command, args []string) error {
			w := cmd.OutOrStdout()
			fmt.Fprintln(w, "No setup URL is configured for this CLI; check the API's docs.")
			fmt.Fprintln(w, "")
			fmt.Fprintln(w, "Then set:")
			fmt.Fprintln(w, "  export DATTO_BCDR_PUBLIC_KEY=\"your-token-here\"")
			fmt.Fprintln(w, "  export DATTO_BCDR_SECRET_KEY=\"your-token-here\"")
			fmt.Fprintln(w, "  datto-bcdr-cli auth set-credentials your-token-here your-token-here")
			if !launch {
				return nil
			}
			fmt.Fprintln(cmd.ErrOrStderr(), "no setup URL configured; cannot launch")
			return nil
		},
	}
	cmd.Flags().BoolVar(&launch, "launch", false, "Open the setup URL in your default browser")
	return cmd
}

func newAuthStatusCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "status",
		Short:   "Show authentication status",
		Example: "  datto-bcdr-cli auth status",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			w := cmd.OutOrStdout()
			header := cfg.AuthHeader()
			authed := header != ""
			refusals := cfg.CredentialRefusalSummaries()
			credentialRefused := len(refusals) > 0
			// JSON envelope: {authenticated, verified, source, config}. When not
			// authenticated, write the envelope first then return authErr
			// so exit code carries the auth-failure signal.
			if flags.asJSON {
				out := map[string]any{
					"authenticated": authed,
					"verified":      false,
					"source":        cfg.AuthSource,
					"config":        cfg.Path,
				}
				if credentialRefused {
					out["credential_refused"] = true
					out["credential_refusals"] = refusals
				}
				if authed {
					if expiresAt, _, expired, ok := jwtCredentialExpiry(jwtExpirySource(cfg)); ok {
						out["token_expires"] = expiresAt
						out["token_expired"] = expired
					}
				}
				if printErr := printJSONFiltered(w, out, flags); printErr != nil {
					return printErr
				}
				if !authed && credentialRefused {
					return authErr(cfg.CredentialRefusalError())
				}
				if !authed {
					return authErr(fmt.Errorf("no credentials configured"))
				}
				return nil
			}
			if !authed && credentialRefused {
				fmt.Fprintln(w, red("Credentials present but refused"))
				for _, refusal := range refusals {
					fmt.Fprintf(w, "  %s\n", refusal)
				}
				return authErr(cfg.CredentialRefusalError())
			}
			if !authed {
				fmt.Fprintln(w, red("Not authenticated"))
				fmt.Fprintln(w, "")
				fmt.Fprintln(w, "Set your credentials:")
				fmt.Fprintln(w, "  export DATTO_BCDR_PUBLIC_KEY=\"your-token-here\"")
				fmt.Fprintln(w, "  export DATTO_BCDR_SECRET_KEY=\"your-token-here\"")
				fmt.Fprintf(w, "  datto-bcdr-cli auth set-credentials your-token-here your-token-here\n")
				return authErr(fmt.Errorf("no credentials configured"))
			}

			fmt.Fprintln(w, green("Credentials present (not verified)"))
			fmt.Fprintf(w, "  Source: %s\n", cfg.AuthSource)
			fmt.Fprintf(w, "  Config: %s\n", cfg.Path)
			if _, line, expired, ok := jwtCredentialExpiry(jwtExpirySource(cfg)); ok {
				fmt.Fprintf(w, "  Token expires: %s\n", line)
				if expired {
					fmt.Fprintf(w, "  %s\n", "Set Basic credentials with: export DATTO_BCDR_PUBLIC_KEY=\"your-token-here\" DATTO_BCDR_SECRET_KEY=\"your-token-here\"")
				}
			}
			return nil
		},
	}
}

func newAuthSetCredentialsCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "set-credentials <bcdr_public_key> <bcdr_secret_key>",
		Short:   "Save Basic auth credentials to the credentials file",
		Example: "  datto-bcdr-cli auth set-credentials your-token-here your-token-here",
		Args: func(cmd *cobra.Command, args []string) error {
			if len(args) != 2 {
				return fmt.Errorf("requires exactly 2 args: <bcdr_public_key> <bcdr_secret_key>")
			}
			if args[0] == "" {
				return fmt.Errorf("DATTO_BCDR_PUBLIC_KEY is required")
			}
			if args[1] == "" {
				return fmt.Errorf("DATTO_BCDR_SECRET_KEY is required")
			}
			return nil
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}
			value1 := ""
			if len(args) > 1 {
				value1 = args[1]
			}
			if err := cfg.SaveCredentials(args[0], value1); err != nil {
				return configErr(fmt.Errorf("saving credentials: %w", err))
			}
			savePath := credentialSavePath(cfg)
			if flags.asJSON {
				out := map[string]any{
					"saved":       true,
					"config_path": cfg.Path,
				}
				if !cfg.AgentcookieManagedByExternalStore() {
					out["credentials_path"] = savePath
				}
				return printJSONFiltered(cmd.OutOrStdout(), out, flags)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "Credentials saved to %s\n", savePath)
			return nil
		},
	}
}

func credentialSavePath(cfg *config.Config) string {
	if cfg != nil && cfg.AgentcookieManagedByExternalStore() {
		return cfg.Path
	}
	if path, err := cliutil.CredentialsFilePath(); err == nil {
		return path
	}
	if cfg != nil {
		return cfg.Path
	}
	return ""
}

func newAuthLogoutCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "logout",
		Short:   "Clear stored credentials",
		Example: "  datto-bcdr-cli auth logout",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			if err := cfg.ClearTokens(); err != nil {
				return configErr(fmt.Errorf("clearing tokens: %w", err))
			}

			// Identify which (if any) auth env var is still exported so the
			// JSON envelope and the human prose can both surface it.
			envStillSet := ""
			if envStillSet == "" && os.Getenv("DATTO_BCDR_PUBLIC_KEY") != "" {
				envStillSet = "DATTO_BCDR_PUBLIC_KEY"
			}
			if envStillSet == "" && os.Getenv("DATTO_BCDR_SECRET_KEY") != "" {
				envStillSet = "DATTO_BCDR_SECRET_KEY"
			}

			// JSON envelope: {cleared: true, note?: "<env_var> env var is still set"}.
			if flags.asJSON {
				out := map[string]any{"cleared": true}
				if envStillSet != "" {
					out["note"] = envStillSet + " env var is still set"
				}
				return printJSONFiltered(cmd.OutOrStdout(), out, flags)
			}

			if envStillSet != "" {
				fmt.Fprintf(cmd.OutOrStdout(), "Config cleared. Note: %s env var is still set.\n", envStillSet)
				return nil
			}
			fmt.Fprintln(cmd.OutOrStdout(), "Logged out. Credentials cleared.")
			return nil
		},
	}
}
