// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBatchCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "batch",
		Short:       "Manage batch command groups",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newBatchPostCrmV3ObjectsObjectTypeArchiveArchiveCmd(flags))
	cmd.AddCommand(newBatchPostCrmV3ObjectsObjectTypeCreateCreateCmd(flags))
	cmd.AddCommand(newBatchPostCrmV3ObjectsObjectTypeReadReadCmd(flags))
	cmd.AddCommand(newBatchPostCrmV3ObjectsObjectTypeUpdateUpdateCmd(flags))
	cmd.AddCommand(newBatchPostCrmV3ObjectsObjectTypeUpsertUpsertCmd(flags))
	return cmd
}
