// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCrmCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "crm",
		Short:       "Get, create, update, and delete CRM",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCrmDeleteV4ObjectsObjectTypeObjectIdAssociationsToObjectTypeToObjectIdArchiveCmd(flags))
	cmd.AddCommand(newCrmGetV4ObjectsObjectTypeObjectIdAssociationsToObjectTypeGetPageCmd(flags))
	cmd.AddCommand(newCrmPostV4AssociationsFromObjectTypeToObjectTypeBatchArchiveArchiveCmd(flags))
	cmd.AddCommand(newCrmPostV4AssociationsFromObjectTypeToObjectTypeBatchAssociateDefaultCreateDefaultCmd(flags))
	cmd.AddCommand(newCrmPostV4AssociationsFromObjectTypeToObjectTypeBatchCreateCreateCmd(flags))
	cmd.AddCommand(newCrmPostV4AssociationsFromObjectTypeToObjectTypeBatchLabelsArchiveArchiveLabelsCmd(flags))
	cmd.AddCommand(newCrmPostV4AssociationsFromObjectTypeToObjectTypeBatchReadGetPageCmd(flags))
	cmd.AddCommand(newCrmPostV4AssociationsUsageHighUsageReportUserIdRequestCmd(flags))
	cmd.AddCommand(newCrmPutV4ObjectsFromObjectTypeFromObjectIdAssociationsDefaultToObjectTypeToObjectIdCreateDefaultCmd(flags))
	cmd.AddCommand(newCrmPutV4ObjectsObjectTypeObjectIdAssociationsToObjectTypeToObjectIdCreateCmd(flags))
	return cmd
}
