// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newHubspotProductsCrmCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "hubspot-products-crm",
		Short:       "Manage hubspot products crm",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newHubspotProductsCrmDeleteV3ObjectsProductsProductIdArchiveCmd(flags))
	cmd.AddCommand(newHubspotProductsCrmGetV3ObjectsProductsGetPageCmd(flags))
	cmd.AddCommand(newHubspotProductsCrmGetV3ObjectsProductsProductIdGetByIdCmd(flags))
	cmd.AddCommand(newHubspotProductsCrmPatchV3ObjectsProductsProductIdUpdateCmd(flags))
	cmd.AddCommand(newHubspotProductsCrmPostV3ObjectsProductsBatchArchiveArchiveCmd(flags))
	cmd.AddCommand(newHubspotProductsCrmPostV3ObjectsProductsBatchCreateCreateCmd(flags))
	cmd.AddCommand(newHubspotProductsCrmPostV3ObjectsProductsBatchReadReadCmd(flags))
	cmd.AddCommand(newHubspotProductsCrmPostV3ObjectsProductsBatchUpdateUpdateCmd(flags))
	cmd.AddCommand(newHubspotProductsCrmPostV3ObjectsProductsBatchUpsertUpsertCmd(flags))
	cmd.AddCommand(newHubspotProductsCrmPostV3ObjectsProductsCreateCmd(flags))
	cmd.AddCommand(newHubspotProductsCrmPostV3ObjectsProductsSearchDoSearchCmd(flags))
	return cmd
}
