// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newHubspotListsCrmPostV3ListsV3ListsCmd(flags *rootFlags) *cobra.Command {
	var bodyCustomProperties string
	var bodyFilterBranch string
	var bodyListFolderId int
	var bodyListPermissionsTeamsWithEditAccess string
	var bodyListPermissionsUsersWithEditAccess string
	var bodyMembershipSettingsIncludeUnassigned bool
	var bodyMembershipSettingsMembershipTeamId int
	var bodyName string
	var bodyObjectTypeId string
	var bodyProcessingType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "post-v3-lists-v3-lists",
		Short:       "Post v3 lists v3 lists",
		Annotations: map[string]string{"pp:endpoint": "hubspot-lists-crm.post-v3-lists-v3-lists", "pp:method": "POST", "pp:path": "/crm/v3/lists", "pp:requires-input": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if !stdinBody {
				if (cmd.Flags().Changed("list-permissions-teams-with-edit-access") || bodyListPermissionsTeamsWithEditAccess != "") || (cmd.Flags().Changed("list-permissions-users-with-edit-access") || bodyListPermissionsUsersWithEditAccess != "") {
					if !cmd.Flags().Changed("list-permissions-teams-with-edit-access") && bodyListPermissionsTeamsWithEditAccess == "" && !flags.dryRun {
						return fmt.Errorf("required flag \"%s\" not set", "list-permissions-teams-with-edit-access")
					}
					if !cmd.Flags().Changed("list-permissions-users-with-edit-access") && bodyListPermissionsUsersWithEditAccess == "" && !flags.dryRun {
						return fmt.Errorf("required flag \"%s\" not set", "list-permissions-users-with-edit-access")
					}
				}
				if !cmd.Flags().Changed("name") && bodyName == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "name")
				}
				if !cmd.Flags().Changed("object-type-id") && bodyObjectTypeId == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "object-type-id")
				}
				if !cmd.Flags().Changed("processing-type") && bodyProcessingType == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "processing-type")
				}
			}
			path := "/crm/v3/lists"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				if cmd.Flags().Changed("custom-properties") || bodyCustomProperties != "" {
					var parsedCustomProperties any
					if err := json.Unmarshal([]byte(bodyCustomProperties), &parsedCustomProperties); err != nil {
						return fmt.Errorf("parsing --custom-properties JSON: %w", err)
					}
					asMap, ok := parsedCustomProperties.(map[string]any)
					if !ok {
						return fmt.Errorf("--custom-properties must be a JSON object, got JSON %T", parsedCustomProperties)
					}
					bodyMap["customProperties"] = asMap
				}
				if cmd.Flags().Changed("filter-branch") || bodyFilterBranch != "" {
					bodyMap["filterBranch"] = bodyFilterBranch
				}
				if cmd.Flags().Changed("list-folder-id") || bodyListFolderId != 0 {
					bodyMap["listFolderId"] = bodyListFolderId
				}
				{
					nestedListPermissions := map[string]any{}
					if cmd.Flags().Changed("list-permissions-teams-with-edit-access") || bodyListPermissionsTeamsWithEditAccess != "" {
						var parsedListPermissionsTeamsWithEditAccess any
						if err := json.Unmarshal([]byte(bodyListPermissionsTeamsWithEditAccess), &parsedListPermissionsTeamsWithEditAccess); err != nil {
							return fmt.Errorf("parsing --list-permissions-teams-with-edit-access JSON: %w", err)
						}
						asArray, ok := parsedListPermissionsTeamsWithEditAccess.([]any)
						if !ok {
							return fmt.Errorf("--list-permissions-teams-with-edit-access must be a JSON array, got JSON %T", parsedListPermissionsTeamsWithEditAccess)
						}
						nestedListPermissions["teamsWithEditAccess"] = asArray
					}
					if cmd.Flags().Changed("list-permissions-users-with-edit-access") || bodyListPermissionsUsersWithEditAccess != "" {
						var parsedListPermissionsUsersWithEditAccess any
						if err := json.Unmarshal([]byte(bodyListPermissionsUsersWithEditAccess), &parsedListPermissionsUsersWithEditAccess); err != nil {
							return fmt.Errorf("parsing --list-permissions-users-with-edit-access JSON: %w", err)
						}
						asArray, ok := parsedListPermissionsUsersWithEditAccess.([]any)
						if !ok {
							return fmt.Errorf("--list-permissions-users-with-edit-access must be a JSON array, got JSON %T", parsedListPermissionsUsersWithEditAccess)
						}
						nestedListPermissions["usersWithEditAccess"] = asArray
					}
					if len(nestedListPermissions) > 0 {
						bodyMap["listPermissions"] = nestedListPermissions
					}
				}
				{
					nestedMembershipSettings := map[string]any{}
					if cmd.Flags().Changed("membership-settings-include-unassigned") {
						nestedMembershipSettings["includeUnassigned"] = bodyMembershipSettingsIncludeUnassigned
					}
					if cmd.Flags().Changed("membership-settings-membership-team-id") || bodyMembershipSettingsMembershipTeamId != 0 {
						nestedMembershipSettings["membershipTeamId"] = bodyMembershipSettingsMembershipTeamId
					}
					if len(nestedMembershipSettings) > 0 {
						bodyMap["membershipSettings"] = nestedMembershipSettings
					}
				}
				if cmd.Flags().Changed("name") || bodyName != "" {
					bodyMap["name"] = bodyName
				}
				if cmd.Flags().Changed("object-type-id") || bodyObjectTypeId != "" {
					bodyMap["objectTypeId"] = bodyObjectTypeId
				}
				if cmd.Flags().Changed("processing-type") || bodyProcessingType != "" {
					bodyMap["processingType"] = bodyProcessingType
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "hubspot-lists-crm", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "hubspot-lists-crm", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "hubspot-lists-crm", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "hubspot-lists-crm", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "hubspot-lists-crm", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "hubspot-lists-crm",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Mutation-riding reads (POST search, RPC-over-POST lists) return
				// the same single-key collection envelopes as GET reads. Unwrap
				// before filtering so rows nest once under the result key and
				// --select filters rows, not envelope keys; plain created-object
				// responses pass through unwrapSingleKeyArray untouched.
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				var selectErr error
				filtered := unwrapSingleKeyArray(data)
				if flags.selectFields != "" {
					filtered, selectErr = filterFieldsChecked(filtered, flags.selectFields)
					selectErr = selectErrorForDryRun(selectErr, flags, data)
				} else if flags.compact {
					filtered = compactFields(filtered, nil)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				resultKey := "data"
				if flags.agent {
					resultKey = "results"
				}
				structured, err := wrapPlatformStructuredOutput(json.RawMessage(envelopeJSON), flags, resultKey, true)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), structured, true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "hubspot-lists-crm", partialFailure.Message))
				}
				return selectErr
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlagsMeta renders the body with live
			// provenance, then the typed partial-failure exit fires unless
			// --allow-partial-failure downgrades it. Without this guard a
			// partial failure would exit 0 for these output modes — the exact
			// silent-swallow regression the surrounding patch is preventing
			// for asJSON / piped output.
			printErr := printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"}, nil)
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "hubspot-lists-crm", partialFailure.Message))
			}
			return printErr
		},
	}
	cmd.Flags().StringVar(&bodyCustomProperties, "custom-properties", "", "The list of custom properties to tie to the list. Custom property name is the key, the value is the value.")
	cmd.Flags().StringVar(&bodyFilterBranch, "filter-branch", "", "Filter branch object containing filtering criteria for the list")
	cmd.Flags().IntVar(&bodyListFolderId, "list-folder-id", 0, "The ID of the folder that the list should be created in.")
	cmd.Flags().StringVar(&bodyListPermissionsTeamsWithEditAccess, "list-permissions-teams-with-edit-access", "", "Teams with edit access")
	cmd.Flags().StringVar(&bodyListPermissionsUsersWithEditAccess, "list-permissions-users-with-edit-access", "", "Users with edit access")
	cmd.Flags().BoolVar(&bodyMembershipSettingsIncludeUnassigned, "membership-settings-include-unassigned", false, "Indicates whether unassigned memberships should be included.")
	cmd.Flags().IntVar(&bodyMembershipSettingsMembershipTeamId, "membership-settings-membership-team-id", 0, "The ID of the team associated with the membership.")
	cmd.Flags().StringVar(&bodyName, "name", "", "The name of the list, which must be globally unique across all public lists in the portal.")
	cmd.Flags().StringVar(&bodyObjectTypeId, "object-type-id", "", "The object type ID of the type of objects that the list will store.")
	cmd.Flags().StringVar(&bodyProcessingType, "processing-type", "", "The processing type of the list. One of: `SNAPSHOT`, `MANUAL`, or `DYNAMIC`.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
