// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newHubspotImportsCrmCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "hubspot-imports-crm",
		Short:       "Manage hubspot imports crm",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newHubspotImportsCrmGetV3ImportsImportIdErrorsV3ImportsImportIdErrorsCmd(flags))
	cmd.AddCommand(newHubspotImportsCrmGetV3ImportsImportIdV3ImportsImportIdCmd(flags))
	cmd.AddCommand(newHubspotImportsCrmGetV3ImportsV3ImportsCmd(flags))
	cmd.AddCommand(newHubspotImportsCrmPostV3ImportsImportIdCancelV3ImportsImportIdCancelCmd(flags))
	cmd.AddCommand(newHubspotImportsCrmPostV3ImportsV3ImportsCmd(flags))
	return cmd
}
