// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newHubspotPropertiesCrmPostV3PropertiesObjectTypeCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyCalculationFormula string
	var bodyCurrencyPropertyName string
	var bodyDataSensitivity string
	var bodyDescription string
	var bodyDisplayOrder int
	var bodyExternalOptions bool
	var bodyFieldType string
	var bodyFormField bool
	var bodyGroupName string
	var bodyHasUniqueValue bool
	var bodyHidden bool
	var bodyLabel string
	var bodyName string
	var bodyNumberDisplayHint string
	var bodyOptions string
	var bodyReferencedObjectType string
	var bodyShowCurrencySymbol bool
	var bodyType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "post-v3-properties-object-type-create <objectType>",
		Short:       "Create and return a copy of a new property for the specified object type.",
		Annotations: map[string]string{"pp:endpoint": "hubspot-properties-crm.post-v3-properties-object-type-create", "pp:method": "POST", "pp:path": "/crm/v3/properties/{objectType}", "pp:requires-input": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <objectType>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <objectType>"))
			}
			if !stdinBody {
				if !cmd.Flags().Changed("field-type") && bodyFieldType == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "field-type")
				}
				if !cmd.Flags().Changed("group-name") && bodyGroupName == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "group-name")
				}
				if !cmd.Flags().Changed("label") && bodyLabel == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "label")
				}
				if !cmd.Flags().Changed("name") && bodyName == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "name")
				}
				if !cmd.Flags().Changed("type") && bodyType == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "type")
				}
			}
			path := "/crm/v3/properties/{objectType}"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("objectType is required\nUsage: %s <%s>", cmd.CommandPath(), "objectType"))
			}
			path = replacePathParam(path, "objectType", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				if cmd.Flags().Changed("calculation-formula") || bodyCalculationFormula != "" {
					bodyMap["calculationFormula"] = bodyCalculationFormula
				}
				if cmd.Flags().Changed("currency-property-name") || bodyCurrencyPropertyName != "" {
					bodyMap["currencyPropertyName"] = bodyCurrencyPropertyName
				}
				if cmd.Flags().Changed("data-sensitivity") || bodyDataSensitivity != "" {
					bodyMap["dataSensitivity"] = bodyDataSensitivity
				}
				if cmd.Flags().Changed("description") || bodyDescription != "" {
					bodyMap["description"] = bodyDescription
				}
				if cmd.Flags().Changed("display-order") || bodyDisplayOrder != 0 {
					bodyMap["displayOrder"] = bodyDisplayOrder
				}
				if cmd.Flags().Changed("external-options") {
					bodyMap["externalOptions"] = bodyExternalOptions
				}
				if cmd.Flags().Changed("field-type") || bodyFieldType != "" {
					bodyMap["fieldType"] = bodyFieldType
				}
				if cmd.Flags().Changed("form-field") {
					bodyMap["formField"] = bodyFormField
				}
				if cmd.Flags().Changed("group-name") || bodyGroupName != "" {
					bodyMap["groupName"] = bodyGroupName
				}
				if cmd.Flags().Changed("has-unique-value") {
					bodyMap["hasUniqueValue"] = bodyHasUniqueValue
				}
				if cmd.Flags().Changed("hidden") {
					bodyMap["hidden"] = bodyHidden
				}
				if cmd.Flags().Changed("label") || bodyLabel != "" {
					bodyMap["label"] = bodyLabel
				}
				if cmd.Flags().Changed("name") || bodyName != "" {
					bodyMap["name"] = bodyName
				}
				if cmd.Flags().Changed("number-display-hint") || bodyNumberDisplayHint != "" {
					bodyMap["numberDisplayHint"] = bodyNumberDisplayHint
				}
				if cmd.Flags().Changed("options") || bodyOptions != "" {
					var parsedOptions any
					if err := json.Unmarshal([]byte(bodyOptions), &parsedOptions); err != nil {
						return fmt.Errorf("parsing --options JSON: %w", err)
					}
					asArray, ok := parsedOptions.([]any)
					if !ok {
						return fmt.Errorf("--options must be a JSON array, got JSON %T", parsedOptions)
					}
					bodyMap["options"] = asArray
				}
				if cmd.Flags().Changed("referenced-object-type") || bodyReferencedObjectType != "" {
					bodyMap["referencedObjectType"] = bodyReferencedObjectType
				}
				if cmd.Flags().Changed("show-currency-symbol") {
					bodyMap["showCurrencySymbol"] = bodyShowCurrencySymbol
				}
				if cmd.Flags().Changed("type") || bodyType != "" {
					bodyMap["type"] = bodyType
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "hubspot-properties-crm", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "hubspot-properties-crm", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "hubspot-properties-crm", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "hubspot-properties-crm", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "hubspot-properties-crm", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "hubspot-properties-crm",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Mutation-riding reads (POST search, RPC-over-POST lists) return
				// the same single-key collection envelopes as GET reads. Unwrap
				// before filtering so rows nest once under the result key and
				// --select filters rows, not envelope keys; plain created-object
				// responses pass through unwrapSingleKeyArray untouched.
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				var selectErr error
				filtered := unwrapSingleKeyArray(data)
				if flags.selectFields != "" {
					filtered, selectErr = filterFieldsChecked(filtered, flags.selectFields)
					selectErr = selectErrorForDryRun(selectErr, flags, data)
				} else if flags.compact {
					filtered = compactFields(filtered, map[string]bool{"archivedAt": true, "createdAt": true, "createdUserId": true, "currencyPropertyName": true, "groupName": true, "name": true, "type": true, "updatedAt": true, "updatedUserId": true})
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				resultKey := "data"
				if flags.agent {
					resultKey = "results"
				}
				structured, err := wrapPlatformStructuredOutput(json.RawMessage(envelopeJSON), flags, resultKey, true)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), structured, true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "hubspot-properties-crm", partialFailure.Message))
				}
				return selectErr
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlagsMeta renders the body with live
			// provenance, then the typed partial-failure exit fires unless
			// --allow-partial-failure downgrades it. Without this guard a
			// partial failure would exit 0 for these output modes — the exact
			// silent-swallow regression the surrounding patch is preventing
			// for asJSON / piped output.
			printErr := printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"}, map[string]bool{"archivedAt": true, "createdAt": true, "createdUserId": true, "currencyPropertyName": true, "groupName": true, "name": true, "type": true, "updatedAt": true, "updatedUserId": true})
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "hubspot-properties-crm", partialFailure.Message))
			}
			return printErr
		},
	}
	cmd.Flags().StringVar(&bodyCalculationFormula, "calculation-formula", "", "Represents a formula that is used to compute a calculated property.")
	cmd.Flags().StringVar(&bodyCurrencyPropertyName, "currency-property-name", "", "Currency property name")
	cmd.Flags().StringVar(&bodyDataSensitivity, "data-sensitivity", "", "Indicates the sensitivity level of the property, with options: highly_sensitive, non_sensitive, or sensitive.")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "A description of the property that will be shown as help text in HubSpot.")
	cmd.Flags().IntVar(&bodyDisplayOrder, "display-order", 0, "Properties are displayed in order starting with the lowest positive integer value.")
	cmd.Flags().BoolVar(&bodyExternalOptions, "external-options", false, "Applicable only for 'enumeration' type properties.")
	cmd.Flags().StringVar(&bodyFieldType, "field-type", "", "Controls how the property appears in HubSpot.")
	cmd.Flags().BoolVar(&bodyFormField, "form-field", false, "Whether or not the property can be used in a HubSpot form.")
	cmd.Flags().StringVar(&bodyGroupName, "group-name", "", "The name of the property group the property belongs to.")
	cmd.Flags().BoolVar(&bodyHasUniqueValue, "has-unique-value", false, "Whether or not the property's value must be unique. Once set, this can't be changed.")
	cmd.Flags().BoolVar(&bodyHidden, "hidden", false, "If true, the property won't be visible and can't be used in HubSpot.")
	cmd.Flags().StringVar(&bodyLabel, "label", "", "A human-readable property label that will be shown in HubSpot.")
	cmd.Flags().StringVar(&bodyName, "name", "", "The internal property name, which must be used when referencing the property via the API.")
	cmd.Flags().StringVar(&bodyNumberDisplayHint, "number-display-hint", "", "Number display hint")
	cmd.Flags().StringVar(&bodyOptions, "options", "", "A list of valid options for the property. This field is required for enumerated properties.")
	cmd.Flags().StringVar(&bodyReferencedObjectType, "referenced-object-type", "", "Should be set to 'OWNER' when 'externalOptions' is true")
	cmd.Flags().BoolVar(&bodyShowCurrencySymbol, "show-currency-symbol", false, "Show currency symbol")
	cmd.Flags().StringVar(&bodyType, "type", "", "The data type of the property.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
