// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newHubspotPropertiesCrmCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "hubspot-properties-crm",
		Short:       "Manage hubspot properties crm",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newHubspotPropertiesCrmDeleteV3PropertiesObjectTypePropertyNameArchiveCmd(flags))
	cmd.AddCommand(newHubspotPropertiesCrmGetV3PropertiesObjectTypeGetAllCmd(flags))
	cmd.AddCommand(newHubspotPropertiesCrmGetV3PropertiesObjectTypePropertyNameGetByNameCmd(flags))
	cmd.AddCommand(newHubspotPropertiesCrmPatchV3PropertiesObjectTypePropertyNameUpdateCmd(flags))
	cmd.AddCommand(newHubspotPropertiesCrmPostV3PropertiesObjectTypeCreateCmd(flags))
	return cmd
}
