// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newHubspotLeadsCrmCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "hubspot-leads-crm",
		Short:       "Manage hubspot leads crm",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newHubspotLeadsCrmDeleteV3ObjectsLeadsLeadsIdArchiveCmd(flags))
	cmd.AddCommand(newHubspotLeadsCrmGetV3ObjectsLeadsGetPageCmd(flags))
	cmd.AddCommand(newHubspotLeadsCrmGetV3ObjectsLeadsLeadsIdGetByIdCmd(flags))
	cmd.AddCommand(newHubspotLeadsCrmPatchV3ObjectsLeadsLeadsIdUpdateCmd(flags))
	cmd.AddCommand(newHubspotLeadsCrmPostV3ObjectsLeadsBatchArchiveArchiveCmd(flags))
	cmd.AddCommand(newHubspotLeadsCrmPostV3ObjectsLeadsBatchCreateCreateCmd(flags))
	cmd.AddCommand(newHubspotLeadsCrmPostV3ObjectsLeadsBatchReadReadCmd(flags))
	cmd.AddCommand(newHubspotLeadsCrmPostV3ObjectsLeadsBatchUpdateUpdateCmd(flags))
	cmd.AddCommand(newHubspotLeadsCrmPostV3ObjectsLeadsBatchUpsertUpsertCmd(flags))
	cmd.AddCommand(newHubspotLeadsCrmPostV3ObjectsLeadsCreateCmd(flags))
	cmd.AddCommand(newHubspotLeadsCrmPostV3ObjectsLeadsSearchDoSearchCmd(flags))
	return cmd
}
