// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newHubspotMeetingsCrmGetV3ObjectsMeetingsGetPageCmd(flags *rootFlags) *cobra.Command {
	var flagAfter string
	var flagArchived bool
	var flagAssociations string
	var flagLimit int
	var flagProperties string
	var flagPropertiesWithHistory string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-v3-objects-meetings-get-page",
		Short:       "Read a page of meetings. Control what is returned via the `properties` query param.",
		Example:     "  hubspot-cli hubspot-meetings-crm get-v3-objects-meetings-get-page",
		Annotations: map[string]string{"pp:endpoint": "hubspot-meetings-crm.get-v3-objects-meetings-get-page", "pp:method": "GET", "pp:path": "/crm/v3/objects/meetings", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/crm/v3/objects/meetings"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			if flagAssociations != "" {
				path = appendArrayQueryParam(path, "associations", flagAssociations, "form", true)
			}
			if flagProperties != "" {
				path = appendArrayQueryParam(path, "properties", flagProperties, "form", true)
			}
			if flagPropertiesWithHistory != "" {
				path = appendArrayQueryParam(path, "propertiesWithHistory", flagPropertiesWithHistory, "form", true)
			}
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "auto", "hubspot-meetings-crm", path, retainCLIQueryParams(cmd, map[string]string{
				"after":    formatCLIParamValue(flagAfter),
				"archived": formatCLIParamValue(flagArchived),
				"limit":    formatCLIParamValue(flagLimit),
			}, map[string][]string{"after": {"after"}, "archived": {"archived"}, "limit": {"limit"}}, "after", "cursor"), nil, flagAll, "after", "cursor", "limit", 10, "", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			outputData := collectionItemsForOutput(data, path)
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(outputData, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				var selectErr error
				filtered := data
				if flags.selectFields != "" {
					filtered, selectErr = filterFieldsChecked(filtered, flags.selectFields)
					selectErr = selectErrorForDryRun(selectErr, flags, data)
				} else if flags.compact {
					filtered = compactFields(filtered, nil)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				wrapped, wrapErr = wrapPlatformStructuredOutput(wrapped, flags, "results", true)
				if wrapErr != nil {
					return wrapErr
				}
				if err := printOutput(cmd.OutOrStdout(), wrapped, true); err != nil {
					return err
				}
				return selectErr
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, nil)
		},
	}
	cmd.Flags().StringVar(&flagAfter, "after", "", "The paging cursor token of the last successfully read resource will be returned as the `paging.next.")
	cmd.Flags().BoolVar(&flagArchived, "archived", false, "Whether to return only results that have been archived.")
	cmd.Flags().StringVar(&flagAssociations, "associations", "", "A comma separated list of object types to retrieve associated IDs for.")
	cmd.Flags().IntVar(&flagLimit, "limit", 10, "The maximum number of results to display per page.")
	cmd.Flags().StringVar(&flagProperties, "properties", "", "A comma separated list of the properties to be returned in the response.")
	cmd.Flags().StringVar(&flagPropertiesWithHistory, "properties-with-history", "", "A comma separated list of the properties to be returned along with their history of previous values.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
