// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"hubspot-pp-cli/internal/cliutil"
)

func newObjectsSearchPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyAfter string
	var bodyFilterGroups string
	var bodyLimit int
	var bodyProperties string
	var bodyQuery string
	var bodySorts string

	cmd := &cobra.Command{
		Use:         "objects-search <objectType>",
		Short:       "Post crm v3 objects object type search do search",
		Long:        "Post crm v3 objects object type search do search",
		Annotations: map[string]string{"pp:endpoint": "objects_search.post-crm-v3-objects-object-type-search-do-search", "pp:method": "POST", "pp:path": "/crm/v3/objects/{objectType}/search", "pp:requires-input": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with a required flag/body prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only reads fall through so a bare call still executes; positional
			// commands keep their existing usageErr (exit 2 + JSON envelope).
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if !cmd.Flags().Changed("after") && bodyAfter == "" && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "after")
			}
			if !cmd.Flags().Changed("filter-groups") && bodyFilterGroups == "" && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "filter-groups")
			}
			if !cmd.Flags().Changed("limit") && bodyLimit == 0 && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "limit")
			}
			if !cmd.Flags().Changed("properties") && bodyProperties == "" && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "properties")
			}
			if !cmd.Flags().Changed("sorts") && bodySorts == "" && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "sorts")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/crm/v3/objects/{objectType}/search"
			if len(args) < 1 || args[0] == "" {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "objectType is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "objectType"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("objectType is required\nUsage: %s <%s>", cmd.CommandPath(), "objectType"))
			}
			path = replacePathParam(path, "objectType", args[0])
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			bodyMap := map[string]any{}
			var body any = bodyMap
			if cmd.Flags().Changed("after") || bodyAfter != "" {
				bodyMap["after"] = bodyAfter
			}
			if cmd.Flags().Changed("filter-groups") || bodyFilterGroups != "" {
				var parsedFilterGroups any
				if err := json.Unmarshal([]byte(bodyFilterGroups), &parsedFilterGroups); err != nil {
					return fmt.Errorf("parsing --filter-groups JSON: %w", err)
				}
				asArray, ok := parsedFilterGroups.([]any)
				if !ok {
					return fmt.Errorf("--filter-groups must be a JSON array, got JSON %T", parsedFilterGroups)
				}
				bodyMap["filterGroups"] = asArray
			}
			if cmd.Flags().Changed("limit") || bodyLimit != 0 {
				bodyMap["limit"] = bodyLimit
			}
			if cmd.Flags().Changed("properties") {
				parsedProperties, parseErr := cliutil.ParseStringList(bodyProperties)
				if parseErr != nil {
					return fmt.Errorf("parsing --properties list: %w", parseErr)
				}
				bodyMap["properties"] = parsedProperties
			}
			if cmd.Flags().Changed("query") || bodyQuery != "" {
				bodyMap["query"] = bodyQuery
			}
			if cmd.Flags().Changed("sorts") {
				parsedSorts, parseErr := cliutil.ParseStringList(bodySorts)
				if parseErr != nil {
					return fmt.Errorf("parsing --sorts list: %w", parseErr)
				}
				bodyMap["sorts"] = parsedSorts
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)

			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "objects_search", data, "")
			}
			outputData := data
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(outputData, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{outputData}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				var selectErr error
				filtered := data
				if flags.selectFields != "" {
					filtered, selectErr = filterFieldsChecked(filtered, flags.selectFields)
					selectErr = selectErrorForDryRun(selectErr, flags, data)
				} else if flags.compact {
					filtered = compactFields(filtered, nil)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				wrapped, wrapErr = wrapPlatformStructuredOutput(wrapped, flags, "results", true)
				if wrapErr != nil {
					return wrapErr
				}
				if err := printOutput(cmd.OutOrStdout(), wrapped, true); err != nil {
					return err
				}
				return selectErr
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, nil)
		},
	}
	cmd.Flags().StringVar(&bodyAfter, "after", "", "A paging cursor token for retrieving subsequent pages.")
	cmd.Flags().StringVar(&bodyFilterGroups, "filter-groups", "", "Up to 6 groups of filters defining additional query criteria.")
	cmd.Flags().IntVar(&bodyLimit, "limit", 0, "The maximum results to return, up to 200 objects.")
	cmd.Flags().StringVar(&bodyProperties, "properties", "", "A list of property names to include in the response.")
	cmd.Flags().StringVar(&bodyQuery, "query", "", "The search query string, up to 3000 characters.")
	cmd.Flags().StringVar(&bodySorts, "sorts", "", "Specifies sorting order based on object properties.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
