// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

type resourceReadConfig struct {
	responsePath   string
	paginationType string
	cursorParam    string
	limitParam     string
	nextCursorPath string
	hasMoreField   string
	pageSize       int
}

var resourceReadPaths = map[string]string{ // #nosec G101 -- endpoint paths, not credentials.
	"hubspot-calls-crm":      "/crm/v3/objects/calls",
	"hubspot-companies-crm":  "/crm/v3/objects/companies",
	"hubspot-contacts-crm":   "/crm/v3/objects/contacts",
	"hubspot-deals-crm":      "/crm/v3/objects/0-3",
	"hubspot-emails-crm":     "/crm/v3/objects/emails",
	"hubspot-imports-crm":    "/crm/v3/imports",
	"hubspot-leads-crm":      "/crm/v3/objects/leads",
	"hubspot-line-items-crm": "/crm/v3/objects/line_items",
	"hubspot-meetings-crm":   "/crm/v3/objects/meetings",
	"hubspot-notes-crm":      "/crm/v3/objects/notes",
	"hubspot-owners-crm":     "/crm/v3/owners",
	"hubspot-products-crm":   "/crm/v3/objects/products",
	"hubspot-quotes-crm":     "/crm/v3/objects/quotes",
	"hubspot-tasks-crm":      "/crm/v3/objects/tasks",
	"hubspot-tickets-crm":    "/crm/v3/objects/tickets",
}

var resourceDetailPaths = map[string]string{ // #nosec G101 -- endpoint paths, not credentials.
	"groups":                 "/crm/v3/properties/{objectType}/groups",
	"hubspot-calls-crm":      "/crm/v3/objects/calls/{callId}",
	"hubspot-companies-crm":  "/crm/v3/objects/companies/{companyId}",
	"hubspot-contacts-crm":   "/crm/v3/objects/contacts/{contactId}",
	"hubspot-deals-crm":      "/crm/v3/objects/0-3/{dealId}",
	"hubspot-emails-crm":     "/crm/v3/objects/emails/{emailId}",
	"hubspot-imports-crm":    "/crm/v3/imports/{importId}",
	"hubspot-leads-crm":      "/crm/v3/objects/leads/{leadsId}",
	"hubspot-line-items-crm": "/crm/v3/objects/line_items/{lineItemId}",
	"hubspot-lists-crm":      "/crm/v3/lists/{listId}/schedule-conversion",
	"hubspot-meetings-crm":   "/crm/v3/objects/meetings/{meetingId}",
	"hubspot-notes-crm":      "/crm/v3/objects/notes/{noteId}",
	"hubspot-owners-crm":     "/crm/v3/owners/{ownerId}",
	"hubspot-pipelines-crm":  "/crm/v3/pipelines/{objectType}",
	"hubspot-products-crm":   "/crm/v3/objects/products/{productId}",
	"hubspot-properties-crm": "/crm/v3/properties/{objectType}",
	"hubspot-quotes-crm":     "/crm/v3/objects/quotes/{quoteId}",
	"hubspot-tasks-crm":      "/crm/v3/objects/tasks/{taskId}",
	"hubspot-tickets-crm":    "/crm/v3/objects/tickets/{ticketId}",
}

var resourceWritePaths = map[string]string{ // #nosec G101 -- endpoint paths, not credentials.
	"hubspot-calls-crm":      "/crm/v3/objects/calls/batch/archive",
	"hubspot-companies-crm":  "/crm/v3/objects/companies/batch/archive",
	"hubspot-contacts-crm":   "/crm/v3/objects/contacts",
	"hubspot-deals-crm":      "/crm/v3/objects/0-3/batch/archive",
	"hubspot-emails-crm":     "/crm/v3/objects/emails/batch/archive",
	"hubspot-imports-crm":    "/crm/v3/imports",
	"hubspot-leads-crm":      "/crm/v3/objects/leads/batch/archive",
	"hubspot-line-items-crm": "/crm/v3/objects/line_items/batch/archive",
	"hubspot-lists-crm":      "/crm/v3/lists/folders",
	"hubspot-meetings-crm":   "/crm/v3/objects/meetings/batch/archive",
	"hubspot-notes-crm":      "/crm/v3/objects/notes/batch/archive",
	"hubspot-products-crm":   "/crm/v3/objects/products/batch/archive",
	"hubspot-quotes-crm":     "/crm/v3/objects/quotes/batch/archive",
	"hubspot-tasks-crm":      "/crm/v3/objects/tasks/batch/archive",
	"hubspot-tickets-crm":    "/crm/v3/objects/tickets/batch/archive",
}

var resourceReadConfigs = map[string]resourceReadConfig{
	"hubspot-calls-crm":      {responsePath: "", paginationType: "cursor", cursorParam: "after", limitParam: "limit", nextCursorPath: "", hasMoreField: "", pageSize: 10},
	"hubspot-companies-crm":  {responsePath: "", paginationType: "cursor", cursorParam: "after", limitParam: "limit", nextCursorPath: "", hasMoreField: "", pageSize: 10},
	"hubspot-contacts-crm":   {responsePath: "", paginationType: "cursor", cursorParam: "after", limitParam: "limit", nextCursorPath: "", hasMoreField: "", pageSize: 10},
	"hubspot-deals-crm":      {responsePath: "", paginationType: "cursor", cursorParam: "after", limitParam: "limit", nextCursorPath: "", hasMoreField: "", pageSize: 10},
	"hubspot-emails-crm":     {responsePath: "", paginationType: "cursor", cursorParam: "after", limitParam: "limit", nextCursorPath: "", hasMoreField: "", pageSize: 10},
	"hubspot-imports-crm":    {responsePath: "", paginationType: "cursor", cursorParam: "after", limitParam: "limit", nextCursorPath: "", hasMoreField: "", pageSize: 100},
	"hubspot-leads-crm":      {responsePath: "", paginationType: "cursor", cursorParam: "after", limitParam: "limit", nextCursorPath: "", hasMoreField: "", pageSize: 10},
	"hubspot-line-items-crm": {responsePath: "", paginationType: "cursor", cursorParam: "after", limitParam: "limit", nextCursorPath: "", hasMoreField: "", pageSize: 10},
	"hubspot-meetings-crm":   {responsePath: "", paginationType: "cursor", cursorParam: "after", limitParam: "limit", nextCursorPath: "", hasMoreField: "", pageSize: 10},
	"hubspot-notes-crm":      {responsePath: "", paginationType: "cursor", cursorParam: "after", limitParam: "limit", nextCursorPath: "", hasMoreField: "", pageSize: 10},
	"hubspot-owners-crm":     {responsePath: "", paginationType: "cursor", cursorParam: "after", limitParam: "limit", nextCursorPath: "", hasMoreField: "", pageSize: 100},
	"hubspot-products-crm":   {responsePath: "", paginationType: "cursor", cursorParam: "after", limitParam: "limit", nextCursorPath: "", hasMoreField: "", pageSize: 10},
	"hubspot-quotes-crm":     {responsePath: "", paginationType: "cursor", cursorParam: "after", limitParam: "limit", nextCursorPath: "", hasMoreField: "", pageSize: 10},
	"hubspot-tasks-crm":      {responsePath: "", paginationType: "cursor", cursorParam: "after", limitParam: "limit", nextCursorPath: "", hasMoreField: "", pageSize: 10},
	"hubspot-tickets-crm":    {responsePath: "", paginationType: "cursor", cursorParam: "after", limitParam: "limit", nextCursorPath: "", hasMoreField: "", pageSize: 10},
}

func resourceReadPath(resource string) (string, error) {
	if path, ok := resourceReadPaths[resource]; ok {
		return path, nil
	}
	return "", fmt.Errorf("unknown readable resource %q", resource)
}

func resourceWritePath(resource string) (string, error) {
	if path, ok := resourceWritePaths[resource]; ok {
		return path, nil
	}
	return "", fmt.Errorf("unknown writable resource %q", resource)
}

func resourceDetailPath(resource, escapedID string) (string, error) {
	path, ok := resourceDetailPaths[resource]
	if !ok {
		return "", fmt.Errorf("resource %q does not declare a single-item read path", resource)
	}
	start := strings.Index(path, "{")
	end := strings.Index(path, "}")
	if start < 0 || end <= start {
		return "", fmt.Errorf("resource %q has an invalid single-item read path", resource)
	}
	return path[:start] + escapedID + path[end+1:], nil
}

func resourceReadConfigFor(resource string) resourceReadConfig {
	return resourceReadConfigs[resource]
}

func extractResourcePage(data json.RawMessage, config resourceReadConfig) ([]json.RawMessage, string, bool) {
	if items, ok := resourceJSONArray(data); ok {
		return items, "", false
	}

	var envelope map[string]json.RawMessage
	if json.Unmarshal(data, &envelope) != nil {
		return nil, "", false
	}
	if config.responsePath != "" {
		if payload, ok := responsePayloadAtPath(data, config.responsePath); ok {
			if items, ok := resourceJSONArray(payload); ok {
				next, hasMore := resourcePagination(data, envelope, config)
				return items, next, hasMore
			}
		}
	}
	for _, key := range []string{"data", "results", "items", "records", "nodes", "entries", "features", "Data", "Results", "Items", "Records", "Nodes", "Entries", "Features"} {
		if items, ok := resourceJSONArray(envelope[key]); ok {
			next, hasMore := resourcePagination(data, envelope, config)
			return items, next, hasMore
		}
	}
	for _, key := range []string{"data", "result", "Data", "Result"} {
		var nested map[string]json.RawMessage
		if json.Unmarshal(envelope[key], &nested) != nil {
			continue
		}
		for _, nestedKey := range []string{"data", "results", "items", "records", "nodes", "entries", "features", "Data", "Results", "Items", "Records", "Nodes", "Entries", "Features"} {
			if items, ok := resourceJSONArray(nested[nestedKey]); ok {
				next, hasMore := resourcePagination(data, envelope, config)
				return items, next, hasMore
			}
		}
		if items, ok := resourceSingleArray(nested); ok {
			next, hasMore := resourcePagination(data, envelope, config)
			return items, next, hasMore
		}
	}
	if items, ok := resourceSingleArray(envelope); ok {
		next, hasMore := resourcePagination(data, envelope, config)
		return items, next, hasMore
	}
	return nil, "", false
}

func resourceSingleArray(envelope map[string]json.RawMessage) ([]json.RawMessage, bool) {
	var only []json.RawMessage
	arrays := 0
	for key, raw := range envelope {
		if resourceEnvelopeMetadataKey(key) {
			continue
		}
		if items, ok := resourceJSONArray(raw); ok {
			only = items
			arrays++
			continue
		}
		if strings.TrimSpace(string(raw)) != "null" {
			return nil, false
		}
	}
	return only, arrays == 1
}

func resourceJSONArray(data json.RawMessage) ([]json.RawMessage, bool) {
	if len(data) == 0 || strings.TrimSpace(string(data)) == "null" {
		return nil, false
	}
	var items []json.RawMessage
	if json.Unmarshal(data, &items) != nil {
		return nil, false
	}
	return items, true
}

func resourcePagination(data json.RawMessage, envelope map[string]json.RawMessage, config resourceReadConfig) (string, bool) {
	declaredMore := false
	if config.hasMoreField != "" {
		if raw, ok := responsePayloadAtPath(data, config.hasMoreField); ok {
			var value bool
			if json.Unmarshal(raw, &value) == nil {
				if !value {
					return "", false
				}
				declaredMore = true
			}
		}
	}
	if config.nextCursorPath != "" {
		if raw, ok := responsePayloadAtPath(data, config.nextCursorPath); ok {
			if value := resourceCursorValue(raw); value != "" {
				return value, true
			}
		}
	}
	envelopes := []map[string]json.RawMessage{envelope}
	for i := 0; i < len(envelopes) && i < 16; i++ {
		for _, key := range []string{"data", "result", "meta", "pagination", "Data", "Result", "Meta", "Pagination"} {
			var nested map[string]json.RawMessage
			if json.Unmarshal(envelopes[i][key], &nested) == nil {
				envelopes = append(envelopes, nested)
			}
		}
	}
	for _, candidate := range envelopes {
		for _, key := range []string{config.cursorParam, "next_cursor", "nextCursor", "next_token", "nextToken", "next_page_token", "nextPageToken"} {
			if key == "" {
				continue
			}
			raw, ok := candidate[key]
			if !ok {
				continue
			}
			if value := resourceCursorValue(raw); value != "" {
				return value, true
			}
		}
	}
	if declaredMore {
		return "", true
	}
	for _, candidate := range envelopes {
		for _, key := range []string{"has_more", "hasMore", "has_next", "hasNext"} {
			var value bool
			if raw, ok := candidate[key]; ok && json.Unmarshal(raw, &value) == nil {
				return "", value
			}
		}
	}
	return "", false
}

func resourceCursorValue(raw json.RawMessage) string {
	var value string
	if json.Unmarshal(raw, &value) == nil && value != "" {
		return value
	}
	var number json.Number
	if json.Unmarshal(raw, &number) == nil && number.String() != "" {
		return number.String()
	}
	return ""
}

func resourceEnvelopeMetadataKey(key string) bool {
	switch key {
	case "total", "totalResults", "total_count", "count", "size", "links", "meta", "pagination", "next_cursor", "nextCursor", "next_token", "nextToken", "next_page_token", "nextPageToken", "has_more", "hasMore", "has_next", "hasNext", "errors", "warnings":
		return true
	default:
		return false
	}
}

func resourcePageParams(config resourceReadConfig, cursor string, page int, remaining int) map[string]string {
	params := map[string]string{}
	pageSize := config.pageSize
	if pageSize <= 0 {
		pageSize = 100
	}
	stride := pageSize
	if remaining > 0 && remaining < pageSize && config.paginationType != "page" {
		pageSize = remaining
	}
	if config.limitParam != "" {
		params[config.limitParam] = strconv.Itoa(pageSize)
	}
	if config.cursorParam != "" {
		switch config.paginationType {
		case "offset":
			params[config.cursorParam] = strconv.Itoa(page * stride)
		case "page":
			params[config.cursorParam] = strconv.Itoa(page + 1)
		default:
			if cursor != "" {
				params[config.cursorParam] = cursor
			}
		}
	}
	return params
}

func resourceNextCursor(config resourceReadConfig, current, next string, hasMore bool) (string, bool, error) {
	if config.paginationType == "offset" || config.paginationType == "page" {
		return current, false, nil
	}
	if next == "" {
		if hasMore {
			return "", false, fmt.Errorf("pagination reports more pages without an advanceable cursor")
		}
		return "", true, nil
	}
	if next == current {
		return "", false, fmt.Errorf("pagination cursor %q did not advance", current)
	}
	return next, false, nil
}
