// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

// whichEntry is one row of the curated capability index. The index is seeded
// at generation time from novel hero features first, then promoted endpoint
// commands, deduped by Command so a novel that replaced a promoted leaf keeps
// the hero copy.
type whichEntry struct {
	Command      string `json:"command"`
	Description  string `json:"description"`
	Group        string `json:"group,omitempty"`
	WhyItMatters string `json:"why_it_matters,omitempty"`
}

// whichIndex is the curated list of capabilities this CLI advertises.
// Novel hero features come first (declaration-order ties); promoted
// endpoint commands follow so natural-language queries can find them.
var whichIndex = []whichEntry{
	{Command: "stale", Description: "Find contacts or deals with no engagement in N days, scoped by owner or pipeline stage — instantly, offline.", Group: "Local state that compounds", WhyItMatters: "Use this when the user asks 'what's gone cold' — works after one sync, no API quota burn."},
	{Command: "owner-load", Description: "Open deals per rep per pipeline stage with $ totals, count, and oldest-deal age — the Monday-morning sales-lead report.", Group: "Local state that compounds", WhyItMatters: "Pick this over per-rep API calls when surfacing 'who has too many in-flight deals' or 'where is rep capacity hot'."},
	{Command: "pipeline-health", Description: "Per-stage rollup of count, $ total, $ at risk (idle deals near their close date), and the oldest-stuck deal — one query for a sales-ops dashboard. Closed Lost weighted at probability 0, Closed Won at 1.0.", Group: "Local state that compounds", WhyItMatters: "Use this for forecast-vs-reality checks before a pipeline review."},
	{Command: "nurture queue", Description: "Ranked 'who to contact today' list scored by stale-days × deal amount × stage probability, with the rationale exposed as columns.", Group: "Local state that compounds", WhyItMatters: "Reach for this in the nurture skill or any daily-touch-list loop where an agent needs a priority order with reasons attached."},
	{Command: "deals top", Description: "Composite-ranked top-N deals by (signal × amount × stage-probability × inverse-days-since-contact) with the score breakdown exposed as columns.", Group: "Local state that compounds", WhyItMatters: "Pick this for sales-lead Monday reviews or when an agent needs the top opportunities ranked by signal-weighted score, not raw amount."},
	{Command: "meetings history", Description: "Show the full timeline of property changes for a single meeting (outcome, title, owner, custom fields) — when each value was set, by whom, and from what source.", Group: "Property history & audit", WhyItMatters: "Reach for this when investigating 'when did this meeting flip from Scheduled to No Show, and who changed it'. Requires a prior 'sync --resources hubspot-meetings-crm --with-history <props>' to populate the history table."},
	{Command: "meetings ever-had", Description: "Find every meeting whose given property was EVER set to a given value within a date range — even if it has since changed.", Group: "Property history & audit", WhyItMatters: "Pick this when a customer or audit asks 'every meeting that was at some point in status X during month Y'. Requires a prior 'sync --with-history' capture; the standard /search API cannot answer it."},
	{Command: "meetings status-report", Description: "Composes the meetings ever-had query into the canonical monthly-report shape: every meeting that touched the given status in the given month, with owner, title, current status, and the timestamp of the original status set.", Group: "Property history & audit", WhyItMatters: "Use this once per month per customer report — one command replaces a Python pull + a HubSpot export + a manual cross-reference. Requires a prior 'sync --resources hubspot-meetings-crm --with-history hs_meeting_outcome'."},
	{Command: "sync --with-history", Description: "Opt-in sync flag that requests propertiesWithHistory for the named properties on meetings (and on deals, contacts, companies when scoped to those). Persists per-property snapshots into the shared hubspot_property_history table.", Group: "Property history & audit", WhyItMatters: "Reach for this when you need property change history retained. Without --with-history sync only captures current values; with it, every read after that point can answer 'was this property ever value X' questions."},
	{Command: "engagements of", Description: "Unified chronological timeline of every call, email, meeting, note, and task touching a contact, deal, or company.", Group: "Cross-object intelligence", WhyItMatters: "Use this when an agent or human asks 'what touched this prospect/deal' — one command instead of five paginated API calls."},
	{Command: "notes signals", Description: "Scan note bodies for buying / lost signals (meeting scheduled, budget approved, no response, competitor chosen) and emit per-deal signal counts with the source note id.", Group: "Cross-object intelligence", WhyItMatters: "Use this when summarizing what's heating up or cooling off in the pipeline without re-reading every note."},
	{Command: "since", Description: "What changed across contacts, deals, and engagements since a given timestamp — agent-friendly cross-object delta.", Group: "Cross-object intelligence", WhyItMatters: "Reach for this in agent loops that need to react to CRM activity since the last run without paginating every collection."},
	{Command: "nurture-mine", Description: "Surface the contacts assigned to you that have gone cold but still have open deals — the daily 'who do I call' list, computed across local SQLite.", Group: "Bulk operations", WhyItMatters: "Reach for this when an agent or human needs the daily Titans-style nurture queue without round-tripping HubSpot for every prospect."},
	{Command: "contacts bulk-update", Description: "Apply a CSV of property changes to many contacts at once, pre-validating each row against HubSpot's property schema (types, picklists) before any mutation.", Group: "Bulk operations", WhyItMatters: "Pick this over the HubSpot UI when sales-ops needs to update hundreds of contacts and demands a pre-flight error report rather than silent failures."},
	{Command: "deals velocity", Description: "Per-deal days-in-current-stage and per-stage median/p90 dwell time, computed from dealstage change history — find where deals rot.", Group: "Property history & audit", WhyItMatters: "Use this when the user asks where deals stall or how long deals sit per stage — requires a prior sync deals --with-history dealstage."},
	{Command: "contacts funnel", Description: "One-shot funnel table of contacts per lifecycle stage (subscriber → lead → MQL → SQL → opportunity → customer) with stage-to-stage conversion ratios.", Group: "Cross-object intelligence", WhyItMatters: "Use this for 'where is the top of funnel leaking' questions — instant offline funnel snapshot after one sync."},
	{Command: "deals unowned", Description: "Open deals with no owner or owned by a deactivated rep, with per-stage dollar exposure — the hygiene gap owner-load can't see.", Group: "Cross-object intelligence", WhyItMatters: "Use this in the weekly hygiene pass to find orphaned deals before they rot — distinct from owner-load, which only aggregates owned deals."},
	{Command: "contacts win-back", Description: "Contacts attached to a Closed Won deal but with no engagement in N days — the customer-expansion and re-engage list.", Group: "Cross-object intelligence", WhyItMatters: "Use this for post-win expansion outreach — distinct from nurture-mine (open-deal cold) and stale (any cold)."},
	{Command: "deals forecast", Description: "Probability-weighted pipeline forecast bucketed by close-date month — the canonical GM revenue question, answered offline.", Group: "Cross-object intelligence", WhyItMatters: "Use this for close-month weighted totals for revenue reviews; pipeline-health answers per-stage risk, forecast answers per-month expectation."},
	{Command: "objects-search", Description: "Post crm v3 objects object type search do search", Group: "objects-search", WhyItMatters: "Post crm v3 objects object type search do search"}, // pp:which-promoted
}

// whichMatch pairs an index entry with its ranking score for a query.
// Higher score means stronger match. The ranker is naive (exact token
// then substring then group tag) because 20-40 entries do not need
// semantic retrieval - a ranker upgrade is a future change that would
// not break this contract.
type whichMatch struct {
	Entry whichEntry `json:"entry"`
	Score int        `json:"score"`
}

// rankWhich returns up to `limit` best matches for `query` against the
// index, sorted by descending score. Score breakdown:
//
//	+3  exact token match on the command's leaf or full path
//	+2  substring match on the command (any part)
//	+2  substring match on description or why_it_matters
//	+1  per-token match on description or why_it_matters (capped at 3)
//	+1  group tag contains the query as a whole token
//
// Ties break on declaration order in the index. An empty query returns
// every entry at score 0 in declaration order - this is the "list all"
// behavior the skill documents for broad agent discovery.
func rankWhich(index []whichEntry, query string, limit int) []whichMatch {
	if limit <= 0 {
		limit = 3
	}
	q := strings.ToLower(strings.TrimSpace(query))
	if q == "" {
		out := make([]whichMatch, 0, len(index))
		for _, e := range index {
			out = append(out, whichMatch{Entry: e, Score: 0})
		}
		return out
	}
	// Sub-tokenize the query the same way command paths are split, so a
	// pasted hyphenated capability (repos-list-for-authenticated) matches.
	qTokens := whichSubTokens(q)

	scored := make([]whichMatch, 0, len(index))
	for i, e := range index {
		score := whichScoreEntry(e, q, qTokens)
		scored = append(scored, whichMatch{Entry: e, Score: score})
		_ = i
	}

	sort.SliceStable(scored, func(i, j int) bool {
		if scored[i].Score != scored[j].Score {
			return scored[i].Score > scored[j].Score
		}
		// Specificity tie-break: at equal score prefer the command with the
		// fewest capability sub-tokens - the canonical operation over variants
		// carrying extra words the request never used.
		return len(whichSubTokens(strings.ToLower(scored[i].Entry.Command))) <
			len(whichSubTokens(strings.ToLower(scored[j].Entry.Command)))
	})
	// Drop zero-score matches when the query was non-empty; agents
	// branching on exit code rely on "no match" meaning no confidence.
	filtered := scored[:0]
	for _, m := range scored {
		if m.Score > 0 {
			filtered = append(filtered, m)
		}
	}
	if len(filtered) > limit {
		filtered = filtered[:limit]
	}
	return filtered
}

func whichScoreEntry(e whichEntry, query string, qTokens []string) int {
	score := 0
	cmd := strings.ToLower(e.Command)
	// Sub-token split (spaces, hyphens, underscores, slashes): a capability
	// word buried in a hyphenated leaf (repos-list-for-authenticated) must be
	// matchable by the words a human asks with, or every command in a group
	// ties on the group token alone and index order decides the answer.
	cmdTokens := whichSubTokens(cmd)
	commandParts := strings.Fields(cmd)
	leaf := ""
	if len(commandParts) > 0 {
		leaf = commandParts[len(commandParts)-1]
	}
	desc := strings.ToLower(e.Description)
	descTokens := whichSubTokens(desc)
	why := strings.ToLower(e.WhyItMatters)
	whyTokens := whichSubTokens(why)
	group := strings.ToLower(e.Group)

	// Exact token match on the command path (any token). Filler words
	// credit a command only when they are the whole unsplit leaf
	// ("run a" → "a"), not a hyphenated sub-token ("in" vs "check-in").
	for _, qt := range qTokens {
		if whichIncidentalToken(qt) && !whichTokenMatch(qt, leaf) {
			continue
		}
		for _, ct := range cmdTokens {
			if whichTokenMatch(qt, ct) {
				score += 3
				break
			}
		}
	}
	// Substring match on the full command (covers hyphenated leaves).
	// An incidental-only query must still name the whole command or leaf
	// so "in" does not admit "check-in" via the trailing fragment.
	if strings.Contains(cmd, query) {
		if !whichAllIncidental(qTokens) || whichTokenMatch(query, leaf) || whichTokenMatch(query, cmd) {
			score += 2
		}
	}
	// Description and rationale are correlated prose fields. Share the existing
	// per-token cap so repeating the same query in both fields cannot outweigh
	// an exact command match. A rationale-only match needs two tokens or an
	// exact multi-token phrase to avoid promoting incidental prose words.
	descPhrase := strings.Contains(desc, query)
	descCredit := whichFieldCredit(qTokens, descTokens)
	whyCredit := whichFieldCredit(qTokens, whyTokens)
	whyPhrase := len(qTokens) > 1 && strings.Contains(why, query)
	if score == 0 && whyCredit < 2 && !whyPhrase {
		whyCredit = 0
	}
	if descPhrase || whyPhrase {
		score += 2
	}
	if whyCredit > descCredit {
		score += whyCredit
	} else {
		score += descCredit
	}
	// Group tag match requires a whole token, not an arbitrary substring.
	// Filler words credit a group only when they are the whole group name.
	groupTokens := whichSubTokens(group)
	groupMatched := false
	for _, qt := range qTokens {
		if whichIncidentalToken(qt) && !whichTokenMatch(qt, group) {
			continue
		}
		for _, gt := range groupTokens {
			if whichTokenMatch(qt, gt) {
				score += 1
				groupMatched = true
				break
			}
		}
		if groupMatched {
			break
		}
	}
	// Possessive aliasing: "my/mine/me/current" in a request is API-speak for
	// the authenticated caller; commands scoped to the authenticated user must
	// outrank generic listings for possessive asks.
	possessive := false
	for _, qt := range qTokens {
		switch qt {
		case "my", "mine", "me", "current":
			possessive = true
		}
	}
	if possessive {
		for _, ct := range cmdTokens {
			if ct == "authenticated" || ct == "me" {
				score += 3
				break
			}
		}
	}
	// Read-intent default: penalize write-verb commands when the request never
	// asked for a write, so neutral asks can never rank a destructive command
	// first on a tie.
	if score > 0 {
		queryWrite := false
		for _, qt := range qTokens {
			if whichWriteVerbs[qt] {
				queryWrite = true
				break
			}
		}
		if !queryWrite {
			for _, ct := range cmdTokens {
				if whichWriteVerbs[ct] {
					score -= 2
					break
				}
			}
		}
	}
	// Specificity: a command leaf carrying capability sub-tokens the request never
	// used is a variant, not the canonical answer ("activity-list-repos-
	// starred-by-authenticated" for a repositories ask). Parent resource tokens
	// are excluded so a valid nested command is not erased by its path. A
	// single-token leaf has no variant to disambiguate; the penalty may still
	// down-rank it but must not zero a description/path hit by itself.
	if score > 0 && len(qTokens) > 1 {
		leafTokens := whichSubTokens(leaf)
		unmatched := 0
		for _, ct := range leafTokens {
			hit := false
			for _, qt := range qTokens {
				if whichTokenMatch(qt, ct) {
					hit = true
					break
				}
			}
			if !hit {
				unmatched++
			}
		}
		if unmatched > 3 {
			unmatched = 3
		}
		if len(leafTokens) < 2 && unmatched >= score {
			unmatched = score - 1
		}
		score -= unmatched
	}
	return score
}

func whichFieldCredit(qTokens, fieldTokens []string) int {
	credit := 0
	matched := make(map[string]struct{})
	for _, qt := range qTokens {
		if whichIncidentalToken(qt) {
			continue
		}
		for _, ft := range fieldTokens {
			if whichTokenMatch(qt, ft) {
				key := whichTokenKey(ft)
				if _, ok := matched[key]; ok {
					break
				}
				matched[key] = struct{}{}
				credit++
				break
			}
		}
		if credit == 3 {
			break
		}
	}
	return credit
}

func whichTokenKey(token string) string {
	token = strings.Trim(strings.ToLower(token), ".,:;!?()[]{}\"'")
	if alias := whichTokenAliases[token]; alias != "" {
		return alias
	}
	return whichSingular(token)
}

func whichTokenMatch(a, b string) bool {
	a = strings.Trim(strings.ToLower(a), ".,:;!?()[]{}\"'")
	b = strings.Trim(strings.ToLower(b), ".,:;!?()[]{}\"'")
	if a == "" || b == "" {
		return false
	}
	if a == b {
		return true
	}
	if whichSingular(a) == whichSingular(b) {
		return true
	}
	return whichTokenAliases[a] != "" && whichTokenAliases[a] == whichTokenAliases[b]
}

func whichSubTokens(cmd string) []string {
	return strings.FieldsFunc(cmd, func(r rune) bool {
		return r == ' ' || r == '-' || r == '_' || r == '/'
	})
}

func whichIncidentalToken(token string) bool {
	token = strings.Trim(strings.ToLower(token), ".,:;!?()[]{}\"'")
	if token == "" {
		return true
	}
	return whichIncidentalTokens[token]
}

func whichAllIncidental(qTokens []string) bool {
	if len(qTokens) == 0 {
		return false
	}
	for _, qt := range qTokens {
		if !whichIncidentalToken(qt) {
			return false
		}
	}
	return true
}

// The closed API-verb set for write-shaped commands. A request that never
// asked for a write must not tie-break into a destructive command.
var whichWriteVerbs = map[string]bool{
	"delete": true, "remove": true, "update": true, "create": true, "set": true,
	"add": true, "replace": true, "rename": true, "transfer": true, "merge": true,
	"lock": true, "unlock": true, "star": true, "unstar": true, "follow": true,
	"unfollow": true, "block": true, "unblock": true, "mute": true, "archive": true,
	"unarchive": true, "cancel": true, "send": true, "upload": true, "subscribe": true,
	"unsubscribe": true, "dismiss": true, "approve": true, "decline": true,
	"post": true, "put": true, "write": true, "edit": true, "modify": true,
	"publish": true, "share": true, "comment": true, "grant": true, "revoke": true,
}

var whichTokenAliases = map[string]string{
	"repo": "repository", "repos": "repository", "repository": "repository", "repositories": "repository",
}

// Filler words that must not create a which match by themselves. Possessive
// aliases (my/mine/me/current) stay significant so authenticated-scoped
// commands can still outrank generic listings.
var whichIncidentalTokens = map[string]bool{
	"a": true, "an": true, "the": true, "i": true,
	"is": true, "are": true, "was": true, "were": true, "be": true, "been": true, "being": true,
	"of": true, "to": true, "in": true, "on": true, "at": true, "for": true, "with": true, "from": true, "by": true, "about": true,
	"what": true, "which": true, "who": true, "whom": true, "whose": true, "how": true, "when": true, "why": true, "where": true,
	"will": true, "would": true, "could": true, "should": true, "may": true, "might": true, "can": true, "shall": true,
	"do": true, "does": true, "did": true, "have": true, "has": true, "had": true,
	"and": true, "or": true, "but": true, "if": true, "then": true, "than": true,
	"this": true, "that": true, "these": true, "those": true, "it": true, "its": true,
}

func whichSingular(s string) string {
	if len(s) > 3 && strings.HasSuffix(s, "ies") {
		return strings.TrimSuffix(s, "ies") + "y"
	}
	if len(s) > 3 && strings.HasSuffix(s, "es") {
		return strings.TrimSuffix(s, "es")
	}
	if len(s) > 2 && strings.HasSuffix(s, "s") {
		return strings.TrimSuffix(s, "s")
	}
	return s
}

func newWhichCmd(flags *rootFlags) *cobra.Command {
	var limit int
	cmd := &cobra.Command{
		Use:   "which [query]",
		Short: "Find the command that implements a capability",
		Annotations: map[string]string{
			"mcp:read-only":       "true",
			"pp:typed-exit-codes": "0,2",
		},
		Long: `which resolves a natural-language capability query (for example, "search messages" or "stale tickets") to the best matching command from this CLI's curated feature index.

Exit codes:
  0  at least one match found
  2  no confident match - the query did not score against any indexed capability; fall back to '--help' or 'search' if this CLI has one. Machine output (--json/--csv/--plain/--quiet, or a pipe) still exits 2 and writes {"matches":[]} (or the equivalent empty table) to stdout.`,
		SilenceUsage: true,
		Example: `  hubspot-cli which "stale tickets"
  hubspot-cli which "bottleneck"
  hubspot-cli which --limit 1 "send message"
  hubspot-cli which                                # list the full capability index`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(whichIndex) == 0 {
				return usageErr(fmt.Errorf("this CLI has no curated capability index; run '--help' to see every command"))
			}
			query := strings.Join(args, " ")
			matches := rankWhich(whichIndex, query, limit)

			// Empty query returns the whole index at score 0 (listing mode).
			if strings.TrimSpace(query) == "" {
				return renderWhich(cmd, flags, rankWhichAll(whichIndex))
			}

			if len(matches) == 0 {
				// Machine output still uses the typed exit-2 no-match path.
				// --json (and piped auto-JSON) emit {"matches":[]} on stdout
				// so agents can branch on the envelope without treating exit 0
				// as success. Human terminals keep the usage error only.
				asJSON := flags.asJSON
				if !asJSON && !isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain {
					asJSON = true
				}
				if asJSON || flags.csv || flags.plain || flags.quiet {
					outputFlags := *flags
					outputFlags.asJSON = asJSON || flags.asJSON
					if err := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"matches": []whichMatch{},
					}, &outputFlags); err != nil {
						return err
					}
				}
				return usageErr(fmt.Errorf("no match for %q; try '%s --help' for the full command list", query, cmd.Root().Name()))
			}
			return renderWhich(cmd, flags, matches)
		},
	}
	cmd.Flags().IntVar(&limit, "limit", 3, "Maximum number of matches to return")
	return cmd
}

// rankWhichAll is a narrow helper used by the "empty query lists the
// index" path. It returns every entry in declaration order at score 0
// so the render path treats them uniformly.
func rankWhichAll(index []whichEntry) []whichMatch {
	out := make([]whichMatch, 0, len(index))
	for _, e := range index {
		out = append(out, whichMatch{Entry: e, Score: 0})
	}
	return out
}

func renderWhich(cmd *cobra.Command, flags *rootFlags, matches []whichMatch) error {
	w := cmd.OutOrStdout()
	// Output shape follows the same rule as every other generated
	// command: JSON when the caller asked for it OR when stdout is not
	// a terminal; table when a human is looking.
	asJSON := flags.asJSON
	if !asJSON && !isTerminal(w) {
		asJSON = true
	}
	if asJSON {
		// JSON envelope: {matches: [...]}. The wrap is critical:
		// printJSONFiltered's --compact path uses compactListFields
		// (allowlist) for top-level arrays, which would strip
		// entry/score keys; routing through compactObjectFields
		// (blocklist) via an object envelope preserves them.
		if matches == nil {
			matches = []whichMatch{}
		}
		return printJSONFiltered(w, map[string]any{"matches": matches}, flags)
	}
	fmt.Fprintf(w, "%-24s  %-8s  %s\n", "COMMAND", "SCORE", "DESCRIPTION")
	for _, m := range matches {
		fmt.Fprintf(w, "%-24s  %-8d  %s\n", m.Entry.Command, m.Score, m.Entry.Description)
	}
	return nil
}
