// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// Package mcp — intent handlers.
//
// Intents are higher-level MCP tools that compose multiple endpoint calls
// or expose curated recipe commands with useful flag defaults.
// Rather than forcing an agent to stitch primitives like get_thread +
// create_issue + link_attachment, a single create_issue_from_thread tool
// accepts the top-level input, calls each endpoint in sequence, resolves
// bindings between steps, and returns the final captured value.
//
// Each intent is emitted as a handler registered alongside (or in place of,
// when MCP.EndpointTools == "hidden") the raw endpoint-mirror tools.

package mcp

import (
	"context"
	"fmt"
	"strings"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"sentinelone-pp-cli/internal/mcp/cobratree"
)

// RegisterIntents adds generated intent tools to the MCP server.
// This is called from RegisterTools when spec intents or recipe-lifted intents exist.
func RegisterIntents(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("trace_a_threat_across_the_fleet",
			mcplib.WithDescription("Every endpoint a hash touched, mitigated vs active, with a spread timeline."),
			mcplib.WithString("slug", mcplib.Required(), mcplib.Description("Override the recipe's positional slug value.")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		handleTraceAThreatAcrossTheFleet,
	)
}

// handleTraceAThreatAcrossTheFleet runs the trace_a_threat_across_the_fleet recipe intent: Every endpoint a hash touched, mitigated vs active, with a spread timeline.
func handleTraceAThreatAcrossTheFleet(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	if recipeCLIPathErr != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("companion CLI binary not found: %v", recipeCLIPathErr)), nil
	}

	input := req.GetArguments()
	args := []string{}
	args = append(args, "threats")
	var missingSlug bool
	args, missingSlug = appendRecipePositional(args, input["slug"], true)
	if missingSlug {
		return mcplib.NewToolResultError("slug is required"), nil
	}
	args = append(args, "3f5a9c2e1b7d8a4f6c0e2d1a9b8c7f6e5d4c3b2a")
	args = append(args, "--agent")

	out, err := cobratree.RunCLICommand(ctx, recipeCLIPath, args)
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	return cobratree.ToolResultFromCLICommand(out), nil
}

var (
	recipeCLIPath    string
	recipeCLIPathErr error
)

func init() {
	recipeCLIPath, recipeCLIPathErr = cobratree.SiblingCLIPath()
}

func appendRecipePositional(args []string, value any, required bool) ([]string, bool) {
	selected := recipeValueString(value)
	if selected == "" {
		return args, required
	}
	return append(args, selected), false
}

func appendRecipeStringFlag(args []string, name string, value any, defaultValue string, required bool, useEquals bool) ([]string, bool) {
	selected := defaultValue
	if value != nil {
		selected = recipeValueString(value)
	}
	if selected == "" {
		return args, required
	}
	if useEquals {
		return append(args, "--"+name+"="+selected), false
	}
	return append(args, "--"+name, selected), false
}

func appendRecipeBoolFlag(args []string, name string, value any, defaultValue bool) []string {
	selected := defaultValue
	if v, ok := value.(bool); ok {
		selected = v
	}
	if selected {
		return append(args, "--"+name)
	}
	return args
}

func recipeValueString(value any) string {
	switch v := value.(type) {
	case string:
		return strings.TrimSpace(v)
	case float64:
		return formatMCPParamValue(v)
	case bool:
		if v {
			return "true"
		}
		return "false"
	default:
		if value == nil {
			return ""
		}
		return fmt.Sprintf("%v", value)
	}
}
