// Copyright 2026 Servosity Inc. and msp-skills contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"modernc.org/sqlite"
	sqlite3 "modernc.org/sqlite/lib"
	"sentinelone-pp-cli/internal/cli"
	"sentinelone-pp-cli/internal/client"
	"sentinelone-pp-cli/internal/cliutil"
	"sentinelone-pp-cli/internal/config"
	"sentinelone-pp-cli/internal/learn"
	"sentinelone-pp-cli/internal/mcp/bound"
	"sentinelone-pp-cli/internal/mcp/cobratree"
	"sentinelone-pp-cli/internal/platform"
	"sentinelone-pp-cli/internal/store"
)

const (
	// MCP hosts can fan out tool calls faster than a human CLI session.
	// Keep them on the same polite-client limiter path instead of disabling
	// pacing with rate=0; users can still tune human CLI calls with --rate-limit.
	defaultMCPRateLimit = 2
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	installFreshTenantGate(s)
	// Code-orchestration mode — the full surface is covered by registry tools
	// (<api>_search, <api>_get, and <api>_execute). Endpoint-mirror tools are suppressed.
	RegisterCodeOrchestrationTools(s)
	// Intent tools — higher-level compositions declared in the spec or lifted from recipes.
	RegisterIntents(s)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Synced records live in resources(resource_type, id, data); filter by resource_type and use json_extract on data, e.g. SELECT json_extract(data,'$.name') FROM resources WHERE resource_type='accounts'.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext(s),
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

type mcpPageConfig struct {
	CursorParam    string
	NextCursorPath string
}

func formatMCPParamValue(v any) string {
	switch tv := v.(type) {
	case string:
		return tv
	case bool:
		return strconv.FormatBool(tv)
	case float64:
		if math.IsNaN(tv) || math.IsInf(tv, 0) {
			return strconv.FormatFloat(tv, 'f', -1, 64)
		}
		if math.Trunc(tv) == tv && math.Abs(tv) < 1e15 {
			return strconv.FormatInt(int64(tv), 10)
		}
		return strconv.FormatFloat(tv, 'f', -1, 64)
	case float32:
		f := float64(tv)
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return strconv.FormatFloat(f, 'f', -1, 32)
		}
		if math.Trunc(f) == f && math.Abs(f) < 1e15 {
			return strconv.FormatInt(int64(f), 10)
		}
		return strconv.FormatFloat(f, 'f', -1, 32)
	default:
		// Composite values (a native []any / map[string]any from an array or
		// object param) reach this path when bound to a query or path slot;
		// JSON-encode them so the wire value is valid JSON rather than Go's
		// "[a b c]" / "map[...]" rendering. Body params never come through
		// here — they are stored natively in bodyArgs and marshalled there.
		if b, err := json.Marshal(v); err == nil {
			return string(b)
		}
		return fmt.Sprintf("%v", v)
	}
}

func mcpPathValue(v any) string {
	return cliutil.EscapePathParam(formatMCPParamValue(v))
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, pageConfig mcpPageConfig, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, platformSession, err := newMCPClient(ctx)
		if err != nil {
			return mcpToolError(err.Error()), nil
		}
		if platformSession != nil {
			defer platformSession.ZeroCredentials()
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()
		if err := cli.AdoptMCPOutputSemantics(platformSession, args); err != nil {
			return mcpToolError(err.Error()), nil
		}

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		mcpCursor := ""
		if pageConfig.CursorParam != "" {
			knownArgs["cursor"] = true
			if v, ok := args["cursor"]; ok {
				s, ok := v.(string)
				if !ok {
					return mcpToolError("cursor must be an opaque string returned by a previous MCP response"), nil
				}
				mcpCursor = s
				upstreamCursor, err := bound.UpstreamCursor(s)
				if err != nil {
					return mcpToolError(err.Error()), nil
				}
				if upstreamCursor != "" {
					params[pageConfig.CursorParam] = upstreamCursor
				}
			}
		}
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, mcpPathValue(v), 1)
			case "header":
				if headers == nil {
					headers = map[string]string{}
				}
				headers[binding.WireName] = formatMCPParamValue(v)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = formatMCPParamValue(v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, mcpPathValue(v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = formatMCPParamValue(v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				if readOnly {
					data, err = c.GetWithHeaders(ctx, path, params, headers)
				} else {
					data, err = c.GetMutatingWithHeaders(ctx, path, params, headers)
				}
				break
			}
			if readOnly {
				data, err = c.Get(ctx, path, params)
			} else {
				data, err = c.GetMutating(ctx, path, params)
			}
		case "POST":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PutQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PutQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
			}
		case "PATCH":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PatchQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PatchQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
			}
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcpToolError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcpToolTextWithPlatform("already exists (no-op)", platformSession), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcpToolError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key with: export SENTINELONE_API_TOKEN=\"your-token-here\"" +
					"\n      See API docs: https://twitter.com/frikkylikeme" +
					"\n      Run 'sentinelone-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcpToolError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your API key." +
					"\n      Set your API key with: export SENTINELONE_API_TOKEN=\"your-token-here\"" +
					"\n      See API docs: https://twitter.com/frikkylikeme" +
					"\n      Run 'sentinelone-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcpToolError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource. Check that they have the required permissions and match the API's expected auth scheme." +
					"\n      Set your API key with: export SENTINELONE_API_TOKEN=\"your-token-here\"" +
					"\n      See API docs: https://twitter.com/frikkylikeme" +
					"\n      Run 'sentinelone-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcpToolTextWithPlatform("already deleted (no-op)", platformSession), nil
				}
				return mcpToolError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcpToolError("rate limited: " + msg), nil
			default:
				return mcpToolError(msg), nil
			}
		}

		if binaryResponse {
			encoded := base64.StdEncoding.EncodeToString(data)
			out, err := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      encoded,
				"byte_count":       len(data),
			})
			if err != nil {
				return mcpToolError(fmt.Sprintf("encoding binary result: %v", err)), nil
			}
			if len(out) > bound.MaxBytes {
				return mcpToolError(fmt.Sprintf("binary response is too large for MCP text output: %d response bytes encode to %d base64 bytes and %d MCP result bytes, exceeding the %d byte budget. Use the companion CLI command with --output <file> to save the payload locally.", len(data), len(encoded), len(out), bound.MaxBytes)), nil
			}
			result := string(out)
			if platformSession != nil {
				result = bound.WithMetadata(result, platformSession.OutputMetadata())
			}
			return mcplib.NewToolResultText(result), nil
		}
		if pageConfig.CursorParam != "" {
			return mcpToolPageResultTextWithPlatform(method, data, pageConfig, mcpCursor, platformSession), nil
		}
		return mcpToolResultTextWithPlatform(method, data, platformSession), nil
	}
}

func mcpToolResultText(method string, data json.RawMessage) *mcplib.CallToolResult {
	return mcpToolResultTextWithPlatform(method, data, nil)
}

func mcpToolTextWithPlatform(result string, platformSession *platform.Session) *mcplib.CallToolResult {
	if platformSession != nil {
		result = bound.WithMetadata(result, platformSession.OutputMetadata())
	}
	return mcplib.NewToolResultText(result)
}

func mcpToolResultTextWithPlatform(method string, data json.RawMessage, platformSession *platform.Session) *mcplib.CallToolResult {
	result := bound.EndpointResponse(method, data)
	return mcpToolTextWithPlatform(result, platformSession)
}

// mcpToolError keeps provider-controlled typed endpoint errors within the MCP
// text-result budget just like successful endpoint results.
func mcpToolError(message string) *mcplib.CallToolResult {
	return mcplib.NewToolResultError(bound.Text(message))
}

func mcpToolPageResultText(method string, data json.RawMessage, pageConfig mcpPageConfig, cursor string) *mcplib.CallToolResult {
	return mcpToolPageResultTextWithPlatform(method, data, pageConfig, cursor, nil)
}

func mcpToolPageResultTextWithPlatform(method string, data json.RawMessage, pageConfig mcpPageConfig, cursor string, platformSession *platform.Session) *mcplib.CallToolResult {
	result := bound.EndpointPageResponse(method, data, bound.PageOptions{
		Cursor:         cursor,
		CursorParam:    pageConfig.CursorParam,
		NextCursorPath: pageConfig.NextCursorPath,
	})
	if platformSession != nil {
		result = bound.WithMetadata(result, platformSession.OutputMetadata())
	}
	return mcplib.NewToolResultText(result)
}

func newMCPClient(ctx context.Context) (*client.Client, *platform.Session, error) {
	cfg, err := newMCPConfig()
	if err != nil {
		return nil, nil, err
	}
	return newMCPClientFromConfig(ctx, cfg)
}

func newMCPConfig() (*config.Config, error) {
	cfg, err := config.Load("")
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	return cfg, nil
}

func newMCPClientFromConfig(ctx context.Context, cfg *config.Config) (*client.Client, *platform.Session, error) {
	c := client.New(cfg, 60*time.Second, defaultMCPRateLimit)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	session, err := cli.BindMCPClient(ctx, c)
	if err != nil {
		return nil, nil, err
	}
	if err := cli.ApplyClientHooks(c); err != nil {
		if session != nil {
			session.ZeroCredentials()
		}
		return nil, nil, fmt.Errorf("initializing MCP client: %w", err)
	}
	return c, session, nil
}

func mcpDBPath() (string, error) {
	dir, err := cliutil.DataDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "data.db"), nil
}

type mcpStoreStatusKind string

const (
	mcpStoreStatusEmpty   mcpStoreStatusKind = "empty"
	mcpStoreStatusPartial mcpStoreStatusKind = "partial"
	mcpStoreStatusReady   mcpStoreStatusKind = "ready"
)

func openMCPReadOnlyStore(path string) (*store.Store, *mcplib.CallToolResult) {
	if _, err := os.Stat(path); err != nil {
		if os.IsNotExist(err) {
			return nil, mcplib.NewToolResultError(mcpMissingStoreMessage(path))
		}
		return nil, mcplib.NewToolResultError(fmt.Sprintf("checking local data store %s: %v", path, err))
	}
	db, err := store.OpenReadOnly(path)
	if err != nil {
		return nil, mcplib.NewToolResultError(fmt.Sprintf("opening local data store %s: %v. Run sentinelone-cli sync to refresh the store, or use live endpoint MCP tools for unsynced data.", path, err))
	}
	return db, nil
}

func mcpMissingStoreMessage(path string) string {
	return fmt.Sprintf("No local data store found at %s. Run sentinelone-cli sync before using MCP search/sql, or use live endpoint MCP tools for unsynced data.", path)
}

func mcpStoreStatus(db *store.Store) (mcpStoreStatusKind, error) {
	status, err := db.Status()
	if err != nil {
		return "", err
	}
	var checkpoints, completed int
	err = db.DB().QueryRow(`SELECT COUNT(*), COALESCE(SUM(CASE WHEN last_attempt_complete = 1 THEN 1 ELSE 0 END), 0) FROM sync_state`).Scan(&checkpoints, &completed)
	if err != nil && strings.Contains(strings.ToLower(err.Error()), "no such column: last_attempt_complete") {
		// Read-only stores have not run the conservative completion migration.
		// Legacy timestamps were also written by partial walks, so prove nothing.
		err = db.DB().QueryRow(`SELECT COUNT(*), 0 FROM sync_state`).Scan(&checkpoints, &completed)
	}
	if err != nil {
		msg := strings.ToLower(err.Error())
		if strings.Contains(msg, "no such table") || strings.Contains(msg, "no such column") {
			if len(status) > 0 {
				return mcpStoreStatusReady, nil
			}
			return mcpStoreStatusEmpty, nil
		}
		return "", err
	}
	if checkpoints > 0 {
		if completed == checkpoints {
			return mcpStoreStatusReady, nil
		}
		return mcpStoreStatusPartial, nil
	}
	if len(status) > 0 {
		return mcpStoreStatusReady, nil
	}
	return mcpStoreStatusEmpty, nil
}

func mcpEmptyStoreNextStep() string {
	return "Run sentinelone-cli sync to populate the local SQLite store before using MCP search/sql."
}

func mcpPartialStoreNextStep() string {
	return "The latest sync attempt is incomplete. Resume or rerun sentinelone-cli sync before treating local search/sql results as a complete snapshot."
}

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	path, err := mcpDBPath()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("resolving database: %v", err)), nil
	}
	db, toolErr := openMCPReadOnlyStore(path)
	if toolErr != nil {
		return toolErr, nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}
	storeStatus, err := mcpStoreStatus(db)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading store status: %v", err)), nil
	}

	return toolResultJSON(mcpSearchEnvelope(results, storeStatus))
}

func mcpSearchEnvelope(results []json.RawMessage, storeStatus mcpStoreStatusKind) map[string]any {
	if results == nil {
		results = []json.RawMessage{}
	}
	out := map[string]any{
		"count":        len(results),
		"results":      results,
		"store_status": storeStatus,
		"resumable":    false,
	}
	if storeStatus == mcpStoreStatusPartial {
		out["warning"] = "Local data may be incomplete because the latest sync attempt did not finish."
		out["next_step"] = mcpPartialStoreNextStep()
	} else if len(results) == 0 {
		if storeStatus == mcpStoreStatusEmpty {
			out["next_step"] = mcpEmptyStoreNextStep()
		} else {
			out["next_step"] = "No local search matches. Try a broader query, a lower-specificity FTS expression, or sync again if data may be stale."
		}
	}
	return out
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate rejects multi-statement input, then applies an allowlist (SELECT or
// WITH only) AFTER stripping the leading whitespace, line comments, block
// comments, and semicolons that SQLite itself ignores before parsing. A naive
// HasPrefix check on a keyword blocklist is bypassable by prefixing the
// dangerous statement with "/* x */" or "-- x\n"; a naive leading-keyword
// allowlist is bypassable by appending "; ATTACH DATABASE ...". Combined with
// the empirical fact that modernc.org/sqlite's mode=ro does NOT block VACUUM
// INTO (writes a snapshot to a new file) or ATTACH DATABASE (opens a separate
// writable handle), either bypass produces silent exfiltration to an
// attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	stripped := stripLeadingSQLNoise(query)
	if hasTrailingSQLStatement(stripped) {
		return fmt.Errorf("only a single SELECT or WITH statement is allowed")
	}
	upper := strings.ToUpper(stripped)
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

// hasTrailingSQLStatement reports whether query contains a statement
// terminator followed by more executable SQL. A trailing semicolon is allowed;
// a second statement is not. Semicolons inside string literals, quoted
// identifiers, bracket identifiers, and comments are ignored to match SQLite's
// parser shape closely enough for this security gate.
func hasTrailingSQLStatement(query string) bool {
	inSingle := false
	inDouble := false
	inBacktick := false
	inBracket := false
	inLineComment := false
	inBlockComment := false

	for i := 0; i < len(query); i++ {
		ch := query[i]
		next := byte(0)
		if i+1 < len(query) {
			next = query[i+1]
		}

		switch {
		case inLineComment:
			if ch == '\n' {
				inLineComment = false
			}
			continue
		case inBlockComment:
			if ch == '*' && next == '/' {
				inBlockComment = false
				i++
			}
			continue
		case inSingle:
			if ch == '\'' {
				if next == '\'' {
					i++
					continue
				}
				inSingle = false
			}
			continue
		case inDouble:
			if ch == '"' {
				if next == '"' {
					i++
					continue
				}
				inDouble = false
			}
			continue
		case inBacktick:
			if ch == '`' {
				if next == '`' {
					i++
					continue
				}
				inBacktick = false
			}
			continue
		case inBracket:
			if ch == ']' {
				inBracket = false
			}
			continue
		}

		switch {
		case ch == '-' && next == '-':
			inLineComment = true
			i++
		case ch == '/' && next == '*':
			inBlockComment = true
			i++
		case ch == '\'':
			inSingle = true
		case ch == '"':
			inDouble = true
		case ch == '`':
			inBacktick = true
		case ch == '[':
			inBracket = true
		case ch == ';':
			if stripLeadingSQLNoise(query[i+1:]) != "" {
				return true
			}
			return false
		}
	}
	return false
}

const mcpSQLMaxValueBytes = 4 << 20

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	path, err := mcpDBPath()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("resolving database: %v", err)), nil
	}
	db, toolErr := openMCPReadOnlyStore(path)
	if toolErr != nil {
		return toolErr, nil
	}
	defer db.Close()

	queryCtx, cancel := bound.WithSQLQueryDeadline(ctx)
	defer cancel()

	conn, err := db.DB().Conn(queryCtx)
	if err != nil {
		return mcplib.NewToolResultError(mcpSQLQueryError(queryCtx, err)), nil
	}
	defer conn.Close()

	if _, err := sqlite.Limit(conn, sqlite3.SQLITE_LIMIT_LENGTH, mcpSQLMaxValueBytes); err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("setting SQL value length cap: %v", err)), nil
	}

	rows, err := conn.QueryContext(queryCtx, query)
	if err != nil {
		return mcplib.NewToolResultError(mcpSQLQueryError(queryCtx, err)), nil
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading columns: %v", err)), nil
	}
	scan := bound.NewSQLScanState(cols)
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			if mcpSQLValueTooBig(err) {
				return mcplib.NewToolResultError(mcpSQLQueryError(queryCtx, err)), nil
			}
			return mcplib.NewToolResultError(fmt.Sprintf("scanning row: %v", err)), nil
		}
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		if !scan.Add(row) {
			break
		}
	}
	// rows.Next() stops on a mid-iteration error without failing the loop, so
	// skipping rows.Err() would return a truncated result set as success.
	if err := rows.Err(); err != nil {
		return mcplib.NewToolResultError(mcpSQLQueryError(queryCtx, err)), nil
	}
	storeStatus, err := mcpStoreStatus(db)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading store status: %v", err)), nil
	}

	return toolResultJSON(mcpSQLEnvelope(scan.Rows, cols, storeStatus, scan.Truncated))
}

func mcpSQLEnvelope(rows []map[string]any, columns []string, storeStatus mcpStoreStatusKind, truncated bool) map[string]any {
	if rows == nil {
		rows = []map[string]any{}
	}
	out := map[string]any{
		"count":        len(rows),
		"columns":      columns,
		"rows":         rows,
		"store_status": storeStatus,
		"resumable":    false,
		"truncated":    truncated,
	}
	if truncated {
		out["returned_count"] = len(rows)
		out["max_bytes"] = bound.MaxBytes
		out["note"] = bound.SQLResultBoundNote
	}
	if storeStatus == mcpStoreStatusPartial {
		out["warning"] = "Local data may be incomplete because the latest sync attempt did not finish."
		out["next_step"] = mcpPartialStoreNextStep()
	} else if len(rows) == 0 && !truncated {
		if storeStatus == mcpStoreStatusEmpty {
			out["next_step"] = mcpEmptyStoreNextStep()
		} else {
			out["next_step"] = "The read-only SQL query returned no rows. Check resource_type filters, json_extract paths, or run sync again if data may be stale."
		}
	}
	return out
}

func mcpSQLQueryError(queryCtx context.Context, err error) string {
	if queryCtx.Err() != nil {
		return fmt.Sprintf("query cancelled: %v. MCP SQL queries are bounded to %s; narrow the query with WHERE, GROUP BY, or an aggregate.", err, bound.SQLQueryTimeout)
	}
	if mcpSQLValueTooBig(err) {
		return fmt.Sprintf("query failed: a string or blob exceeds the MCP SQL value cap of %d bytes (4 MiB). Narrow the selected columns or use substr, json_extract, or length instead of returning oversized values.", mcpSQLMaxValueBytes)
	}
	msg := err.Error()
	if strings.Contains(strings.ToLower(msg), "no such table") {
		return fmt.Sprintf("query failed: %v. Synced records live in resources(resource_type, id, data), not one SQL table per resource. Filter by resource_type, for example resource_type='accounts', and read JSON fields with json_extract(data,'$.field').", err)
	}
	return fmt.Sprintf("query failed: %v", err)
}

func mcpSQLValueTooBig(err error) bool {
	var sqliteErr *sqlite.Error
	return errors.As(err, &sqliteErr) && sqliteErr.Code() == sqlite3.SQLITE_TOOBIG
}

// toolResultJSON renders v as the indented JSON body of an MCP text result,
// surfacing a marshal failure as a tool error instead of empty content.
func toolResultJSON(v any) (*mcplib.CallToolResult, error) {
	text, err := bound.JSON(v)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding result: %v", err)), nil
	}
	return mcplib.NewToolResultText(text), nil
}
func registeredCommandMirrorCapabilities(s *server.MCPServer, capabilities []map[string]string) []map[string]string {
	registered := make([]map[string]string, 0, len(capabilities))
	root := cli.RootCmd()
	for _, capability := range capabilities {
		toolName := cobratree.ToolNameForCommand(s, root, capability["cli_command"])
		if toolName == "" {
			continue
		}
		entry := s.GetTool(toolName)
		if entry == nil || entry.Tool.Meta == nil || entry.Tool.Meta.AdditionalFields["pp:tenant-gate"] != "child-cli" {
			continue
		}
		capability["mcp_tool"] = toolName
		registered = append(registered, capability)
	}
	return registered
}

func handleContext(s *server.MCPServer) func(context.Context, mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		return handleContextResult(s, ctx, req)
	}
}

func handleContextResult(s *server.MCPServer, _ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	paths := map[string]string{}
	if dir, err := cliutil.ConfigDir(); err == nil {
		paths["config_dir"] = dir
	}
	if dir, err := cliutil.DataDir(); err == nil {
		paths["data_dir"] = dir
	}
	if dir, err := cliutil.StateDir(); err == nil {
		paths["state_dir"] = dir
	}
	if dir, err := cliutil.CacheDir(); err == nil {
		paths["cache_dir"] = dir
	}
	ctx := map[string]any{
		"api":         "sentinelone",
		"description": "Every SentinelOne v2.1 management endpoint, plus an offline SQLite store and cross-entity analytics — fleet health, threat triage, blast radius, drift — that no console view offers.",
		"archetype":   "project-management",
		"tool_count":  len(s.ListTools()),
		"paths":       paths,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion sentinelone-cli binary.",
		// learn_protocol is generated from the single shared source of
		// truth (the exported constant internal/learn.RecallFirstProtocol)
		// also consumed by the CLI agent-context command, so the MCP and
		// CLI agent surfaces cannot drift.
		"learn_protocol": learn.RecallFirstProtocol,
		"auth": map[string]any{
			"type": "api_key",
			"env_vars": []map[string]any{
				{
					"name":        "SENTINELONE_API_TOKEN",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
			"docs_url": "https://twitter.com/frikkylikeme",
		},
		"resources": []map[string]any{
			{
				"name":        "accounts",
				"description": "accounts operations",
				"endpoints":   []string{"create", "get", "get-by-id", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "accounts.expire-now",
				"description": "Manage expire now",
				"endpoints":   []string{"expire-an-account"},
				"writable":    true,
			},
			{
				"name":        "accounts.policy",
				"description": "Manage policy",
				"endpoints":   []string{"account", "update-account"},
				"writable":    true,
			},
			{
				"name":        "accounts.reactivate",
				"description": "Manage reactivate",
				"endpoints":   []string{"account"},
				"writable":    true,
			},
			{
				"name":        "accounts.revert-policy",
				"description": "Manage revert policy",
				"endpoints":   []string{"revert_policy"},
				"writable":    true,
			},
			{
				"name":        "accounts.uninstall-password",
				"description": "Manage uninstall password",
				"endpoints":   []string{"generate-regenerate", "get", "get-metadata", "revoke"},
				"writable":    true,
			},
			{
				"name":        "activities",
				"description": "activities operations",
				"endpoints":   []string{"get", "get-activity-types"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "agents",
				"description": "agents operations",
				"endpoints":   []string{"abort-scan", "approve-uninstall", "broadcast-message", "can-run-remote-shell", "clear-remote-shell", "connect-to-network", "count", "decommission", "disable", "disable-ranger", "disconnect-from-network", "enable", "enable-ranger", "fetch-firewall-logs", "fetch-firewall-rules", "fetch-logs", "get", "get-application", "get-installed-apps-for", "get-passphrase", "initiate-scan", "mark-as-uptodate", "move-between-sites", "move-to-console", "processes", "randomize-uuid", "reject-uninstall", "reset-local-config", "restart", "set-external-id", "set-persistent-configuration-overrides", "shutdown", "start-remote-profiling", "start-remote-shell", "stop-remote-profiling", "terminate-remote-shell", "uninstall", "update-software"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "agents.actions",
				"description": "Manage actions",
				"endpoints":   []string{"fetch-files"},
			},
			{
				"name":        "agents.uploads",
				"description": "upload operations",
				"endpoints":   []string{"export-agent-logs"},
			},
			{
				"name":        "application-inventory",
				"description": "application-inventory operations",
				"endpoints":   []string{"grouped-app-inventory"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "application-inventory-counts",
				"description": "application-inventory-counts operations",
				"endpoints":   []string{"counters"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "applications",
				"description": "applications operations",
				"endpoints":   []string{},
			},
			{
				"name":        "applications.forensics",
				"description": "Manage forensics",
				"endpoints":   []string{"application", "application-connections", "application-detailed", "export-application"},
			},
			{
				"name":        "cloud-detection",
				"description": "cloud-detection operations",
				"endpoints":   []string{"activate-rules", "create-rule", "delete-rules", "disable-rules", "get-alerts", "get-rules", "update-alert-analyst-verdict", "update-rule", "updated-threat-incident"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "config-override",
				"description": "config-override operations",
				"endpoints":   []string{"create", "delete", "delete-configoverride", "get", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "device-control",
				"description": "device-control operations",
				"endpoints":   []string{"copy-rules", "create-rule", "delete-rules", "enable-disable-rules", "export-rules", "get-configuration", "get-device-rules", "get-events", "import-rules", "move-rules", "reorder-rules", "update-configuration", "update-device-rule"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "dv",
				"description": "dv operations",
				"endpoints":   []string{"cancel-running-query", "create-query-and-get-query-id", "download-source-process-file", "get-events", "get-events-by-type", "get-process-state", "get-query-status"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "exclusions",
				"description": "exclusions operations",
				"endpoints":   []string{"create", "delete", "get", "update", "validate-item"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "filters",
				"description": "filters operations",
				"endpoints":   []string{"delete", "delete-deep-visibility", "get", "get-deep-visibility", "save", "save-deep-visibility", "update", "update-deep-visibility"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "firewall-control",
				"description": "firewall-control operations",
				"endpoints":   []string{"add-rule-tags", "copy-rules", "create-firewall-rule", "create-firewall-rule-by-category", "delete-rules", "delete-rules-by-category", "enable-disable-rules", "export-rules", "get-configuration", "get-firewall-rules", "get-firewall-rules-by-category", "get-protocols", "get-tag-firewall-rules", "import-rules", "move-rules", "remove-rule-tags", "reorder-rules", "set-location", "update-configuration", "update-firewall-rule-by-category"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "firewall-control.add-tags",
				"description": "Manage add tags",
				"endpoints":   []string{"add-rule-tags-by-category"},
				"writable":    true,
			},
			{
				"name":        "firewall-control.configuration",
				"description": "Manage configuration",
				"endpoints":   []string{"get-by-category", "update-by-category"},
				"writable":    true,
			},
			{
				"name":        "firewall-control.copy-rules",
				"description": "Manage copy rules",
				"endpoints":   []string{"by-category"},
				"writable":    true,
			},
			{
				"name":        "firewall-control.enable",
				"description": "Manage enable",
				"endpoints":   []string{"disable-rules-by-category"},
				"writable":    true,
			},
			{
				"name":        "firewall-control.export",
				"description": "export operations",
				"endpoints":   []string{"rules-by-category"},
			},
			{
				"name":        "firewall-control.import",
				"description": "Manage import",
				"endpoints":   []string{"rules-by-category"},
				"writable":    true,
			},
			{
				"name":        "firewall-control.move-rules",
				"description": "Manage move rules",
				"endpoints":   []string{"by-category"},
				"writable":    true,
			},
			{
				"name":        "firewall-control.protocols",
				"description": "Manage protocols",
				"endpoints":   []string{"get-by-category"},
			},
			{
				"name":        "firewall-control.remove-tags",
				"description": "Manage remove tags",
				"endpoints":   []string{"remove-rule-tags-by-category"},
				"writable":    true,
			},
			{
				"name":        "firewall-control.reorder",
				"description": "Manage reorder",
				"endpoints":   []string{"rules-by-category"},
				"writable":    true,
			},
			{
				"name":        "firewall-control.set-location",
				"description": "Manage set location",
				"endpoints":   []string{"by-category"},
				"writable":    true,
			},
			{
				"name":        "groups",
				"description": "groups operations",
				"endpoints":   []string{"create", "delete", "get", "get-by-id", "update", "update-ranks"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "groups.move-agents",
				"description": "Manage move agents",
				"endpoints":   []string{"move_agents"},
				"writable":    true,
			},
			{
				"name":        "groups.policy",
				"description": "Manage policy",
				"endpoints":   []string{"group", "update-group"},
				"writable":    true,
			},
			{
				"name":        "groups.regenerate-key",
				"description": "Manage regenerate key",
				"endpoints":   []string{"regenerate-group-token"},
				"writable":    true,
			},
			{
				"name":        "groups.revert-policy",
				"description": "Manage revert policy",
				"endpoints":   []string{"revert_policy"},
				"writable":    true,
			},
			{
				"name":        "hashes",
				"description": "hashes operations",
				"endpoints":   []string{},
			},
			{
				"name":        "hashes.classification",
				"description": "Manage classification",
				"endpoints":   []string{"hash"},
			},
			{
				"name":        "hashes.reputation",
				"description": "Manage reputation",
				"endpoints":   []string{"hash"},
			},
			{
				"name":        "installed-applications",
				"description": "installed-applications operations",
				"endpoints":   []string{"get", "get-cves"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "last-activity-as-syslog",
				"description": "last-activity-as-syslog operations",
				"endpoints":   []string{"message"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "locations",
				"description": "locations operations",
				"endpoints":   []string{"create", "delete", "get", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "ranger",
				"description": "ranger operations",
				"endpoints":   []string{"add-cred-details", "add-new-deploy-command-for-device-from-agent-from-task-infra", "change-device-review", "change-device-review-in-bulk", "change-device-tags", "create-cred-group", "delete-cred-group", "delete-cred-group-detail", "export-data", "get-cred-group-details", "get-cred-groups", "get-gateways", "get-settings", "get-table", "update-cred-group", "update-cred-group-details", "update-gateway", "update-gateways", "update-settings"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "ranger.json",
				"description": "Manage json",
				"endpoints":   []string{"export-raw-data", "raw-data"},
			},
			{
				"name":        "rbac",
				"description": "rbac operations",
				"endpoints":   []string{"create-new-role", "delete-role", "get-all-roles", "get-specific-role-definition", "get-template-for-new-role", "update-role"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "remote-scripts",
				"description": "remote-scripts operations",
				"endpoints":   []string{"get-scripts", "run", "upload-a-new-script"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "report-tasks",
				"description": "report-tasks operations",
				"endpoints":   []string{"create", "get", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "reports",
				"description": "reports operations",
				"endpoints":   []string{"delete", "delete-tasks", "download", "get", "get-insight"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "restrictions",
				"description": "restrictions operations",
				"endpoints":   []string{"create-blacklist-item", "delete-blacklist-item", "get-blacklist", "update-blacklist-item", "validate-blacklist-item"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "rogues",
				"description": "rogues operations",
				"endpoints":   []string{"export-data", "get-settings", "get-table", "update-settings"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "sentinelone-export",
				"description": "Manage sentinelone export",
				"endpoints":   []string{"activities", "agents", "events", "list-installed-applications", "threat-timeline"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "sentinelonerss",
				"description": "sentinelonerss operations",
				"endpoints":   []string{"s1-rss-feed"},
			},
			{
				"name":        "settings",
				"description": "settings operations",
				"endpoints":   []string{"clear-pending-emails", "delete-notification-recipient", "get-ad", "get-ad-fqdns", "get-microsoft", "get-notification", "get-notification-recipients", "get-sms", "get-smtp", "get-sso", "get-syslog", "set-ad", "set-ad-fqdns", "set-microsoft", "set-notification", "set-notification-recipients", "set-sms", "set-smtp", "set-sso", "set-syslog", "test-ad", "test-microsoft", "test-smtp", "test-sso", "test-syslog"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "singularity-marketplace",
				"description": "singularity-marketplace operations",
				"endpoints":   []string{"delete-marketplace-application", "enable-or-disable-application", "get-applications-catalog", "get-configuration-fields", "get-configuration-fields-for-catalog-application", "get-marketplace-applications", "install-applications", "update-application-configuration"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "site-with-admin",
				"description": "site-with-admin operations",
				"endpoints":   []string{"create-site-and-user"},
				"writable":    true,
			},
			{
				"name":        "sites",
				"description": "sites operations",
				"endpoints":   []string{"create", "create-duplicate", "delete", "get", "get-by-id", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "sites.expire-now",
				"description": "Manage expire now",
				"endpoints":   []string{"expire-site"},
				"writable":    true,
			},
			{
				"name":        "sites.policy",
				"description": "Manage policy",
				"endpoints":   []string{"site", "update-site"},
				"writable":    true,
			},
			{
				"name":        "sites.reactivate",
				"description": "Manage reactivate",
				"endpoints":   []string{"site"},
				"writable":    true,
			},
			{
				"name":        "sites.regenerate-key",
				"description": "Manage regenerate key",
				"endpoints":   []string{"regenerate-site-key"},
				"writable":    true,
			},
			{
				"name":        "sites.revert-policy",
				"description": "Manage revert policy",
				"endpoints":   []string{"revert_policy"},
				"writable":    true,
			},
			{
				"name":        "system",
				"description": "system operations",
				"endpoints":   []string{"cache-status", "database-status", "get-config", "info", "set-config", "status"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "tags",
				"description": "tags operations",
				"endpoints":   []string{"create", "delete", "delete-by-id", "edit", "get"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "tasks-configuration",
				"description": "tasks-configuration operations",
				"endpoints":   []string{"create-task", "get-child-scope-task-configuration", "get-task-configuration", "has-child-scopes"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "tenant",
				"description": "tenant operations",
				"endpoints":   []string{"global-policy", "update-global-policy"},
				"writable":    true,
			},
			{
				"name":        "tests",
				"description": "tests operations",
				"endpoints":   []string{"free-text-filters"},
			},
			{
				"name":        "threat-intelligence",
				"description": "threat-intelligence operations",
				"endpoints":   []string{"create-io-cs", "delete-io-cs"},
				"writable":    true,
			},
			{
				"name":        "threats",
				"description": "threats operations",
				"endpoints":   []string{"add-note-to-multiple", "add-to-blacklist", "add-to-exclusions", "disable-engines", "export", "export-mitigation-report", "fetch-file", "get", "mitigate", "update-analyst-verdict", "update-external-ticket-id", "updated-incident"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "threats.download-from-cloud",
				"description": "Manage download from cloud",
				"endpoints":   []string{"download_from_cloud"},
			},
			{
				"name":        "threats.explore",
				"description": "Manage explore",
				"endpoints":   []string{"get-events"},
			},
			{
				"name":        "threats.notes",
				"description": "Manage notes",
				"endpoints":   []string{"delete-threat", "get-threat", "update-threat"},
				"writable":    true,
			},
			{
				"name":        "threats.timeline",
				"description": "Manage timeline",
				"endpoints":   []string{"get-threat"},
			},
			{
				"name":        "threats.whitening-options",
				"description": "Manage whitening options",
				"endpoints":   []string{"exclusion-options"},
			},
			{
				"name":        "update",
				"description": "update operations",
				"endpoints":   []string{"delete-packages", "download-agent-package", "download-package", "get-latest-packages", "latest-packages-by-os", "package"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "upload",
				"description": "upload operations",
				"endpoints":   []string{"agent-package", "deploy-system-package", "system-package"},
				"writable":    true,
			},
			{
				"name":        "user",
				"description": "users operations",
				"endpoints":   []string{"by-token"},
				"searchable":  true,
			},
			{
				"name":        "users",
				"description": "users operations",
				"endpoints":   []string{"auth-app", "auth-by-sso", "auth-recovery-code", "bulk-delete", "change-password", "check-global", "check-remote-shell-permissions", "check-viewer", "create", "delete", "disable-2-fa", "email-verification", "enable-2-fa", "enable-2-fa-app", "generate-api-token", "generate-i-frame-token", "generate-recovery-code", "get", "list", "login", "login-by-api-token", "login-by-token", "logout", "redirect-to-sso", "request-2-fa-app", "revoke-api-token", "send-verification-email", "sign-eula", "token-details", "update", "validate-verification-token"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "users.api-token-details",
				"description": "Manage api token details",
				"endpoints":   []string{"token-by-user-id"},
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass cursor parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use createdAt__lt for incremental fetches (filter by modification time).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": registeredCommandMirrorCapabilities(s, []map[string]string{
			{"name": "Overnight Drift", "command": "whatchanged", "cli_command": "whatchanged", "description": "One answer to 'what changed across all my tenants since I logged off?", "rationale": "Diffs two historical store snapshots of agents, threats, and activities across every site", "via": "mcp-command-mirror"},
			{"name": "Threat Recurrence Hunter", "command": "threats recurrence", "cli_command": "threats recurrence", "description": "Surfaces threats whose same hash or name re-appears across endpoints — or returns on an endpoint after a prior", "rationale": "Joins threats by sha1/threatName across the full history table", "via": "mcp-command-mirror"},
			{"name": "Stale & Decaying Fleet", "command": "fleet-health stale", "cli_command": "fleet-health stale", "description": "Ranks endpoints by a composite decay score — last-seen age, last-scan age, out-of-date agent version", "rationale": "Fuses lastActiveDate, scanFinishedAt, agentVersion vs the fleet's modal version", "via": "mcp-command-mirror"},
			{"name": "Protection Coverage Gaps", "command": "coverage gaps", "cli_command": "coverage gaps", "description": "Lists endpoints in detect-only mode, with self-protection off", "rationale": "Cross-joins agent policy/mode fields with site and group membership to compute coverage holes and a coverage percentage", "via": "mcp-command-mirror"},
			{"name": "Version Rollout Tracker", "command": "versions rollout", "cli_command": "versions rollout", "description": "Shows agent-version distribution per site over time and flags sites stuck on EOL/old versions or stalled", "rationale": "Builds a time series of per-site version histograms from historical snapshots", "via": "mcp-command-mirror"},
			{"name": "MTTR & Triage SLA", "command": "threats mttr", "cli_command": "threats mttr", "description": "Computes mean time from threat detection to mitigation per site", "rationale": "Subtracts mitigation-event timestamps from detection timestamps across the activities and threats history and", "via": "mcp-command-mirror"},
			{"name": "Unmanaged Exposure Map", "command": "ranger exposure", "cli_command": "ranger exposure", "description": "Surfaces unmanaged/rogue endpoints on each subnet by cross-referencing Ranger-discovered devices against managed agents", "rationale": "Joins Ranger device-discovery inventory to the agent inventory on network identity (IP/subnet)", "via": "mcp-command-mirror"},
			{"name": "Blast Radius", "command": "threats blast-radius", "cli_command": "threats blast-radius", "description": "For one threat, instantly shows every endpoint it touched, which are mitigated vs still active", "rationale": "Joins one threat identity across all agents plus site/group membership plus per-endpoint mitigation status plus", "via": "mcp-command-mirror"},
			{"name": "Tenant Posture Scorecard", "command": "posture", "cli_command": "posture", "description": "A one-page per-tenant rollup — agent health %, coverage %, open-threat count, oldest unresolved", "rationale": "Rolls up every other derived metric per site into a single cross-entity composite", "via": "mcp-command-mirror"},
			{"name": "Verdict Reconciliation", "command": "threats verdicts", "cli_command": "threats verdicts", "description": "Flags threats whose analyst verdict, confidence level", "rationale": "Diffs the analystVerdict/confidenceLevel/incidentStatus fields against each threat's prior stored value", "via": "mcp-command-mirror"},
			{"name": "Triage Queue", "command": "threats triage", "cli_command": "threats triage", "description": "One ranked", "rationale": "Ranks all unresolved threats across every site by a composite the API exposes only as separate filter fields", "via": "mcp-command-mirror"},
			{"name": "Fleet Snapshot", "command": "fleet-health summary", "cli_command": "fleet-health summary", "description": "At-a-glance fleet counts — online/offline/decommissioned, infected, out-of-date", "rationale": "Multi-dimension rollup over the synced agents table; the raw API needs one filtered count query per dimension per site.", "via": "mcp-command-mirror"},
			{"name": "Endpoint Dossier", "command": "agents dossier", "cli_command": "agents dossier", "description": "Everything about one endpoint on one card: agent state, full threat history, recent activities", "rationale": "Fuses four entities (agent × threat history × activities × membership) from the local store", "via": "mcp-command-mirror"},
			{"name": "Exclusion Hygiene", "command": "exclusions audit", "cli_command": "exclusions audit", "description": "Flags risky exclusions — never matched by any threat, wildcard paths", "rationale": "Joins exclusions against the local threat history to compute matched/never-matched", "via": "mcp-command-mirror"},
			{"name": "Site Risk Ranking", "command": "sites risk", "cli_command": "sites risk", "description": "Ranks sites/clients against each other by composite risk — open-threat density, coverage gaps, stale agents", "rationale": "Composes per-site derived metrics across the whole local store into one cross-tenant ranking", "via": "mcp-command-mirror"},
		}),
		"playbook": []map[string]string{
			{"topic": "Overnight Drift", "insight": "Diffs two historical store snapshots of agents, threats, and activities across every site; the API returns current state only, with no cross-entity 'delta since T' endpoint."},
			{"topic": "Threat Recurrence Hunter", "insight": "Joins threats by sha1/threatName across the full history table, correlating mitigationStatus over time and grouping by agent; no Get_Threats call says '4th hit of this hash, twice mitigated'."},
			{"topic": "Stale & Decaying Fleet", "insight": "Fuses lastActiveDate, scanFinishedAt, agentVersion vs the fleet's modal version, and networkStatus/infected/isUpToDate into one weighted rank the API exposes only as separate filterable fields."},
			{"topic": "Protection Coverage Gaps", "insight": "Cross-joins agent policy/mode fields with site and group membership to compute coverage holes and a coverage percentage; no API call returns 'all agents NOT in protect mode grouped by site'."},
			{"topic": "Version Rollout Tracker", "insight": "Builds a time series of per-site version histograms from historical snapshots; the API gives a current-version filter but no week-over-week rollout progress or stall detection."},
			{"topic": "MTTR & Triage SLA", "insight": "Subtracts mitigation-event timestamps from detection timestamps across the activities and threats history and aggregates by tenant/analyst — a derived duration no single endpoint computes."},
			{"topic": "Unmanaged Exposure Map", "insight": "Joins Ranger device-discovery inventory to the agent inventory on network identity (IP/subnet) and counts managed-vs-unmanaged per network — two API surfaces the console never joins."},
			{"topic": "Blast Radius", "insight": "Joins one threat identity across all agents plus site/group membership plus per-endpoint mitigation status plus first/last-seen into a spread timeline; the API returns threat rows, not an endpoint-joined containment view."},
			{"topic": "Tenant Posture Scorecard", "insight": "Rolls up every other derived metric per site into a single cross-entity composite; the API has no tenant-level posture object."},
			{"topic": "Verdict Reconciliation", "insight": "Diffs the analystVerdict/confidenceLevel/incidentStatus fields against each threat's prior stored value; the API returns the current verdict only, never a before/after."},
			{"topic": "Triage Queue", "insight": "Ranks all unresolved threats across every site by a composite the API exposes only as separate filter fields; the console shows one tenant's threat blade at a time."},
			{"topic": "Fleet Snapshot", "insight": "Multi-dimension rollup over the synced agents table; the raw API needs one filtered count query per dimension per site."},
			{"topic": "Endpoint Dossier", "insight": "Fuses four entities (agent × threat history × activities × membership) from the local store; the API requires four separate calls and manual correlation."},
			{"topic": "Exclusion Hygiene", "insight": "Joins exclusions against the local threat history to compute matched/never-matched; the API lists exclusions but can't say whether one ever fired."},
			{"topic": "Site Risk Ranking", "insight": "Composes per-site derived metrics across the whole local store into one cross-tenant ranking; no API object compares tenants."},
			{"topic": "Finding stale work", "insight": "Use the stale command or sql query to find items not updated recently. More reliable than scanning list results manually."},
			{"topic": "Load analysis", "insight": "When analyzing team workload, filter by assignee and status. Raw counts without status filtering are misleading."},
			{"topic": "Bulk operations", "insight": "For bulk status changes, prefer update endpoints over delete+create. Most PM APIs track history on updates."},
		},
	}
	return toolResultJSON(ctx)
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
